### ISSUE TITLE
A survey with a CS configured that doesn't exist in the server makes the app crash

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#1006]

**Comment by ifoche** [comment]
to test in hnqis.psi-mis.org server

**Comment by josemp10** [comment]
You can test it in hnqis-dev.psi-mis.org as well. It contains a copy of the
hnqis database...

**Comment by idelcano** [comment]
I did reproduced this problem changing the hierarchical code of the CS called "Newborn Resuscitation" in dev sever (after, i restored the correct hirearchical code).

I tried to reproduce this problem changing the composite score of some questions, but the application works right in that case.

https://github.com/EyeSeeTea/malariapp/pull/1012 customtabs
https://github.com/EyeSeeTea/malariapp/pull/1011 hnqis
