### ISSUE TITLE
Tabs not showing questions inside

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#1039]

**Comment by ifoche** [comment]
See [screenshot](https://camo.githubusercontent.com/48f879c4317d898d155244a235c1e50ece3ed83d/68747470733a2f2f73332d75732d776573742d322e616d617a6f6e6177732e636f6d2f62756464796275696c642d73637265656e73686f74732f3536626262636536636435316134303130306430336136652f3537333362376635383437643937303130303730393333362f36303861646632352d366134382d346365332d393335642d6238313232393166303833372e6a7067)

**Comment by ifoche** [comment]
Apparently only a metadata refresh solves the issue

**Comment by idelcano** [comment]
@ifoche  the problem are in our pull, or in the server metadata.

The server have some "duplicated" programs.
For example the programs:
"UCSahd652pz"	"1. General OTSS"
and
"gogdZwD7KDS"	"DO NOT EDIT - 1. General OTSS"

All the dataelements in this programs are the same (Questions, compositescores, uids..).

And we only convert the first dataelement in the pull.

I worked this night in identify the problem and pull all the dataelements, duplicated dataelements incluided.

I only have a problem with the match/parent relations at this moment,  i need duplicate the relations too...
For example:
Question A with uid X with header Y (header-tab-tabgroup-program) 
Question A with uid X with header D (header-tab-tabgroup-program) 
And the matc/parent relations are created only with the first.

But  i think the best solution maybe  is create a new table  with the relation (Question 1-N headers).

Or more simple,do not allow programs with dataelement duplicated in the server.

**Comment by josemp10** [comment]
Yes, it is possible, in the server configuration, to share dataelements
accross several programs (actually control dataelements are being shared in
all programs). And this would be something that may happen frequently in
the future.
