### ISSUE TITLE
Num/dem preference make the custom tabs blank

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#1046]

**Comment by ifoche** [comment]
When you click on the preference the tab goes blank, and it never recovers, even unclicking the num/dem setting again

**Comment by idelcano** [comment]
Do you have more infomation about that? What tab goes blank, resolution, device... It is working for me.

**Comment by idelcano** [comment]
Ok. It is not working in custom_tab branch, but is solved in other branch (branch bug-fix_compositeScore_bug)
