### ISSUE TITLE
In the improve tab, show all the assessments in the DB, not only the last one for each OU

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#1049]

**Comment by ifoche** [comment]
As in HNQIS we're supposed to show only the last one, while in EDS they're asking to show all the assessments, I would say that the best option is to include a setting in the json configuration (something like listFilter: 'lastForOU'|'none') so we can configure the surveys filter depending on the json setting in each variant

**Comment by idelcano** [comment]
We are pulling only the last event data using:
                    job = DhisService.loadLastData(context);)
is necessary change it?
I can change it to: 
if filter is none:
                     job = DhisService.loadData(context);) (download all events)
else 
                    job = DhisService.loadLastData(context);) (only download last events)
