### ISSUE TITLE
H14.1 Several media x question

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/malariapp#1074]
1 Question N media
Shown as a list inside feedback

**Comment by ifoche** [comment]
DataElement 
"KE HNQIS HIV-160-HTC-Seek clarification and obtains verbal or written consent ( if the client decides to test)"
is now configured with attribute video URL set to:
0B8KIRhh6kcl6UmNZbHB5YXliMG8#0B8KIRhh6kcl6SUhBdmVYT0ZhMjQ
Both are medias that already exist in other DEs

**Comment by ivanarrizabalaga** [comment]
Great thanks!

**Comment by ivanarrizabalaga** [comment]
@ifoche I think I got it working now but it looks like there is only 1 'good' video x question (maybe the second one is the mov video which is skipped since it cant be reproduced properly).

Can you try to add a second different mp4 video (or image mixing both should work too) for the same question?
