### ISSUE TITLE
Create architecture to pull data from DHIS2

### ISSUE THREAD

**Issue by josemp10** [EyeSeeTea/malariapp#109]

**Comment by ifoche** [comment]
Is it a duplicate of #32 ?

**Comment by josemp10** [comment]
No. Bueno... yo creo que habría que renombrar - re-escribir...

A la actividad que creé debería haberla llamado "Create architecture to
pull *metadata *from DHIS2". No es solo Automatic Questions, son todas las
questions (automatics or not), surveys, orgunits, etc. es decir toda la
metadata que esté en DHIS2..

**Comment by ifoche** [comment]
ok, entonces, marco éste como duplicado, lo cierro, cambio el nombre a la otra y la reasigno a tí. Te parece?

**Comment by josemp10** [comment]
Sí, ok. O reasígnala a los dos (creo que se puede). Es verdad que no me di
cuenta de la otra.... yo iba a empezar a trabajar en esto esta semana, pero
vamos viendo cómo dividir el trabajo si quieres. También las otras tareas
que creé hoy formarían parte de la del Pull (Map DHIS2 API, Map
DataElements,....). Estaría bien referir también cada una de ellas como
partes del todo, Otherwise "pull from DHIS2" será una task de lo menos 50 o
60 horas...
