### ISSUE TITLE
Map Data Elements Groups

### ISSUE THREAD

**Issue by josemp10** [EyeSeeTea/malariapp#110]

**Comment by ifoche** [comment]
I really don't understand very well this task. Jose, can you explain it a bit so when we can understand it whenever we put it in the releases notes? Just a little clarifying sentence

**Comment by josemp10** [comment]
Esta tarea ya no tenía sentido, así que cerrela. I don't know if there was
a better way to close it (I wanted to remove it)

**Comment by ifoche** [comment]
I usually put the label "invalid" to distinguish later which tasks are done and which ones have been rejected. I even wanted to create a "rejected" column to make it automatically in waffle, but apparently this is not possible.
