### ISSUE TITLE
Update picture cherry-pick branch and include laos variant

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#1103]

**Comment by ifoche** [comment]
This would include:
- [ ] Update feature-Add_new_pictureapp_compoments branch with last development made on custom_tabs
- [ ] Create the new laos variant in malariapp repo and bring the lao and thai translations to it
- [ ] Ensure that either the thai/lao translations either the khmer translation are each of them present in their branch, and not in the main folder, to avoid forcing the app to include translations to those languages when building a variant that doesn't use them

**Comment by idelcano** [comment]
@ifoche i finished feature-Add_new_pictureapp_compoments
I included the thai lao (boon) font license too .
