### ISSUE TITLE
parent-child optimisation

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#1144]

**Comment by ivanarrizabalaga** [comment]
Sample Family Planning

*Does this facility offer contraceptive counseling?* (with 15 children)

 - Original time: **(to complete)**
 - After optimizations: **1.2sec**

**Comment by ivanarrizabalaga** [comment]
**Suggestions:**
 - getView: use convertView
 - move calculations away from main thread
 - simplify layouts
 - duplicate xml for num/den to avoid programatical changes

**Comment by adrianq** [comment]
@idelcano Let's start:
- [ ]  Simplify layouts: Review ddl, remove relative layouts...
- [ ] duplicate xml for num and den: radio, ddl, etc.

**Comment by adrianq** [comment]
This card is done. Parent-child optimisation is working great now, it is pretty fast and smooth in almost every device. We have created [another card](https://github.com/EyeSeeTea/malariapp/issues/1155) that is about some minor stuff. However it is more about code management and clean up task than actual performance issues.
