### ISSUE TITLE
i18n Survey contents?

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/malariapp#118]
Why caring about english, french and spanish (ui) when the questions are only in english?

Does it make sense to care about the questions and options as translatable content?

I guess It would be an important effort but also an great feature.

**Comment by ifoche** [comment]
It was the client who asked us for doing it. In principle, it has more sense to be able to translate the interface, just to let them see "how would it look like", and whenever the have the final version for the questions, make the effort of translating also that heavy amount of data.

**Comment by josemp10** [comment]
Some time early next week, we are probably going to have a new sets of questions in Khmer http://es.wikipedia.org/wiki/Idioma_camboyano, a language only spoken in Cambodia (10 million people in  the world)
