### ISSUE TITLE
Continuous doc: Integrate readthedocs + github

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/malariapp#120]

**Comment by adrianq** [comment]
@ivanarrizabalaga Done. Let me know if you have any problem

**Comment by ivanarrizabalaga** [comment]
@adrianq
A quick hangout to close this issue?

**Comment by ivanarrizabalaga** [comment]
@adrianq

Simply confirm that everything is ok:
http://health-network-qis.readthedocs.org/

It will get better with time.

**Comment by adrianq** [comment]
@ivanarrizabalaga Great! I checked it a couple of times during the evening but it was not working yet. I guess it took more than a couple of minutes to build it (maybe because it was the first time). Thank you for this!
