### ISSUE TITLE
Survey tab error

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/malariapp#122]
When you try to open the 'survey' tab the app crashes.

After debuggin' a little bit it seems the error is here:

SurveyActivity (line 187):
        if (adaptersList.get(10) != null) {
            tab1 = adaptersList.get(10).getScore();
            ((TextView) this.findViewById(R.id.profileScore)).setText(Utils.round(tab1));

CompositiveScoreAdapter (line 75):
    public Float getScore() {
        return null;
    }

**Comment by ivanarrizabalaga** [comment]
@EyeSeeTea/ifoche this one is the error I told you

**Comment by ifoche** [comment]
This was solved in a very ugly way. We need to find soon a much clean way to implement general scores
