### ISSUE TITLE
Get events from server using new sdk

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#1236]

**Comment by idelcano** [comment]
Maliarapp branch: https://github.com/EyeSeeTea/malariapp/tree/feature-new_sdk

sdk branch: https://github.com/EyeSeeTea/dhis2-android-sdk/tree/feature-sdk_update_with_temp

**Comment by idelcano** [comment]
The pull has a null exception in the conversion because some dataelement attributes not exists, we should comment it to finish the pull. 
https://github.com/EyeSeeTea/malariapp/blob/feature-new_sdk/app/src/main/java/org/eyeseetea/malariacare/sdk/SdkPullController.java#L129 Comment this line.

I tried this methods:


getEvents();
getEvents("IrppF3qERB7","Nxw94OjsCjS");


public static void    getEvents( ) {
    //Observer form server 
    Set<String> uids = new HashSet<String>();
    uids.add("sfsHw30FfA0");
    final Observable<List<Event>> eventListObservable = D2.events().pull(uids);
    eventListObservable.
            subscribeOn(Schedulers.io()).
            observeOn(AndroidSchedulers.mainThread())
            .subscribe(new Action1<List<Event>>() {
                @Override
                public void call(List<Event> events) {
                    //// FIXME: 22/11/2016 return event
                    Log.d("Eventos", "eventos" + events.size());
                }
            }, new Action1<Throwable>() {
                @Override
                public void call(Throwable throwable) {
                    Log.d("Eventos", "eventos error");
                }
            });
}
public static void getEvents(String organisationUnitUId, String programUId) {
    ProgramFlow programFlow = getProgram(programUId);
    OrganisationUnitFlow organisationUnitFlow = getOrganisationUnit(organisationUnitUId);
    OrganisationUnit organisationUnit = OrganisationUnitFlow.MAPPER.mapToModel
            (organisationUnitFlow);

    org.hisp.dhis.client.sdk.models.program.Program program = ProgramFlow.MAPPER.mapToModel(programFlow);
    Observable<List<Event>> eventListObservable = D2.events().list(
            organisationUnit,
            program);
    eventListObservable.
            subscribeOn(Schedulers.io()).
            observeOn(AndroidSchedulers.mainThread())
            .subscribe(new Action1<List<Event>>() {
                @Override
                public void call(List<Event> events) {
                    //// FIXME: 22/11/2016 return event
                    Log.d("Eventos", "eventos" + events.size());
                }
            }, new Action1<Throwable>() {
                @Override
                public void call(Throwable throwable) {
                    Log.d("Eventos", "eventos error");
                }
            });
}
