### ISSUE TITLE
Review gradle lint errors

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/malariapp#127]
Right now:

./gradlew lint 

shows 13 errors + 219 warnings.

Most of them are not important, but we need to clean them up sooner or later.

**Comment by ivanarrizabalaga** [comment]
Errors
---------------
 - Correctness
    - [ ] 13	Error MissingPrefix: Missing Android XML namespace  
 - Correctness:Messages
    - [ ] 1	Error StringFormatInvalid: Invalid format string    

Warnings
---------------
 - Correctness

    - [ ] 1	Warning InconsistentArrays: Inconsistencies in array element counts
    - [ ] 2	Warning AppCompatMethod: Using Wrong AppCompat Method
    - [ ] 1	Warning DuplicateIncludedIds: Duplicate ids across layouts combined with include tags
    - [ ] 1	Warning InlinedApi: Using inlined constants on older versions
    - [ ] 1	Warning OldTargetApi: Target SDK attribute is not targeting latest version
    - [ ] 1	Warning SimpleDateFormat: Implied locale in date format
    - [ ] 27	Warning UnusedAttribute: Attribute unused on older versions
    - [ ] 1	Warning InflateParams: Layout Inflation without a Parent
    - [ ] 1	Warning GradleDependency: Obsolete Gradle Dependency
    - [ ] 2	Warning GradleOverrides: Value overridden by Gradle build script
    - [ ] 1	Warning Deprecated: Using deprecated resources
    - [ ] 8	Warning PxUsage: Using 'px' dimension

- Performance

    - [ ] 12	Warning ObsoleteLayoutParam: Obsolete layout params
    - [ ] 7	Warning ViewHolder: View Holder Candidates
    - [ ] 1	Warning UseValueOf: Should use valueOf instead of new
    - [ ] 15	Warning DisableBaselineAlignment: Missing baselineAligned attribute
    - [ ] 1	Warning InefficientWeight: Inefficient layout weight
    - [ ] 3	Warning Overdraw: Overdraw: Painting regions more than once
    - [ ] 44	Warning UnusedResources: Unused resources
    - [ ] 22	Warning UselessParent: Useless parent layout

- Usability:Icons

    - [ ] 1	Warning IconColors: Icon colors do not follow the recommended visual style
    - [ ] 1	Warning IconMissingDensityFolder: Missing density folder

- Usability

    - [ ] 1	Warning TextFields: Missing inputType or hint

- Accessibility

    - [ ] 2	Warning ClickableViewAccessibility: Accessibility in Custom Views
    - [ ] 1	Warning ContentDescription: Image without contentDescription

- Internationalization

    - [ ] 9	Warning HardcodedText: Hardcoded text

- Bi-directional Text

    - [ ] 21	Warning RtlSymmetry: Padding and margin symmetry
    - [ ] 54	Warning RtlHardcoded: Using left/right instead of start/end attributes
    - [ ] 1	Warning RtlEnabled: Using RTL attributes without enabling RTL support

**Comment by ifoche** [comment]
For warnings see #206
