### ISSUE TITLE
Pull fail for NullPointerException in conversions for ifoche_test2

### ISSUE THREAD

**Issue by xurxodev** [EyeSeeTea/malariapp#1289]

**Comment by idelcano** [comment]
@xurxodev  the problem is with this event: hzHn90CGBSZ

And it is solved changing this line(371) in convertfromsdk:
if (event.getEventDate() == null || event.getEventDate().equals("")) {
                   
                    if (event.getEvent().getEventDate() == null
                            || event.getEvent().getEventDate().equals("")) {

Anyway all the events should has eventdate, the problem is the that event should have pushed with eventdate.
