### ISSUE TITLE
Cannot open saved survey

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/malariapp#137]
Once you create a survey and fulfill some questions, if you go back to the dashboard activity you cannot open the survey again.

After a quick review it looks like 'AssessmentAdapter' does not create any listener for the 2 first columns

**Comment by ifoche** [comment]
Thank you very much. We saw it yesterday in the middle of the presentation and it was not yet solved. I'll go for it now

**Comment by ifoche** [comment]
Quick overview: It looks like it happens only with the last survey. Sounds an index problem (not reaching last element). Let's bebug

**Comment by ifoche** [comment]
Ok, it was a simple position that had to be (position-1). Looks like ListView returns the position counting also the header as a position, so every item position is increased by one.

**Comment by ivanarrizabalaga** [comment]
Cool!
