### ISSUE TITLE
Test Using Samsung Tab 3 | 7''

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#140]

**Comment by ifoche** [comment]
@josemp10 . How can we do for sending me the tab? As finally Adri didn't go to your house he didn't bring it to me. Would it be possible to send me by any other way?

**Comment by ifoche** [comment]
@josemp10 . Are these messages reaching you? Maybe is better to send you using the @EyeSeeTea/owners group

**Comment by ifoche** [comment]
@josemp10 . Jose, are you reading this?

**Comment by josemp10** [comment]
ahm... by mail I gues... (some kind of MRW or something, don't know here in London).  Or I can try to get your home  next weekend from Bilbao.... I don't know.

**Comment by ifoche** [comment]
I think that @adrianq is already at Madrid and so, maybe the best is as you say, to wait until you're in Bilbao. However, I'm leaving Bayonne at the end of this month (I will make the mail to be resent to Oviedo so I can receive it when we go to Oviedo the second half of the summer). The doubt then is...
- If you send me the tablet to Bayonne and it arrives after 30 june, it will be resent to Oviedo and I won't have it until August, otherwise I'll have it immediately.
- If you send me the tablet to Jaen I will have it for sure the 2nd week of July. 

What do you think is the best? :)

**Comment by josemp10** [comment]
The second week of July in Jaen...

How many days are you planing to stay there?

**Comment by adrianq** [comment]
@ifoche We are meeting in Cadiz the 11th July. Maybe it is better is @josemp10 gives me the tab in London and I bring it with me to Malaga. So we save a few pounds at lest and we are not worry about the delivery.

**Comment by josemp10** [comment]
ey.... I will be in Andalucia too by that time   (I am going to Cordoba on
the 8th). What are your plans guys?

**Comment by ifoche** [comment]
It sounds better your option @adrianq for the tablet. For the holidays I think it's better if we continue talking by other messaging system, but it sounds great to have you both at home, in my place with a big beer and very good climate ;)

**Comment by josemp10** [comment]
Don't know.  Solo podríamos quedar el Miércoles o el Jueves de la siguiente semana  (el Viernes me marcho a la mañana a Spain, y ya probablemente no vuelva en un mes). Y esos dos días estoy petadísimo. Vamos viendo...

**Comment by josemp10** [comment]
I am going  to be tomorrow Wednesday all day at Rodolfo's office, so we only have Thursday to give you the tablet.  Could it work for you? I don't know yet for me. If we can not make it, we have 2 options:

1) Taking the tablet  with me to Spain and send it to Jaen from Asturias
2) Leaving the tablet in Balham, so you may need to cross the city to get it.

Both options are fine to me ...
