### ISSUE TITLE
Draw a sample picture of our database using the DHIS2-SDK database model

### ISSUE THREAD

**Issue by josemp10** [EyeSeeTea/malariapp#156]

**Comment by josemp10** [comment]
So we can analyze pros and cons much better

**Comment by josemp10** [comment]
https://www.lucidchart.com/documents/edit/49531d7b-56ce-4abf-bcad-6f28507aab63

**Comment by adrianq** [comment]
@josemp10 can the doc be accessed by anybody? I can find it. Have you placed it in the right folder?

**Comment by ifoche** [comment]
@josemp10 @adrianq me neither. I cannot see it. Is it properly shared with everyone?

**Comment by josemp10** [comment]
Ala, ya está...
