### ISSUE TITLE
Add attributes to DHIS2-SDK

### ISSUE THREAD

**Issue by josemp10** [EyeSeeTea/malariapp#158]

**Comment by adrianq** [comment]
Assigning this issue to me as it has to do with the PR to Oslo which will add the new  features

**Comment by ifoche** [comment]
This is related to #170

**Comment by ifoche** [comment]
For the moment, we have Attribute table filled, and I'm now mapping AttributeValues (that is a little bit more complicated as there's no direct call in the API for getting all the AttributeValues at once)

**Comment by ifoche** [comment]
@idelcano, @ivanarrizabalaga, you can update attributes_pull branch. Attributes should be properly being downloaded from now on.

**Comment by idelcano** [comment]
Great!
@ifoche the DataElementAttributeValue dataElementId(is a uid)  is saved with " " .
Example: "vWgsPN1RPLl". it should be vWgsPN1RPLl.

**Comment by ifoche** [comment]
you're right! Please update again, it was a stupid mistake when translating the json value.
