### ISSUE TITLE
change compositive by composite

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#162]

**Comment by ivanarrizabalaga** [comment]
Files to rename:
	CompositiveScores.csv
	CompositiveScore.java
	CompositiveScoreAdapter.java	
	CompositiveNumDenRecord.java		
	compositivescoretab.xml
	compositive_scores_record.xml
	survey_compositive_scores.png


Search ocurrences:
	

Targets
    Occurrences of 'Compositive' in Project
Found Occurrences  (66 usages found)
    Unclassified occurrence  (59 usages found)
        app  (58 usages found)
              (2 usages found)
                Tabs.csv  (2 usages found)
                    (12: 5) 18;'Compositive Scores';12;1;4
                    (14: 5) 20;'Compositive Scores';3;2;4
            app/src/androidTest/java/org/eyeseetea/malariacare/test  (3 usages found)
                LoginActivityEspressoTest.java  (1 usage found)
                    (35: 49) import org.eyeseetea.malariacare.database.model.CompositiveScore;
                MalariaEspressoTest.java  (2 usages found)
                    cleanDB()  (1 usage found)
                        (80: 9) CompositiveScore.deleteAll(CompositiveScore.class);
                    (30: 49) import org.eyeseetea.malariacare.database.model.CompositiveScore;
            org.eyeseetea.malariacare  (5 usages found)
                SurveyActivity.java  (5 usages found)
                    onCreate(Bundle)  (3 usages found)
                        (81: 14) List<CompositiveScore> compositiveScores = new ArrayList<CompositiveScore>();
                        (85: 14) for (CompositiveScore compositiveScore : CompositiveScore.listAll(CompositiveScore.class)) {
                        (104: 42) adaptersMap.put(tab, new CompositiveScoreAdapter(compositiveScores, this, R.layout.compositivescoretab, tab.getName()));
                    (45: 49) import org.eyeseetea.malariacare.database.model.CompositiveScore;
                    (53: 57) import org.eyeseetea.malariacare.layout.adapters.survey.CompositiveScoreAdapter;
            org.eyeseetea.malariacare.database.model  (17 usages found)
                CompositiveScore.java  (13 usages found)
                    CompositiveScore()  (1 usage found)
                        (22: 12) public CompositiveScore() {
                    CompositiveScore(String, String, CompositiveScore)  (1 usage found)
                        (25: 12) public CompositiveScore(String code, String label, CompositiveScore compositive_score) {
                    equals(Object)  (1 usage found)
                        (100: 9) CompositiveScore that = (CompositiveScore) o;
                    getCompositive_score()  (1 usage found)
                        (43: 12) public CompositiveScore getCompositive_score() {
                    getCompositiveScoreChildren()  (2 usages found)
                        (55: 17) public List<CompositiveScore> getCompositiveScoreChildren() {
                        (57: 46) this._compositiveScoreChildren = CompositiveScore.find(CompositiveScore.class, "compositivescore = ?", String.valueOf(this.getId()));
                    getSingleQuestionIncludingChildren()  (1 usage found)
                        (80: 18) for (CompositiveScore cScore : this.getCompositiveScoreChildren())
                    hasChildren()  (1 usage found)
                        (72: 20) return !getCompositiveScoreChildren().isEmpty();
                    hasParent()  (1 usage found)
                        (52: 19) return getCompositive_score() != null;
                    setCompositive_score(CompositiveScore)  (1 usage found)
                        (47: 20) public void setCompositive_score(CompositiveScore compositive_score) {
                    (10: 14) public class CompositiveScore extends SugarRecord<CompositiveScore> {
                    (14: 5) CompositiveScore compositive_score;
                    (17: 10) List<CompositiveScore> _compositiveScoreChildren;
                Question.java  (4 usages found)
                    getCompositiveScore()  (1 usage found)
                        (142: 12) public CompositiveScore getCompositiveScore() { return compositiveScore; }
                    Question(String, String, String, String, String, Integer, Float, ...)  (1 usage found)
                        (39: 207) CompositiveScore
                    setCompositiveScore(CompositiveScore)  (1 usage found)
                        (144: 20) public void setCompositiveScore(CompositiveScore compositiveScore) { this.compositiveScore = compositiveScore; }
                    (25: 5) CompositiveScore compositiveScore;
            org.eyeseetea.malariacare.database.utils  (7 usages found)
                PopulateDB.java  (6 usages found)
                    populateDB(AssetManager)  (4 usages found)
                        (89: 25) CompositiveScore compositiveScore = new CompositiveScore();
                        (92: 70) if (!line[3].equals("")) compositiveScore.setCompositive_score(compositiveScoreList.get(Integer.valueOf(line[3])));
                        (109: 84) if (line.length == 13 && !line[12].equals("")) question.setCompositiveScore(compositiveScoreList.get(Integer.valueOf(line[12])));
                        (153: 9) CompositiveScore.saveInTx(compositiveScoreList.values());
                    (8: 49) import org.eyeseetea.malariacare.database.model.CompositiveScore;
                    (35: 25) static Map<Integer, CompositiveScore> compositiveScoreList = new LinkedHashMap<Integer, CompositiveScore>();
                ReadWriteDB.java  (1 usage found)
                    (24: 49) import org.eyeseetea.malariacare.database.model.CompositiveScore;
            org.eyeseetea.malariacare.layout.adapters.survey  (9 usages found)
                CompositiveScoreAdapter.java  (9 usages found)
                    CompositiveScoreAdapter(List<CompositiveScore>, Context, int, String)  (1 usage found)
                        (50: 12) public CompositiveScoreAdapter(List<CompositiveScore> items, Context context, int id_layout, String tab_name) {
                    getView(int, View, ViewGroup)  (2 usages found)
                        (108: 9) CompositiveScore item = (CompositiveScore) getItem(position);
                        (115: 52) Float compositive_value = ScoreRegister.getCompositiveScore(item);
                    initializeSubscore()  (3 usages found)
                        (62: 19) ListView lCompositiveScores = (ListView) ((Activity) context).findViewById(R.id.listView);
                        (64: 92) ViewGroup header = (ViewGroup) lInflater.inflate(R.layout.compositivescoreheader, lCompositiveScores, false);
                        (65: 10) lCompositiveScores.addHeaderView(header);
                    (32: 49) import org.eyeseetea.malariacare.database.model.CompositiveScore;
                    (42: 14) public class CompositiveScoreAdapter extends BaseAdapter implements ITabAdapter {
                    (44: 10) List<CompositiveScore> items;
            org.eyeseetea.malariacare.layout.score  (15 usages found)
                CompositiveNumDenRecord.java  (4 usages found)
                    readNumDen(CompositiveScore, List<Float>)  (2 usages found)
                        (29: 35) public List<Float> readNumDen(CompositiveScore compositiveScore, List<Float> numDenTotal){
                        (33: 18) for (CompositiveScore compositiveScoreChild: compositiveScore.getCompositiveScoreChildren()){
                    (22: 49) import org.eyeseetea.malariacare.database.model.CompositiveScore;
                    (26: 14) public class CompositiveNumDenRecord extends ANumDenRecord{
                ScoreRegister.java  (11 usages found)
                    addRecord(Question, Float, Float)  (2 usages found)
                        (38: 25) if (question.getCompositiveScore() != null) {
                        (39: 54) compositiveScoreRegister.get(question.getCompositiveScore()).addRecord(question, num, den);
                    deleteRecord(Question)  (2 usages found)
                        (45: 25) if (question.getCompositiveScore() != null)
                        (46: 54) compositiveScoreRegister.get(question.getCompositiveScore()).deleteRecord(question);
                    getCompositiveScore(CompositiveScore)  (1 usage found)
                        (65: 28) public static Float getCompositiveScore(CompositiveScore cScore) {
                    getRecursiveScore(CompositiveScore, List<Float>)  (2 usages found)
                        (50: 50) private static List<Float> getRecursiveScore(CompositiveScore cScore, List<Float> result) {
                        (55: 18) for (CompositiveScore cScoreChildren : cScore.getCompositiveScoreChildren())
                    registerScore(CompositiveScore)  (2 usages found)
                        (79: 38) public static void registerScore(CompositiveScore compositiveScore){
                        (80: 60) compositiveScoreRegister.put(compositiveScore, new CompositiveNumDenRecord());
                    (22: 49) import org.eyeseetea.malariacare.database.model.CompositiveScore;
                    (34: 30) private static final Map<CompositiveScore, CompositiveNumDenRecord> compositiveScoreRegister = new HashMap<CompositiveScore, CompositiveNumDenRecord>();
        malariapp  (1 usage found)
            docs  (1 usage found)
                index.md  (1 usage found)
                    (63: 5) ### Compositive tab
    Usage in comments  (1 usage found)
        app  (1 usage found)
            app/src/androidTest/java/org/eyeseetea/malariacare/test  (1 usage found)
                SurveyEspressoTest.java  (1 usage found)
                    change_to_compositive_score()  (1 usage found)
                        (147: 25) //WHEN: Select 'Compositive Score' tab
    Usage in string constants  (6 usages found)
        app  (6 usages found)
            org.eyeseetea.malariacare  (3 usages found)
                SurveyActivity.java  (3 usages found)
                    onCreate(Bundle)  (2 usages found)
                        (83: 47) Log.i(".SurveyActivity", "Registering Compositive Score");
                        (103: 39) if (tab.getName().equals("Compositive Scores"))
                    showTab(Tab)  (1 usage found)
                        (168: 100) if (selectedTab.getType() == Constants.TAB_SCORE_SUMMARY && !selectedTab.getName().equals("Compositive Scores"))
            org.eyeseetea.malariacare.database.model  (1 usage found)
                CompositiveScore.java  (1 usage found)
                    toString()  (1 usage found)
                        (88: 17) return "CompositiveScore{" +
            org.eyeseetea.malariacare.database.utils  (2 usages found)
                PopulateDB.java  (2 usages found)
                    populateDB(AssetManager)  (2 usages found)
                        (44: 128) CompositiveScores
                        (88: 27) case "CompositiveScores.csv":
