### ISSUE TITLE
Double pane bug

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#164]

**Comment by ifoche** [comment]
Ivan, I've renamed the landscape xml file for dashboard to unused_dashboard.xml in order to have it working without the double pane, and added in DashboardFragment.java a line that says:
mDualPane = false;
I think this way we don't use the double pane for this deliverable, but the code's still there whenever you reach this bug. Please, ask me if you have any doubt whenever you start with this.

**Comment by ivanarrizabalaga** [comment]
Understood, ok!


[image: http://]
Ivan Arrizabalaga
[image: http://]about.me/ivan-arrizabalaga
<http://about.me/ivan-arrizabalaga>

**Comment by ifoche** [comment]
Solved with the new Dashboard. Be careful whenever we move again to the old one
