### ISSUE TITLE
change min sdk to 15/16

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#169]

**Comment by ifoche** [comment]
@ivanarrizabalaga, we need this to be done for tomorrow, do yo think this is going to be done by that date?

**Comment by ivanarrizabalaga** [comment]
Sure, I will create the pull request at 16h or so.



[image: http://]
Ivan Arrizabalaga
[image: http://]about.me/ivan-arrizabalaga
<http://about.me/ivan-arrizabalaga>

**Comment by ifoche** [comment]
@ivanarrizabalaga Perfect, thanks
