### ISSUE TITLE
Dashboard assessments alignment and indentaion

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#187]
repair it

**Comment by ivanarrizabalaga** [comment]
I cant really see any problem here:
Already solved somehow?

![dashboard_list](https://cloud.githubusercontent.com/assets/4146319/8087662/92e998d0-0f9c-11e5-8584-9d1476d9a2b6.png)

**Comment by ifoche** [comment]
have you checked it with Galaxy Note 2, Android 4.2.2 ? This is the standard device we have to verify the look & feel

![screenshot from 2015-06-10 20 48 20](https://cloud.githubusercontent.com/assets/10931645/8091145/655a66ea-0fb2-11e5-9709-f820689ec998.png)
