### ISSUE TITLE
Improve footer

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#189]
- [ ] Put a shadow above the score bar to clearly separate it from the rest of the form
- [ ] Put an alpha channel to change the color of the score bar (to separate it from the rest)
- [ ] Put the numerical score and the qualitative score in the same line

**Comment by ivanarrizabalaga** [comment]
Finally:
 - [x] Separate footer from form by adding a top gray border.
 - [x] Numerical and qualitative score inline.

**Comment by ivanarrizabalaga** [comment]
- [ ] Add some padding
 - [ ] % in same color
