### ISSUE TITLE
Add the survey "Social Franchise" in the databse

### ISSUE THREAD

**Issue by josemp10** [EyeSeeTea/malariapp#192]

**Comment by ifoche** [comment]
Is this a 3rd type of survey? If that is the case, please let me know. The way I implemented how the surveys are grouped in the dashboard is only valid for 2 different type of surveys, so I should reimplement a little part to make it works for n

**Comment by josemp10** [comment]
Yes, it is a new type os survey (sorry :) ).

**Comment by josemp10** [comment]
The import needs to be done by next Monday (8 th of June). Do you think we are going to have the capability of grouping n type of surveys by then? Thanks

**Comment by ifoche** [comment]
I don't think so, but don't worry. The only thing that will happen is that dashboard will look a little bit uglier. Surveys will alternatively show or hide their orgUnit name and a different background, but I wouldn't expect no app crash. But is good to know that this will be uploaded on monday, so I can that day work on it to solve it asap. Thanks to you, updating the DB

**Comment by josemp10** [comment]
Thanks Nacho. Will work on the new database  during the weekend, so it will be ready  by Monday morning. Thanks

**Comment by josemp10** [comment]
I have  updated the database in development.

**Comment by ifoche** [comment]
@josemp10 added the new database, I will now adapt the way the surveys are shown in the dashboard, to include also this new database type

**Comment by ifoche** [comment]
Finally it was already properly managed the surveys collapse. I thought it was not going to work for "n" but it looks like yes. I reassign the issue to @josemp10 and pass it to "To test" status

**Comment by josemp10** [comment]
Yes, all seem to be correct. Thanks @ifoche !
