### ISSUE TITLE
Scores are not being calculated properly on Automated Questions

### ISSUE THREAD

**Issue by josemp10** [EyeSeeTea/malariapp#197]
This was working on the 6b but since the version 7 they have a crazy bahaviour. Looking into it.

**Comment by ifoche** [comment]
I've created an issue for introducing a test for this part (issue #198). This is our engine, so we need to detect this failures on the fly, and it would be fine to have a continuous integration system (jenkins/buildbot/etc) for checking this. I think once we've got the hosting, we will be able to do it.

**Comment by ifoche** [comment]
Jose, did you make advances with this? It is important having this for tomorrow release. Should I reassign it to anyone else? It that case, could you explain it a little more what is the problem?

**Comment by josemp10** [comment]
Yes, I have a solution for this, but I didn't have the time to implement it yet. Will take me one hour. At what time  do you expect to generate the new release? In the evening I hope...

**Comment by adrianq** [comment]
@josemp10 finally do you refactor as well the code for the spinner so we have an homogeneus solution for both spinner and radiobutton?

**Comment by josemp10** [comment]
Nope. I didn't have the time today yet. Anyway,  from the quick test that I have done it seems that  the solutions that we have for RadioButtons is not going to work for spinners...

**Comment by adrianq** [comment]
Ok, then I will keep this issue opened until you have some time to test it properly and find a good solution. Otherwise, we will forget about this. @ifoche does this change have an impact on score tests (TBH I have no idea about the current status)? If not would it make sense to do the effort of implementing a test that check this corner case?

**Comment by ifoche** [comment]
Sorry @adrianq , I don't understand which case exactly are you talking about. I think you both have spoken recently about it and have a clear image of what you're talking about, but I need a little bit more context. Let me guess:
- So you're saying that maybe, as the dropdown answers and the radiobuttons ones have a common logic, they could be implemented using this common logic and just making their specific difference in the layout, is that it?
- Apart from that, you're asking that, in the case we had a score test that changed some dropdown to check score system was working, maybe now it need to be readapted to the new radiobuttons, and maybe if there is not an specific radiobutton test there should be. 
Are those your points?

**Comment by josemp10** [comment]
The bug was  because the "onChecked"  event for RadioButtons was automatically  launched  when the view is created on the adapter.  We had the same problems with  the DropDown components some months ago. In the case of a DDL we are using a boolean variable  to  determine if the view is being created at the moment (so the onItemSelectedEvent does not have to be launched ) or not (although I recognize is an ugly solution).  However this boolean variable  does not work for RadioButtons. So we found out another solution for RadioButtons, an elegant and easy one, but unfortunately, it seems that it is not going to work  for  the DDLs views.

So, we have a good solution for RadioButtons and we have an ugly solution for DropDown Lists.  So, this ticket is now abou that.

**Comment by josemp10** [comment]
Definetely will open a new issue for this
