### ISSUE TITLE
Tareas para próxima versión

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#20]
- [x] Tabs: Dropdown list para navegar
- [x] Tabs: Generar tabs manuales con valores 0.0
- [x] Bordes: Bordes de elementos, padding, espacio entre header, márgenes
- [x] Denominadores: Precargar los denominadores sin hijos
- [x] Denominadores: Contar con todos los denominadores para el cálculo
- [x] Num/dem layout: colocar el porcentaje total y junto al num/dem y cambiar color de fondo ese layout
- [x] Questions: Highlight de preguntas con hijos
- [x] Questions: Limpiado de las respuestas al cancelar la expansión
- [x] Questions: Botón de clear
- [x] Questions: Hide/show hijos en función de la selección del padre
- [x] Questions: No se están almacenando los hijos de cada pregunta
- [x] Scores: Redondear los scores a 1 o 2 decimales
- [x] Scores: Colocar el score en la tab score
- [x] Scores: Colocar el average en la tab score
- [x] Scores: Hacer el calculo del score de toda la app

**Comment by ifoche** [comment]
Parece que estamos teniendo un pequeño problema. Creo que la asociación de cada Question con sus Question hijas no se crea bien, y tanto getQuestionChildren() como getQuestion() devuelven para todas las preguntas que ninguna tiene hijo. Eso no debe ser posible.

**Comment by ifoche** [comment]
- Pregunta a resolver con Rodolfo en la próxima reunión:
La tab profile tiene un score, con su num/dem, que se calcula automáticamente, pero en la tab score no hay un hueco reservado para ese score. ¿Deberíamos meterlo?

**Comment by ifoche** [comment]
- Problemilla con el listView. Parece que cuando haces scroll hacia abajo, los elementos que van desapareciendo por arriba se borran. Habría que echarle un ojo a eso.

**Comment by josemp10** [comment]
Ok, eso es un problemón, más que un problemilla. Ayer cuando lo probe,
juraría que no se borraban. Anyway, me pongo con eso, que no es complicado
de solucionar. Hablamos.

2015-03-02 2:43 GMT+01:00 Ignacio Foche <notifications@github.com>:
