### ISSUE TITLE
Score tab is not working

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#210]

**Comment by ifoche** [comment]
This is again the "ugly general scores" bug, that we must to repair for next release

**Comment by josemp10** [comment]
I am not sure.... maybe we don't need them anymore... let's talk about it early next week

**Comment by josemp10** [comment]
I meant, maybe we don't need the general Scores tab as it is now...

**Comment by josemp10** [comment]
I can 95% confirm that  we are not going to have the General Score Tab anymore
