### ISSUE TITLE
Some tests are broken

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/malariapp#217]
After release 8 it looks like some new tests are broken and need some review:

 - [x] change_to_score
 - [x] delete_survey_by_swipping (this one belongs to DashboardDetailsActivityExpressoTest)
 - [x] global_scores_are_calculated
 - [x] in_c1_rdt_score_some_points
 - [ ] radiobutton_textsize_changes

**Comment by adrianq** [comment]
@ivanarrizabalaga I have just changed bullets for checkboxes. Just mariconware that Github provides as it uses Markdown ;) (https://help.github.com/articles/writing-on-github/) This way when a test is fixed we can just ticked the checkbox.

**Comment by ifoche** [comment]
If you execute them one by one, you'll realize that not all of them are broken. I'm not sure why this is happening. At least:
- radiobutton_textsize_changes
- delete_survey_by_swipping
Are working

**Comment by ivanarrizabalaga** [comment]
@ifoche
You're right I'll take a deeper look when I got the chance
