### ISSUE TITLE
Adding completion_date to the survey

### ISSUE THREAD

**Issue by josemp10** [EyeSeeTea/malariapp#222]
Right now, it does not exist in the database. As we agreed in the past, we need both dates: starting_date, and completion_date. The completion_date has to be automatically stored when a survey is completed. We need to send the completion_dates when pushing the values to DHIS2

**Comment by ivanarrizabalaga** [comment]
To consider:
 - Survey requires a method that checks if the survey is completed or not
 - When a survey becomes completed the 'completion_date' takes its value
 - If you remove an aswer from a completed survey both 'completion_date' and 'state' change again.

**Comment by ivanarrizabalaga** [comment]
Related to issue #224

**Comment by ivanarrizabalaga** [comment]
Related to issue #224

**Comment by ivanarrizabalaga** [comment]
@josemp10 

http://stackoverflow.com/questions/28065898/android-sugar-orm-save-crash

SugarORM does not allow null values for dates, I'm going to put a future dummy value (1/1/9999) as a false NULL.
