### ISSUE TITLE
Show sent surveys in a new table in the dashboard

### ISSUE THREAD

**Issue by josemp10** [EyeSeeTea/malariapp#228]

**Comment by josemp10** [comment]
@ifoche, this is a "nice to have" but not a priority. We are already showing the sent surveys in the  dashboard, although in the same table that the active surveys. In any case we need to allow the users to "delete", "open", ... the dashboard items without clicking two times (one to select the table, other to select the item in the table)

**Comment by ifoche** [comment]
Already shown in dashboard both tables, now a bit work in customization and refactor the code to leave it cleaner
