### ISSUE TITLE
upload CSV of the countries (Zambia, Zimbawe, Ghana...)

### ISSUE THREAD

**Issue by josemp10** [EyeSeeTea/malariapp#229]
- [x] Zambia
- [x]  Ghana
- [x] Mozambique
- [x] SF and ICM
- [x] Malawi
- [x] Tanzania

**Comment by josemp10** [comment]
[ ] - Zambia
[ ] - Ghana

**Comment by ifoche** [comment]
In the title of the issue is written Zimbawe but in the list, only Mozambique. Can you clarify this? I've checked Ghana as it is already done, isn't it?

**Comment by ifoche** [comment]
This seems to be complete, isn't it? Can we move it to "done"?
