### ISSUE TITLE
PUSH hacia DHIS

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#23]
Subir todos los datos en bloque de un formulario hacia DHIS

**Comment by ifoche** [comment]
Propuesta @josemp10 :
- Como no hay una forma directa de mapear las questions de las custom tabs a la base de datos, una solución sería hacerlo con un setTag(question) en el tiempo en que se está creando la tab, y luego ya, sabiendo que las preguntas 1-4 están asociadas, 5-8 igual, y así... pues hacer la subida de los datos a DHIS haciendo getTag() sobre los componentes que respresentan cada pregunta. Para hacerlo así, habría que crear un Header virtual, que en realidad no se representara y a este header ponerle 160 preguntas (4 preguntas/fila x 20 filas/bloque x 2 bloques de preguntas) para el caso adherence (y hacer lo mismo con IQAEQA. 
- De cara al volcado en DHIS, como en DHIS la tabla se guarda la opción como un texto, Jose propone romper la relación entre las tablas Value y Option, y guardar el texto de la opción.

DHIS tiene las tablas así (véase que el campo value es un conjunto de caracteres)
CREATE TABLE datavalue
(
  dataelementid integer NOT NULL,
  periodid integer NOT NULL,
  sourceid integer NOT NULL,
  categoryoptioncomboid integer NOT NULL,
  value character varying(255),
  storedby character varying(100),
  lastupdated timestamp without time zone,
  comment character varying(360),
  followup boolean,
  attributeoptioncomboid integer NOT NULL,
  created timestamp without time zone,
  CONSTRAINT datavalue_pkey PRIMARY KEY (dataelementid, periodid, sourceid, categoryoptioncomboid, attributeoptioncomboid),
  CONSTRAINT fk_datavalue_attributeoptioncomboid FOREIGN KEY (attributeoptioncomboid)
      REFERENCES categoryoptioncombo (categoryoptioncomboid) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_datavalue_categoryoptioncomboid FOREIGN KEY (categoryoptioncomboid)
      REFERENCES categoryoptioncombo (categoryoptioncomboid) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_datavalue_dataelementid FOREIGN KEY (dataelementid)
      REFERENCES dataelement (dataelementid) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_datavalue_organisationunitid FOREIGN KEY (sourceid)
      REFERENCES organisationunit (organisationunitid) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT fk_datavalue_periodid FOREIGN KEY (periodid)
      REFERENCES period (periodid) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)

Propuesta @ifoche :
- Mientras @josemp10 hablaba, se me ha ocurrido otra posible solución para el problema de las customs, que sería hacer que cada fila de 4 preguntas fuera un header, utilizando su identificador como id del paciente. Habría que darle alguna vuelta más pero me parece que eso quedaría un poco menos chapuza. No obstante, por supuesto la mejor opción es siempre el rediseño de las tablas. Por falta de tiempo Jose plantea que no es muy viable para la próxima entrega.

**Comment by ifoche** [comment]
Propuesta que finalmente se implementará:
- Las preguntas estarán agrupadas por una pregunta padre fantasma, que no se representará pero servirá para hacer la unión de las preguntas hijas que conforman una fila. Las preguntas estarán agrupadas en headers. El nombre del header coincidirá con el id del TableLayout en el que se van a mostrar. De esta forma, al rellenar un Custom Layout, se extrae un header, se busca el TableLayout asociado, y luego se buscan las preguntas padre. Iterando sobre las preguntas padre se van situando las celdas de cada fila (representada por una pregunta padre).

**Comment by ifoche** [comment]
El botón de Save debe sustituirse por uno Submit. En todo momento debe hacerse un guardado en local sin preguntar al usuario, para que al cerrar y abrir quede siempre ahí. Rodolfo ha preguntado para saber si debe además poder guardarse varios formularios. Si la respuesta es que sí, deberíamos, al pulsar en submit, desplegar una opción para elegir qué formulario se desea submitir de los guardados en local. Si la respuesta es que no, al pulsar en submit se hará PUSH a la DB de DHIS. Cuando se hace un Submit, se asume que después se hace un Clear.

**Comment by adrianq** [comment]
See also #27

**Comment by adrianq** [comment]
@josemp10 will talk to Rodolfo about how to deal with org unit/period/data elements and some other issues

**Comment by josemp10** [comment]
3 prerequisites  need to be addressed before working on this issue:

1) We need to save the metadata in our local database
2) We need to save data in our local database
3) James needs to implement a program in DHIS2 (a program is a data entry based on events. Maybe a bit difficult to explain here, will show you how it works when it is done)

**Comment by ifoche** [comment]
See also #27

**Comment by josemp10** [comment]
Tentative, this has to be done the first week of July. PSI has to send to us the UIDs of the DataElements first...

**Comment by josemp10** [comment]
I have just  learnt that  the next release is on the 5th of July, so rry...

**Comment by ifoche** [comment]
Yes, we have the milestone "Release 8" set for the 3rd of July, I think that was the concrete date that Rodolfo said yesterday. Probably that will be the date we're going to meet.

**Comment by ifoche** [comment]
I've just seen the updates from Rodolfo in the shared document. Effectively, he set Sunday 5 as the due date for release 8, but he put an intermediate due date for June 10 that I'm asking for moving it to June 12. That wouldn't be the 2 weeks sprint, but at least would be one week. I'll move the Release 8 due date for June 12 and create a new Release 9 milestone for the 5 July. Push and Pull (as much as possible) goes for the Release 9

**Comment by adrianq** [comment]
Subtask discussed yesterday:
   - [ ] Upload xml example
   - [ ] Store uid/code for programs in DB
   - [ ] Store uid/code for OU in DB
   - [ ] Store uid/code for CompositiveScores
   - [ ] Polish Scores Table
   - [ ] Push Answers
   - [ ] Push Compositive/Scores

@josemp10 Please add/remove/keep update as the design phase goes on...

**Comment by ivanarrizabalaga** [comment]
@josemp10 With current implementation in 'Jose-is-pushin' there is still a problem related to SSL certificates.

Whenever you try to do the request you get a **java.security.cert.CertPathValidatorException: Trust anchor for certification path not found**.

There are several paths to follow:
- Check dhis-event-capture to see if it works for **'https://malariacare.psy.org**
- Read this carefully (https://developer.android.com/training/articles/security-ssl.html)

**Comment by josemp10** [comment]
Thanks @ivanarrizabalaga for your great work with this task!

**Comment by ifoche** [comment]
@josemp10 , @ivanarrizabalaga . Just a question. Is this something that must go to "Testing" first? I imagine that, after all the hard work, seeing the task as "Done" is psychologically encouraging, but maybe there are some tests that must be done before moving it to "Done"? (just asking, I haven't seen the code yet)

**Comment by josemp10** [comment]
Well... I have no idea how we should implement a test for this task. I
mean, the test is to check that the answers are in the DHIS2 server...
there is no way to check in the android if those answers have been already
sent or not with their value, for that, you need to go to the DHIS2 server.

**Comment by ifoche** [comment]
No...I imagine checking that the answers are in the server is quite difficult. I was thinking in things like:
- The answers are properly being translated into json
- If the server is not present, the error is managed
- etc

could we put the task as "in progress" and if those tests are not done when release is over, create a task for doing them? do you think those tests are just not needed? I don't know how is the code so only you guys can say if there are pieces of code that can be separately tested.

**Comment by adrianq** [comment]
Yes, it it not about testing the whole functionality. It is about having unit test and also we can think about having some dummy data in a server (local or remote) and check if we can push the information. Another test can have a wrong uid and check it fails when pushing. I think it is a super important feature and it should be covered by test

**Comment by josemp10** [comment]
Anyway, i don´t think it is going to be useful...

- if the server is not present we are going to see an error message (we had
so many yesterday).
- the answers are properly being translated into json -> the json is
well-formed, otherwise the import wouldn't work. Well, maybe we can check
that all the answers are contained in the json (but I don't think we need a
test for this)
- Wrong UIDs.... If the DHIS2 UIDs are not the same that in the android
app, the import is not going to work.
- Dummy data.... There is no dummy data. The data that we send to the DHIS2
server is just text (it does not matter if it is an option, text, date). I
mean there is no way to send 'wrong' data to DHIS2.

We can discuss this more later today, but I can not see a value for this
task :)
