### ISSUE TITLE
Create a new table to render the answers

### ISSUE THREAD

**Issue by josemp10** [EyeSeeTea/malariapp#235]
Drop Down List? Radio Buttons Vertical? Radio Buttons Horizontal?

**Comment by ifoche** [comment]
I don't understand this issue, can anyone explain it to me?

**Comment by ifoche** [comment]
anyone out there? If I get no answer in a week, I'll close this issue. I'll use this break week in the project development to clean up all the issues that has been accumulating all this time, and may have no sense anymore

**Comment by ifoche** [comment]
Hi @ivanarrizabalaga, this is just to remember you that after this task we may update the DB lucid chart. Thank you in advance

**Comment by ivanarrizabalaga** [comment]
Oki @ifoche
