### ISSUE TITLE
% of completion is not properly working

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#243]

**Comment by ifoche** [comment]
If you fill, for example, an ICM survey, the completion percentage shown is not 100%

**Comment by ivanarrizabalaga** [comment]
Already solved in Jose is pushing branch

**Comment by ifoche** [comment]
ok, thanks. @josemp10 is your branch ready to PR? If not, can you cherry-pick that commit(s) to development to let me test what happens when a survey is finished?
