### ISSUE TITLE
Create a system for selecting the locale-dependent data

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#254]

**Comment by josemp10** [comment]
Let's comment this option to Rodolfo on Wednesday...

**Comment by josemp10** [comment]
I don't want to take the risk of a user trying to install this app without
internet (Yes, I know it is difficult, but don't know if impossible). Lets
wait till Wednesday, till we have a clear answer from Rodolfo and Graham.

**Comment by ifoche** [comment]
Yes. What I suggest here would be something like, in login activity, put a dropdown list to decide the country you're logging in. After checking your credentials, the app would go to a common URL adding a "/country" and there it would search for the csv files. Simple but effective. This way, we wouldn't need to upload the csv for each country, and data would be out from the repo

**Comment by ifoche** [comment]
country would then become a preference for the app, and it could even be changed by the user, if we want

**Comment by ifoche** [comment]
As we now have CSVs in other languages, but not in all languages, it is now important to include a way to, at least, avoid user using the app if the language selected is not the good one. The best would be to have a system to download the appropriate data
