### ISSUE TITLE
Refactor PushClient to remove hardcoded data

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#256]

**Comment by ifoche** [comment]
several strings are hardcoded, and there we should centralize them in the strings file, and there are some variables like the user, or pass we're using to push to DHIS server that are being hardcoded. We need to link them to preferences or user defined variables.

**Comment by ifoche** [comment]
Server has been already placed into a variable. Still user:pass is hardcoded

**Comment by adrianq** [comment]
Done by @ifoche
