### ISSUE TITLE
composite scores are not properly pushed

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#259]

**Comment by ifoche** [comment]
Although composite scores are properly shown in the app, when we push them, at the server, we see them all with a score of 100%, no mather which score they had in the app

**Comment by josemp10** [comment]
I have changed yesterday a litle bit the code. We had a ListAllByProgram,
so I have changed it to ListAll (Although we need to re-write the
ListAllByProgram method, ListAll is nice when we have only one program), so
now we don't get  100% score for all of them, But still we are not getting
the correct values when we push them...

**Comment by ifoche** [comment]
@ivanarrizabalaga . The task @josemp10 is talking about is #251
