### ISSUE TITLE
too much time spent loading in dashboard

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#263]

**Comment by ivanarrizabalaga** [comment]
The completion rate is calculated for both lists (unsent, sent) which might be quite slow.

With the last commit this rate is only calculated for unsent surveys.

**Comment by josemp10** [comment]
Ivan, I am reopening ths issue. As long as the user is answering questions, it takes years to load the dashboard (and I am only testing it with one survey). May you have a look? It seems that there is a relation between the loading time and the number of questions answered in a survey.

**Comment by ivanarrizabalaga** [comment]
Yes it is related to the %ratio of completion that it is calculated for
each survey.

I'm going to stay away for a while, maybe I got the chance to take a look
at night.

**Comment by ivanarrizabalaga** [comment]
@EyeSeeTea/developers

I've introduced a cache for ratios, optimized a query (which was buggy by the way) and a couple of minor changes and now goes twice faster.

Please check it out to confirm it is ok now.
