### ISSUE TITLE
Create push tests

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#267]

**Comment by adrianq** [comment]
Work [in progress in Picture app](https://github.com/EyeSeeTea/pictureapp/issues/28)

**Comment by ifoche** [comment]
This task is waiting for SDK implementation. As the SDK doesn't retrieve the push result, we cannot test anything. The implementation of that part in the SDK is apparently going to be done by its developers, so whenever it is done, we'll do the tests. Very related to issue #608

**Comment by ifoche** [comment]
@adrianq we're going to update this in malariapp. If I'm not bad, I imagine that these tests were prepared for the old push style, but  they aren't adapted to SDK nor the new ImportedSummary capabilities of the SDK, isn't it? If there's something we must know before starting this task that may not be in the issue you referenced, please could you tell us? However, we will inform you about the progress of this issue, as I think picture app probably may want it too.

**Comment by ivanarrizabalaga** [comment]
It seems like multidex apps require some special config:

http://developer.android.com/intl/es/tools/building/multidex.html

**Comment by ivanarrizabalaga** [comment]
@idelcano I finally manage to run tests again, I've pushed my current configuration to branch **push_test**

Minimal test sample in PushTest, I'm working from that starting point

**Comment by ivanarrizabalaga** [comment]
@idelcano It looks like there is still something wrong, dont use this branch yet

**Comment by ifoche** [comment]
@ivanarrizabalaga @idelcano you have the user "test" with pass (I send it through hangout) with the minimum permissions, test facility 1 as orgUnit, only Family Planning as Program, and even without permission to access via web. It is configured in hnqis-dev-staging

**Comment by ifoche** [comment]
BTW, the user is also in hnqis-dev-ci now

**Comment by ivanarrizabalaga** [comment]
Not ready yet, I'm still working in an effective way to wait for alertdialog in progressactivity ( espresso waits for asyntasks by default but doesnt wait for our pullcontroller callback code so I have to implement an idlingresource, arggg).

I will work on this tonight...

**Comment by ivanarrizabalaga** [comment]
Initial tests for login and push done in *push_test* branch.

I'm not moving the issue into done because I need a real (but limited) user with permission to pull/push from server  or read this from a local.properties file I dont know yet.

**Comment by ifoche** [comment]
ok, @ivanarrizabalaga . I've created a user testOK and a user testFAIL. The user testFAIL has the same kind of permissions that you had until today (he can view the metadata and download it but no permission with the data). The testOK is able to download the data also. Both work just with family planning program. I'll send you and @idelcano the passwords directly by chat.

PS: It's done just in hnqis-dev-staging server, but I'll do it in hnqis-dev-ci soon

**Comment by ivanarrizabalaga** [comment]
@ifoche I've modified the tests and it looks like they are working now.
