### ISSUE TITLE
Question Parent-Child logic extremely slow

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#270]

**Comment by ifoche** [comment]
In real devices it takes too much time to view the children when you activate a parent

**Comment by josemp10** [comment]
I think I have an answer for this one. It can be related to hide/show
headers when the user clicks on a parent question with the yes value. Will
testing tomorrow

**Comment by josemp10** [comment]
In Spanish, sorry!

Clase: AutoTabAdapter
Método: updateQuestionsVisibility -> Tenemos 2 bucles anidados.

Prueba a comentar la siguiente
linea: hidden[items.indexOf(child.getHeader())] =
isHeaderHide(child.getHeader());

isHeaderHide puede recorrer todas las questions de una header (warning: En
estas surveys hay headers que tienen muchísimas questions)

**Comment by ifoche** [comment]
Yes, commenting out that piece of code results in an improvement of the time spent to open the children. Now I'm profiling the method to guess which exactly is the improvement. Commenting out that line, do you know what effect would produce in our app? I mean, why was that code for? I'll try to guess myself, but as there's no comments is a little hard and maybe you can clarify this quicker

**Comment by josemp10** [comment]
It is still slow. We need:

1) Re-code that piece again trying to reduce the response time
or
2) Display a progress bar while the "thing" is working.

**Comment by ifoche** [comment]
@ivanarrizabalaga, did you check whether new DBFlow lazy behavior has modified this issue? is it now running faster?

**Comment by ifoche** [comment]
solved in #959
