### ISSUE TITLE
some questions layouts are wrong

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#273]

**Comment by ifoche** [comment]
- In Reading of Films, all question with "Thin Swear" should use vertical layout instead of horizontal one
- In tabs CCM, Observation 1, 2, 3, the question about Sex should be in vertical layout

**Comment by josemp10** [comment]
?? I have the last version of the Excel spreedsheet that Graham sent to
me... and I think all those questions are correct. Sex in Observation 1, 2,
3, is displaying horizontal and "This Swear" is displaying horizontal. They
are correct. Some answers could have different representations in different
tabs. Sex is being displayed horizontal in some tabs and vertical in other
tabs. I think, it is better if we wait for the Graham's feedback

**Comment by ifoche** [comment]
Graham has written to say that those layout must change. So I keep the bug opened

**Comment by josemp10** [comment]
The changes have been introduced in the new database
