### ISSUE TITLE
app scroll is very slow

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#281]

**Comment by ifoche** [comment]
I've removed the checkboxes images loading and the app performance has significantly improved. So maybe we would need to find the way to reuse that image loading, or keep the default checkbox image. I'm going to try it on my phone to see if this may be also the cause for other bugs

**Comment by josemp10** [comment]
I think we would need to use the convertView in the getView method of the
adapter. Please have a look at
http://www.vogella.com/tutorials/AndroidListView/article.html#adapterperformance

The most important bottleneck in the performance is the rendering of the
views in the screen. The parameter convertView gives us a view that we can
reuse (and not rendering again). It may be a bit tricky to code, as we need
to ask, is the convertview a DDL, a date, a SHORT_TEXT...?. But I think we
need to try it.

**Comment by ifoche** [comment]
Yes, the use of convertView is something we've widely spoken about... We didn't implement it yet due to that difficulty for reusing in case the views are not of the same type. But I think I have an idea about how to do it. Let's give it a try

**Comment by ivanarrizabalaga** [comment]
Checking this: 
 - http://sparetimedev.blogspot.com.es/2012/10/recycling-of-views-with-heterogeneous.html
 - http://android.amberfog.com/?p=296

**Comment by ifoche** [comment]
Hi @ivanarrizabalaga . This is buggy. I've checked it out and:
- 1 . If you write something, go down and then up again, you'll see all the Textfields showing the same text.
- 2 . It looks like the convertView is taken without looking whether or not the view type is the same as the older one. 

I'm now to tired, so maybe I didn't explained myself very well. But checking in a real device it's not working so for the moment I won't mix it with the hotfix branch. Can you give a look to this asap?

Thank you.

**Comment by ifoche** [comment]
We'll save this here to give it a try for Release 10

**Comment by adrianq** [comment]
@ifoche I am closing this old task. Scroll is much much better now . There are some minor improvements that can be done regarding the match questions but they have been written down [in this card](https://github.com/EyeSeeTea/malariapp/issues/1145).
