### ISSUE TITLE
Progress bar while loading tabs

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/malariapp#282]

**Comment by ivanarrizabalaga** [comment]
@EyeSeeTea/developers
First attempt in branch 'loading_tabs'

It is not prepared for the old Survey with the 'generalScore' tab.

**Comment by ifoche** [comment]
Sorry @ivanarriazabalaga . Is this prepared to be integrated into hotfixes_to_release_9? If so, could you make a PR? I supose which is the branch, but I think it's better if you confirm that with a PR. This way we're sure you're not working in the branch anymore and want to see the changes in hotfixes_to_release_9, and at the same time, you can give a look to the changes alltogether

**Comment by ivanarrizabalaga** [comment]
@ifoche ok, I think is ready for merge I'm going to pull and check latest changes in hotfixes and then create the PR (tonight hopefully)
