### ISSUE TITLE
Latency when entering numeric values

### ISSUE THREAD

**Issue by josemp10** [EyeSeeTea/malariapp#287]
This only happens in the AutoTabAdapter, so it is probably due to the use of EditTextCard View (the custom tabs have still the android EditText fields). I tried to remove the filters but it didn't make any difference. It is very strange as this is only happening in the integer.xml layout, not when the dataentry field is text.

**Comment by ifoche** [comment]
Solved by using the same .xml file for integer.xml than for shorttext.xml
