### ISSUE TITLE
Latency when selection an option in DDLs

### ISSUE THREAD

**Issue by josemp10** [EyeSeeTea/malariapp#288]
This is only happening in AutoTabAdapter (not in the custom tabs). When the user selects an option, it takes 2 seconds to put the selected option in the DDL field.

**Comment by ivanarrizabalaga** [comment]
It works fine in an emulator, I'm going to try with a physical device.

**Comment by ifoche** [comment]
Apparently it is related to the number of times we call initializeSubscore() in AutoTabAdapter. If we go to initializeScoreViews() and comment out the last line, we'll see a huge improvement in the performance. I think we're calling initializeSubscore() constantly and we should do it just at the very beginning

**Comment by josemp10** [comment]
Great!! So, as the custom tabs do not have subscore section (I removed them
in the last version, as we don't need them anymore) we didn't see those
problems in the custom tabs performance.

I tested it and DDLs are responding good, each tab loading time has been
decreased signitfically, and the timing for hide/show logic has been
reduced half way (still a bit lag, but I think for the users is ok). I
still don't understand why the initializeSubscore is being called so much,
but we are almost there!!

**Comment by ifoche** [comment]
A new refactor of the toggle visibility has completely removed the latency. Now checkbox and ddls runs incredibly quick
