### ISSUE TITLE
% of completion is not real

### ISSUE THREAD

**Issue by josemp10** [EyeSeeTea/malariapp#289]
I tried with the Zambia survey, and I got 100% when I still had 4 empty tabs. I am sure there was a problem counting this in the Custom Tabs, but also I think there is a problem in the algorithim. Unfortunately this is going to be quite difficult to test (or long time consuming) in a survey with more than 1400 questions...

This is a high priority issue, but I think there are others more urgent than this one... maybe we should wait to have the datasets of ofher countries with a more comprehensive survey (like Ghana)...

**Comment by ivanarrizabalaga** [comment]
@josemp10 this one should be done

**Comment by ifoche** [comment]
@ivanarrizabalaga I've just checked it and it seems it's not yet solved. I remember you already talked us about this bug. The behaviour is, when a parent question is answered no and you exit and re-enter, children are shown. I suppose this is somehow linked to the wrong calculation. I'll check it out to find a solution

**Comment by ifoche** [comment]
I've made the test of answering everything, even all children question and completion percentage is not the good one. My initial guess is that it has something to do with the "label" questions. Maybe for doing the percentage it is taking into account. However, it could have something to do with #234 too

**Comment by ivanarrizabalaga** [comment]
@EyeSeeTea/developers

I've met this in 'pictureapp' and since the DB is really small in that case I think I've found the problem:

    private SurveyAnsweredRatio reloadSurveyAnsweredRatio(){

        int numRequired= Question.countRequiredByProgram(this.getProgram());
        int numOptional=0;
        int numAnswered = Value.countBySurvey(this);

        for (Value value : this.getValuesFromParentQuestions()) {
            if (value.isAYes()) {
                //There might be children no answer questions that should be skipped
                for(Question childQuestion:value.getQuestion().getQuestionChildren()){
                    numOptional+=(childQuestion.getAnswer().getOutput()==Constants.NO_ANSWER)?0:1;
                }
            }

        }
        SurveyAnsweredRatio surveyAnsweredRatio=new SurveyAnsweredRatio(numRequired+numOptional, numAnswered);
        SurveyAnsweredRatioCache.put(this.id, surveyAnsweredRatio);
        return surveyAnsweredRatio;
    }

-------------------------------------------

    public static int countBySurvey(Survey survey){
        if(survey==null || survey.getId()==null){
            return 0;
        }
        String[] whereArgs={survey.getId().toString()};
        return (int)Value.count(Value.class,"survey=?",whereArgs);
    }

The number of answered questions was not ok.

**Comment by ifoche** [comment]
checking it on malariapp

**Comment by ifoche** [comment]
After testing it, it looks like we're changing to "Prepared to send" state when we're almost at 100% . But that bug will be treated in a different issue (#309)
