### ISSUE TITLE
Tab change latency

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#293]

**Comment by ivanarrizabalaga** [comment]
@EyeSeeTea/developers

After checking our UI issues following this tutorial (http://developer.android.com/tools/debugging/debugging-ui.html) is clear to me that there are too many components in view ("thanks for the info" I know, I know).

The point is that most of the inner layouts(the ones corresponding to each type of questions) have some views that probably could be remove (intermediate RelativeLayouts and so).

I'm going to give this a try and check if I'm right or not.

**Comment by ifoche** [comment]
Yes, as you've probably already imagined, that excess of auxiliar views is there for representation purposes. I mean, probably a refactor now that all the app has grown a lot is good and needed, and we surely can reduce that amount of views, but please take into account at each change that a view can be there to:
- use his padding/margin/etc to change the way their children are shown
- be the target of a "findViewById()" search in order to modify something
- etc
so please check it twice and paying attention to everything, just to be sure another thing is not suffering after a LinearLayout removal, or a RelativeLayout...and so on

**Comment by ivanarrizabalaga** [comment]
@EyeSeeTea/developers

So crucial info de process to turn a tab into a list of headers and questions takes almost a whole 1sec. right now.

*Utils.convertTabToArray 840ms*

We should try to do this with 2 querys (1 headers, 1 questions) and then mix them properly, I'm goind to give it a try later.

**Comment by ivanarrizabalaga** [comment]
@EyeSeeTea/developers

I have tested some minor improvements but havent found the right optimization yet. In general:

*ChangeTab = Some preparation (30ms) + build Adapter (700ms) + 20 getViews(250ms)* 

Some additional info:

 - Turning N queries (1 x header) into 1 bigger query to get questions -> **NO effect**
 - Removing updateReadOnly -> No effect
 - Preloading headers & questions in surveyService -> Even worse
 - 20 getViews take (depending on the types of elements): 250ms 
     - header/no_answer: 5ms 
     - text/int: 7/10ms
     - dropdown: 25ms
     - checkbox (no children): 30 ms
     - checkbox (children): 35/50/80 ms (depending on the number&type of children) 
 - Any time you answer 'Yes' to a parent question the **whole screen is recreated** (20 getViews) this is #270 
 - **Scrolling** is just the sum of 20 getViews (aprox), #281

Still running testing different things...

**Comment by ivanarrizabalaga** [comment]
I'm pretty sure that there is a 1+N problem (http://stackoverflow.com/questions/97197/what-is-the-n1-selects-issue), loading all the questions from a tab takes only 2ms in SQLiteDataBrowser but takes up to 700ms in our code.

I think that (SugarORM) for each Question loads its related objects (Header, Answer, Question and CompositeScore) so you end up making hundreds of querys.

**Comment by ivanarrizabalaga** [comment]
@EyeSeeTea/developers 

Bad news I guess, I have just confirmed that SugarORM doesnt use lazy loading, when we select the questions from a tab behind the curtains there are 2199 small querys to complete each field of each question and their relationships.

To sum it up this means that we cannot improve those 700/850 ms from the method Utils.convertTabToArray easily.

If you want to check it you must (http://stackoverflow.com/questions/5966584/logging-sql-queries-in-android):
 - adb shell stop
 - adb shell setprop log.tag.SQLiteStatements VERBOSE
 - adb shell start

**Comment by ifoche** [comment]
Ok @ivanarrizabalaga . Thank you for the great analyze job. I think this will have to wait for the next refactor, that apparently could be something like moving from Sugar to DBFlow.
