### ISSUE TITLE
When % of completion is near 100, survey is set to "prepared to send". This must only happen when it is exactly 100

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#309]

**Comment by ivanarrizabalaga** [comment]
This code looks ok:

```java
    public boolean isCompleted(){
        if(total<=0){
            return false;
        }

        return answered>=total;
    }
```

really think it is something related to #447

**Comment by ifoche** [comment]
so you checked removing one answer to a complete survey make its completion percentage in dashboard appear as "ready to upload" isn't it?

**Comment by ivanarrizabalaga** [comment]
Yes I have checked it, the problem is the function that calculates the number of required questions.

Example:

1 - Every question is filled: required **61** | answered 64
2 - Everything but 1 question: required 61 | answered **63**
