### ISSUE TITLE
Refactor Parent-Child relation into new relation db schema

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/malariapp#346]

**Comment by ivanarrizabalaga** [comment]
Queries required for navigation:

/*Get parent question*/
select q.*
from question q 
left join questionoption qo on q.id_question=qo.id_question
left join match m on qo.id_match=m.id_match
left join questionrelation qr on m.id_question_relation=qr.id_question_relation
where qr.id_question=228 and qr.operation=1;

/*Get parent question + option*/
select qo.id_question,qo.id_option
from questionoption qo
left join match m on qo.id_match=m.id_match
left join questionrelation qr on m.id_question_relation=qr.id_question_relation
where qr.id_question=228 and qr.operation=1;

/*Get children for question + option*/
select q.*
from question q left join questionrelation qr on q.id_question=qr.id_question
left join match m on qr.id_question_relation=m.id_question_relation
left join questionoption qo on m.id_match=qo.id_match
where qo.id_question=227 and qo.id_option=130 and qr.operation=1;

**Comment by ivanarrizabalaga** [comment]
Enable dynamically output for sql queries in DBFlow:

com.raizlabs.android.dbflow.config.FlowLog.setMinimumLoggingLevel(FlowLog.Level.V);

**Comment by ivanarrizabalaga** [comment]
Counting the current number of optional questions that should be answered according the values of the parent questions:

select q.*
from question as q 
left join questionrelation as qr on q.id_question=qr.id_question
left join answer as a on q.id_answer=a.id_answer
left join match as m on qr.id_question_relation=m.id_question_relation
left join questionoption as qo on m.id_match=qo.id_match
left join value as v on qo.id_question=v.id_question and qo.id_option=v.id_option
left join option as o on v.id_option=o.id_option
where a.output<>7 and v.id_survey=1 and qr.operation=1
