### ISSUE TITLE
Polish Match Feature

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/malariapp#349]
- [x] Disabled Spinner

**Comment by ivanarrizabalaga** [comment]
Disable the last spinner (the one that it is calculated)

**Comment by ifoche** [comment]
In the code you can see it in [line](https://github.com/EyeSeeTea/malariapp/blob/development/app/src/main/java/org/eyeseetea/malariacare/layout/adapters/survey/AutoTabAdapter.java#L230-L232). There you'll find all the tries we've done to solve it

**Comment by ivanarrizabalaga** [comment]
I move the second task from this card to its own issue #452 since both issues are not really related

**Comment by ifoche** [comment]
The solution for disabling the spinner has become maximum priority. They want it ASAP, so can you please put it first? Thank you @ivanarrizabalaga

**Comment by ivanarrizabalaga** [comment]
It is already in the PR from yesterday.

**Comment by ifoche** [comment]
oops, sorry, waffle was not updated when I wrote you my last comment. I see it as closed now...I think waffle is having some problems because now I can see duplicated all comments...what a strange thing... Anyway. Thank you for the work
