### ISSUE TITLE
If tab has gone to sleep, when a survey is deleted dashboard doesn't refresh

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#364]

**Comment by adrianq** [comment]
@ivanarrizabalaga I have just realised this is happening in Picture App. Therefore once you fix this in Malaria App, can you please move (as a new branch) the bit of code that solves the problem into Picture App?

From now on, let's try to keep this in mind for any bug or error.

**Comment by ivanarrizabalaga** [comment]
Sure! I have already solved it so there will be a PR today  :D

**Comment by adrianq** [comment]
Great! Many thanks! :)

Btw, I am already available with a good internet connection just in case you would like to discuss anything

**Comment by adrianq** [comment]
@ivanarrizabalaga You haven't created a PR for this, right? Once you have created a PR for this, can you do the same in PictureApp and close [this card](https://waffle.io/EyeSeeTea/pictureapp/cards/55c29d9701922114006d2ea4)?
