### ISSUE TITLE
Ghana variant crash when creating survey

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#378]

**Comment by ifoche** [comment]
The failures comes from OrgUnits.csv. This is not updated to the new DB format

**Comment by ifoche** [comment]
Apparently Ghana variant may disappear. We're not yet sure. In the meanwhile, this country has disappear from R10 release notes and downloadable apks, although we're keeping it in the code

**Comment by adrianq** [comment]
This issue has to do with the db. @josemp10 will update the csv and hopefully this will fix the bug. @josemp10 I am assigning it to you, please close it  once you update the csv and check this is not happening anymore
