### ISSUE TITLE
Repair tab items cache for composite scores tab

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#382]

**Comment by ifoche** [comment]
When fixing the bug described in #357 @josemp10 noticed that cache was not properly working on composite score tabs. He disabled it in this case. We need to reactivate it, but being sure it works and doesn't introduce any new bug

**Comment by ivanarrizabalaga** [comment]
Back to backlog since EDS is not prepared for R11.

If you try to launch any eds variant (ghana for instance) it crashes before dashboard (during population).

**Comment by ifoche** [comment]
Composites score tab is no longer needed in the app, si this becomes invalid
