### ISSUE TITLE
Start assessment: App crashes in validation

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/malariapp#384]
Using **edsMalawi** (edsGhana creation is broken so far).

If I try to create a survey without fulfilling any of the data the validation crashes the app.

**Comment by ifoche** [comment]
I've seen this behaviour before in other variants when the OrgUnits have not been properly populated, have you already checked it? (it may be a problem in the DB and not in the validation).

**Comment by ivanarrizabalaga** [comment]
#379
