### ISSUE TITLE
Modify push to update events datavalues

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#407]

**Comment by ifoche** [comment]
Its needed to do some API calls to retrieve the data needed to update old events with the new values. See specifications for more information

**Comment by ifoche** [comment]
Depends on #420 . Basically, if we cannot avoid push squashing the rest of the surveys, we have to comment out that code, and PSI will do that work in a cron job in the server

**Comment by josemp10** [comment]
We cancel this task. Likely is going to be a cron job in the server yes. Sorry @adrianq for the time you have consumed on this task

**Comment by adrianq** [comment]
Well, a weekend coding is always a funny weekend :/ @ifoche Can you remove that PR for the code or do you want me to do it?

**Comment by ifoche** [comment]
I move this to done as, although finally we've taken another approach, the work is done
