### ISSUE TITLE
Dashboard not refreshing

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#412]

**Comment by ifoche** [comment]
After sending a survey, it doesn't go automatically to sent section. This is a recursive problem I thought we had already solved. I hope this is the last time we solved it.

**Comment by ifoche** [comment]
I've notice that now the dashboard doesn't wait for the push result to refresh. Maybe the problem could be that. If it refreshes itself before having the push result, it probably hasn't tagged yet the survey as sent

**Comment by ifoche** [comment]
After the meeting, this task has taken the highest priority. It's mandatory to solve this

**Comment by ifoche** [comment]
Whenever we find a solution, we have to patch R10 too.

**Comment by ivanarrizabalaga** [comment]
@ifoche i think now it is solved.

Adding a middle activity (LoginActivity) while doing the push broke the expected flow in the DashboardActivity.

I think the code would be easier with a dialog for credentials instead of trying to reuse the former LoginActivity.

**Comment by ifoche** [comment]
We've already commented this in person. It's strange because on R10 (which already had the LoginActivity inside) we didn't have this bug, but however, I agree with you that probably a dialog would be better to avoid exiting the Activity. We will think about it for next code management, and of course, we need client confirmation for such a change.

**Comment by ifoche** [comment]
I reopen it to give a try to R10 bug and see if this solution is easily portable to R10 by cherry picking the commit

**Comment by ifoche** [comment]
done by cherry-picking to a branch called v1.0 that starts from v1.0 tag, the commit 852d2318ee4b641eb265f91029ef0269fb9ebdb7 from v1.1 release
