### ISSUE TITLE
Introduce images in feedback content

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#418]
we need to check if this is working already for valid local and remote URLs

**Comment by ifoche** [comment]
They're accesible but not interpreted by the parser. We need to represent, locally stored, the images that currently are stored in [this folder](https://drive.google.com/folderview?id=0Bx05i_ZJuoZVOWdDVHdfTldaQm8&usp=drive_web)

**Comment by ivanarrizabalaga** [comment]
Since I turn the TextView into a full WebView any html tag is working after issue #422.
Gonna try to find the right local path to local assets.

**Comment by ifoche** [comment]
Sounds great!

**Comment by ivanarrizabalaga** [comment]
Done, I'm going to do a PR in a minute.

This change will affect performance of feedback. Turning a lightweight component like a TextView into a heavyweight component such as WebView means a lot.

I have tried it in a physical device and it works pretty fine but it is a bit slowlier now.
