### ISSUE TITLE
HTML parser is not interpreting everything

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#422]

**Comment by ifoche** [comment]
Feedback is being fed by HTML tagged text. In general, everything is being formatted properly but some things are not being properly read:
- [ ] Bullet lists (<ul><li/></ul>) are not being read
- [ ] Images appear as a blue square. We have to guess if this is because it is not reaching the URL, but however, we need to render images (even if we are force to download them and have them in local)

**Comment by ifoche** [comment]
[this](http://stackoverflow.com/questions/11214001/show-ul-li-in-android-textview) explains that our parser is not reading ul-li tags. We need to change the parser to allow it

**Comment by ifoche** [comment]
[here](http://stackoverflow.com/questions/7424512/android-html-imagegetter-as-asynctask) you'll find another interesting link

**Comment by ivanarrizabalaga** [comment]
A pseudo approach:

 - Rename URLImageParser into CustomParser
 - Implements Html.ImageGetter and  TagHandler

In the method:

**public void handleTag(boolean opening, String tag,
                                 Editable output, XMLReader xmlReader);**

check for the tags "ul", "li" and follow a sample to turn it into the proper string.

Check this link http://stackoverflow.com/questions/11214001/show-ul-li-in-android-textview

**Comment by ifoche** [comment]
done by using [Kutsi code](https://bitbucket.org/Kuitsi/android-textview-html-list)
