### ISSUE TITLE
Remove some text boxes when questions could be found below

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/malariapp#43]
block out the text boxes in the following sections (these are questions with the options right below them so no text box necessary) - water supply, power supply, out patient drug stock out, microscope/rdt stockout and minor lab equipment.

We are still waiting for Martin/Rodolfo in order to know how to solve it...

**Comment by ifoche** [comment]
Now we have a new type of question (label) that has no answer attached. This solves the issue
