### ISSUE TITLE
Clean countRequiredByProgram() code

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#447]

**Comment by ifoche** [comment]
The function countRequiredByProgram(TabGroup tabGroup) get the number of questions that doesn't have a parent. With the changes in the DB this had stop working, but now is fixed. The problem is, due to DBFlow bug related to the join between tables that have common column names, to me it was impossible to get that in a simple DB query, so finally I got it using 2 different queries (1 for obtaining all the questions related to that Program and another one to get which questions are children) and so getting the parents for that program comes from substracting the 2nd query to the 1st one. Would it be possible to make it in a cleaner way?

**Comment by ifoche** [comment]
Please find [here](https://github.com/EyeSeeTea/malariapp/blob/development/app/src/main/java/org/eyeseetea/malariacare/database/model/Question.java#L488-544) the concerning code lines

**Comment by ifoche** [comment]
As this logic is used for #309, please give a look to that too in order to solve it.

**Comment by ivanarrizabalaga** [comment]
```sql
//Todas las 'respondibles' del tabgroup
select count(*)
from 
	question q 
	left join answer a on q.id_answer=a.id_answer
	left join header h on q.id_header = h.id_header
	left join tab t on h.id_tab = t.id_tab
where 
	a.output<>	7 and
	t.id_tab_group=1
	
//Hijas
select count(*)
from
	questionrelation qr 
	left join question q on qr.id_question = q.id_question
	left join answer a on q.id_answer=a.id_answer
	left join header h on q.id_header = h.id_header
	left join tab t on h.id_tab = t.id_tab	
where 
	qr.operation=1 and
	a.output<>	7 and
	t.id_tab_group=1
```

**Comment by ivanarrizabalaga** [comment]
I have tried to join these 2 querys into one but it cant be done since there are questions with both types of relationships (being a children question + match result question).
