### ISSUE TITLE
Represent number of sent assessment by month

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#457]

**Comment by ifoche** [comment]
As we're not yet pulling data from server, this obviously will result in a delta curve for the current month, and would only work if the user holds using the app without upgrading it more than a month, but however, these are the specifications for this release. Apart from that, we need to show a threshold , that in the future will be calculated or extrated from somewhere, but for the moment we will fix it in 30 (but keep that variable easily changeable).

**Comment by ifoche** [comment]
![linechart](https://cloud.githubusercontent.com/assets/10931645/10166284/9880490a-66c3-11e5-87b0-5728bb81deaf.png)

**Comment by ivanarrizabalaga** [comment]
https://jsfiddle.net/do691wz4/6/

**Comment by ifoche** [comment]
@ivanarrizabalaga. I'm so sorry. Yesterday we were talking about using d3 as the js library for the charts (as we're more experienced with that and we have to take advantage of that). You can see [here](https://github.com/mitchwongho/D3Android) a project where somebody has already done this before. Is it painless to move to d3 now?

**Comment by ivanarrizabalaga** [comment]
@ifoche Yesterday a completed a mocked chart with Chart.js BUT if d3 is the
way to go for more projects (since it is far more powerful) it could be the
right time to change (the sooner the better).
Anyway I will surely talk to you this afternoon since there is a problem
with the dashboard (fragment + scrollview dont get on well) that we
probably need to solve to complete the whole monitor stuff.


[image: http://]
Ivan Arrizabalaga
[image: http://]about.me/ivan-arrizabalaga
<http://about.me/ivan-arrizabalaga>

**Comment by ifoche** [comment]
ok, perfect. Sorry for changing the library and not thinking on d3 before. But as you said, d3 is more powerful and we're using it in some other projects. My fault.

**Comment by ifoche** [comment]
Just to leave a trace. We finally decided to use chart.js again, because d3 needed too much coding for just a little chart.

**Comment by ifoche** [comment]
I've reopened the issue because it's not working at the moment, but also because we need to do a little last hour change. Apparently, now we need to show only the last 6 months (not 12 as we were showing before)

**Comment by ivanarrizabalaga** [comment]
One question, I was creating the chart from the sent surveys without
considering that most of times there's going to be just a few months (maybe
even just one).

After reading your last comment I dont know if you'd rather have a chart
always with 6 points (0,0,0,0,2,7 for instance).

Is that right (it is very easy no problem at all)?

**Comment by ifoche** [comment]
That's it. I think the best would be to show only the surveys sent in the last 6 months

**Comment by ivanarrizabalaga** [comment]
Sorry Nacho, I dont know if have understood you:

A)Every chart is made of a series of 6 points no matter what (if no survey
has been sent 6 zeros)

B)If I got data from the last 3 months the chart is made of 3 points, if I
got a whole year only the last 6 points are shown

Sorry again, I'm a little bit 'espeso' ;)

**Comment by ifoche** [comment]
Yes, I think you've understood. To represent 6 months you need to put 6 points in the linear chart. If there aren't sent surveys for any month, then a 0 would be represented. So every time you would be representing 6 points, and this 6 points would be the amount of sent surveys for this month, last month, 2 months ago, 3 months ago, 4 months ago and 5 months ago. Then you will have to group the sent surveys by date, order them by month, cut all the data older than 6 months and count them (something like that. Of course it is always better if you can have that in a query, but I don't know if that query will be easy build with the ORM known bugs)

**Comment by ivanarrizabalaga** [comment]
Oki doki :)

**Comment by ivanarrizabalaga** [comment]
@ifoche  It is working ok for me. I dont know what is happening, :(

I've tried: 
 - nexus 5 api 17&22 (emulator)
 - nexus9 api 22 (emulator)
 - samsumg s5 (device)

always with the same results.

Now I have added the 6 months issue too.

**Comment by ifoche** [comment]
@ivanarrizabalaga I have to seriously apologize. I'm so sorry. It was completely my fault. I thought that a chart with no sent surveys would show up as an empty chart with its axis and 0 values, but apparently, it even didn't show the axis at all. That confused me and drove me to think that it wasn't working at all. So now I would correct myself. It was working when a sent survey was present, but, when it wasn't, it was not working. I've seen that you've corrected that in your last commit, so thank you for that, now everything's fine. I put it as done.
