### ISSUE TITLE
Represent number of surveys belonging to scoring classes by program in several  pie charts (one per program)

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#459]

**Comment by ifoche** [comment]
![piechart2](https://cloud.githubusercontent.com/assets/10931645/10166313/b978b278-66c3-11e5-92e6-41f149a36141.png)
![piechart1](https://cloud.githubusercontent.com/assets/10931645/10166314/bc2a2e84-66c3-11e5-849b-b495767a9e8e.png)

**Comment by ivanarrizabalaga** [comment]
http://jsfiddle.net/wcgtu72q/

**Comment by ifoche** [comment]
![device-2015-10-11-022912](https://cloud.githubusercontent.com/assets/10931645/10413989/038134d0-6fc0-11e5-940e-65dcc707b423.png)

As you can see in the screenshot, line chart is there, and there is space enough for seeing pie charts too even without scrolling, but they're not there. Shouldn't they?

Thank you again

**Comment by ifoche** [comment]
![device-2015-10-11-023407](https://cloud.githubusercontent.com/assets/10931645/10414019/94010f4e-6fc0-11e5-9cb8-9a601bc79efb.png)

This is just to let you see that, in this case, it is not related to the same issue as before. Even with sent surveys, pie charts are not apparently there

**Comment by ivanarrizabalaga** [comment]
I dont know, android version? Device or emulator? I need to reproduce it.

If I find some time I will try to call you so we can check it together.

You can also try try the 'chrome://inspect' trick to debug the javascript
code and see whats happening.

**Comment by ifoche** [comment]
![device-2015-10-11-112327](https://cloud.githubusercontent.com/assets/10931645/10416171/11106468-700b-11e5-86c9-60747e4acf0b.png)

Android 4.4.2 (API 19) kernel 3.4.5-3952694. It is a real device (Samsung model SM-T210). 
But it happens also in a 4.2.2 (API 17) with kernel 3.4.67-qemu+ (Virtual device)
And it happens also in a 4.3 (API 18) with kernel 3.4.67-qemu+ (Virtual device)
And it happens also in a 5.0.2 (API 21) with kernel 3.4.67+ (Virtual device) (screenshot comes from this device)

It's strange that you cannot reproduce it, I can't find any device where this works. Are you sure we're looking at the same branch (development) and bug (pie charts not showing)?
