### ISSUE TITLE
Push overall score

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#461]

**Comment by ifoche** [comment]
Apparently there is not any special logic that could avoid pushing this overall score, but server is not receiving it

**Comment by ivanarrizabalaga** [comment]
josemp10, ifoche 
the root score is not ok in the csvs, the scores **1, 2 and 3** are not associated to score **0**.

I'm going to take a look at **populatedb** code but probably should be fix from data instead.

**Comment by ivanarrizabalaga** [comment]
Parent scores **must** be added before children scores so they can find their parent in the intermediate Hashmap

**Comment by josemp10** [comment]
Ok, got it. And solve it in the next 15 minutes!

**Comment by ifoche** [comment]
thank you @ivanarrizabalaga, @josemp10, can you give a look to this? @josemp10 I created a branch from master called hotfix_score_data_bug, can you upload solution to this in that branch and make a PR to master whenever it is finished? Thank you in advance

**Comment by josemp10** [comment]
Ok, I have pushed the new comp. scores.csv versions to the
hotfix_score_data_bug
brach. I didn't make the PR cause I didn''t test it yet (I can do that in
about one hour), although I am pretty sure that Ivan is right.

**Comment by ifoche** [comment]
perfect I'll take care of every PR later at 21h or 22h today, so there's time. Thank you very much

**Comment by josemp10** [comment]
Tested it! @ivanarrizabalaga's suggestion did the trick. However, now the
overall comp.score is being showed as well in the feedback (top of the rest
of comp. scores). We have 2 options:

1) Keeping the overall comp. score at the top of the comp. scores (and
removing it from the header). Although in this case we need to add a new
color for the new level (we have 3 levels with this approach)

or

2) Keeping the overall comp. score at the header as it is now (and removing
it from the top of the comp. scores)

PSI prefers the option 1), but they are ok with both!

Making the PR anyway...

**Comment by ifoche** [comment]
Ok, it's my turn then. I'll implement a simple logic (if the composite score parent is null do not represent it). That way, they'll get what they had. Let's leave them decide after they see everything working what to do next. Thank you both guys for your work

**Comment by ifoche** [comment]
Done by [removing cs parent from feedback list](https://github.com/EyeSeeTea/malariapp/blob/master/app/src/main/java/org/eyeseetea/malariacare/database/feedback/FeedbackBuilder.java#L62-68) in representation part
