### ISSUE TITLE
change push return json parsing to allow also 2.20 version

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#462]

**Comment by ifoche** [comment]
When push is finished, on 2.20 version of DHIS the field in the answered json that contains the number of questions updated and so on has slightly changed. So now we need to read the DHIS version to distinguish when it is a 2.19 from a 2.20 and read the response depending on it

**Comment by ifoche** [comment]
@josemp10 will confirm that in json response there is a DHIS version and which are the names for those fields

**Comment by ivanarrizabalaga** [comment]
The response after pushing is now (under dhis 2.20) completely different:

```json
{
    "httpStatus": "OK",
    "httpStatusCode": 200,
    "status": "OK",
    "message": "Import was successful.",
    "response": {
        "responseType": "ImportSummaries",
        "imported": 75,
        "updated": 0,
        "ignored": 0,
        "importSummaries": [
            {
                "responseType": "ImportSummary",
                "status": "SUCCESS",
                "importCount": {
                    "imported": 75,
                    "updated": 0,
                    "ignored": 0,
                    "deleted": 0
                },
                "reference": "JdTt8wWPiua",
                "href": "https://hnqis.psi-mis.org/api/events/JdTt8wWPiua"
            }
        ]
    }
}
```

**Comment by ifoche** [comment]
Can you easily identify which response come from which version?

**Comment by josemp10** [comment]
@ifoche, I think it may be other API call to know the DHIS2 version (I
would need to have a look).

Thanks @ivanarrizabalaga

**Comment by ivanarrizabalaga** [comment]
@josemp10 dont worry about it, the code supports both versions now (last PR)
