### ISSUE TITLE
ScrollView in Dashboard with Monitor

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/malariapp#479]
So far I'm going to create the logic that shows the charts inside the Dashboard **BUT**  in order to make it right we will have to deal with all the issues related to the lack of **scrollview** in the activity.

I've made a quick attempt  to solve this but it is not easy since it looks like we are relying on fragments which dont get on well with scrollviews.

**Comment by ivanarrizabalaga** [comment]
http://stackoverflow.com/questions/18367522/android-list-view-inside-a-scroll-view
http://stackoverflow.com/questions/5308247/what-does-androidisscrollcontainer-do

**Comment by ifoche** [comment]
Depends on #457 and #459

**Comment by ifoche** [comment]
One alternative comes from introducing a unique listview and make different rowTypes, as explained [here](http://kyogs.blogspot.in/2014/06/the-use-of-getviewtypecount-and.html) and [here](http://stackoverflow.com/questions/4777272/android-listview-with-different-layout-for-each-row/4777306#4777306)

**Comment by ifoche** [comment]
Another alternative (and something very interesting to think about) is the case of ExpandableListView. These kind of ListViews allow to have 2 different lists that may be collapsed and expanded dynamically. Sounds great to substitute Feedback and Survey content representation, and even dashboard content. More info [here](http://developer.android.com/reference/android/widget/ExpandableListView.html)

**Comment by ifoche** [comment]
The alternative that would respect more our current architecture would be [this one](https://pristalovpavel.wordpress.com/2014/12/26/doing-it-right-vertical-scrollview-with-viewpager-and-listview/), that is a variant of [this](http://stackoverflow.com/questions/6210895/listview-inside-scrollview-is-not-scrolling-on-android/17503823#17503823)
