### ISSUE TITLE
Integrate SDK login

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#482]

**Comment by ifoche** [comment]
Login must be reintroduced in the beginning of the app, and replaced by the SDK one. A very obsolete branch with this work is present, that may be helpful, but we need to be sure that it deserves the effort to rescue that branch instead of redoing the work keeping an eye on it.

**Comment by adrianq** [comment]
@ifoche this is finally working although I guess a little bit of polish will be needed. I am closing this card. Let's create a new one that defines what needs to be polish in login activity.
