### ISSUE TITLE
After first survey upload, charts are shown far away, very scrolled down

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#489]

**Comment by ifoche** [comment]
Hi @ivanarrizabalaga, can you update the state of this issue? Where are we?

**Comment by ifoche** [comment]
@ivanarrizabalaga has made a redesign for the dashboard, not yet completed but apparently with a clean and better performance. @adrianq and I will think a little about the orientation of the redesign and will get back to this later. Please @ivanarrizabalaga, write here the name of the branch where you've left the code, so we can take it into account. Thank you in advance.

**Comment by ivanarrizabalaga** [comment]
@ifoche

The branch is **scroll_dashboard**

What is left to be done?

 - Swipe to delete (i've upload some snippets but **this is not ready**)
 - Check height of elements in horizontal mode (should be easy)

What classes/files could be removed?

 - DashboardActivity
 - DashboardSentFragment
 - DashboardUnsentFragment
 - IDashboardAdapter
 - ADashboardAdapter
 - AAssessmentAdapter
 - AAssessmentUnsentAdapter
 - AAssessmentSentAdapter
 - fragment_dashboard
 - assessment_sent_header
 - assessment_sent_record
 - assessment_sent_footer
 - assessment_header
 - assessment_record
 - assessment_footer

**Comment by ifoche** [comment]
Thanks!!

**Comment by ivanarrizabalaga** [comment]
@ifoche I've just added a very basic swipe to delete (no visual effect onfling but it works) this morning.

A visual swiping effect + review layout in portrait and it would completed 100%.

**Comment by ivanarrizabalaga** [comment]
@ifoche, just an update.

I've realized that there was a weird horizontal padding at values-820dp and the layout looks good in portrait and landscape.

**Comment by ifoche** [comment]
Finally solved with a new approach (measuring things after webview load). I'll tell you more tomorrow. It was easier than we thought :)
