### ISSUE TITLE
Grandpa refactor

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/malariapp#49]

**Comment by ifoche** [comment]
We can reuse this big refactor card to point to the mega-refactor that jose just told us we need to do as the app is going to grow a lot. 

In that refactor I think we'll need to re-structure the tabs as we know them at this moment, and turn them into separate activities that are controlled by the upper drowdown menu (releasing it from its static-tabs chains). I mean, at this moment when somebody clicks on the menu, it simulates a tab-change event and so the reality is that we have a tabbed layout that is loaded at the begining and we just move between preloaded tabs. We need to use activities to load tabs. Using activities will take us to a different problem. Now as we have everything pre-loaded, we can get things between tabs (put a value in the score tab, for example) and from the moment we separate everything in activities on, we won't have this possibility anymore. That's the reason why I think we need to change those fields' access for local DB access. So a prerrequisite to this refactor would be implement the local DB saving.

**Comment by adrianq** [comment]
Duplicate
