### ISSUE TITLE
Implement metadata/data pull through SDK and exchange layer

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#493]

**Comment by ifoche** [comment]
See 
- [ ] #497 
- [ ] #498
- [ ] #499
- [ ] #500

**Comment by ifoche** [comment]
@ivanarrizabalaga, @idelcano, Oslo developers have encourage us to move to the 2.20 branch in the sdk. Can you please make a "git checkout 2.20 & git pull" on sdk subfolder?
In the next months we will probably move to 2.21, and then we will need to implement an update system, but for the moment we're going to consider that as the stable branch.

In addition, I've seen that DB is slightly different in 2.20 branch (compared to master branch). I recommend you to update the branch and then execute a pull, and using "adb pull", download the SDK DB in order to check it and analyse the differences.

**Comment by ifoche** [comment]
@ivanarrizabalaga, @idelcano, I've shared a document with you. This is a document that must be opened using [draw.io web app](https://www.draw.io/) It's a diagram with the tables involved in the exchange process. I think I've put the tables/columns needed but, as you're the ones doing the translate, nobody but you to check it and correct the possible mistakes. @josemp10 will draw the lines between the fields, so we can have a proper translation diagram that could guide us in the future without needing to look at the code. If you can help @josemp10 drawing the first lines, the goal is to keep it updated as with the lucid chart DB diagram.

Thank you very much to everyone for your work!

**Comment by ifoche** [comment]
@josemp10 we're having a problem with Questions composition. The problem is that, as Questions are being translated like this...
if (I am a CS) --> translateIntoCS()
else --> translateIntoQuestion()
...if there are other things in the DB that are not questions, like the control dataElements, or any other testing questions that probably shouldn't be there in the server, we're translating them into the app.

This way, when we try to run the application we get multiple crashes, as several foreign keys cannot be found. 

So there are 2 main ways to solve this:
1st approach --> We take out from the server everything that is not a valid question, and in the case of control dataElements we put an attribute on them to be able to filter them
2nd approach --> We put an attribute that let us filter the questions from the trash

I would prefer the 2nd one, as with the 1st one, we need to be really sure that no one introduces a question badly linked to its tab/program/etc in the server. Otherwise all the apps getting their data from that server would crash immediately. But you can tell us whether there is any constraint to do that. Anyway, both approaches need a change in the server data, so we need to decide and modify it.

Can we see it together in a hangouts soon? We're stuck in this to get the pull fully working, so if we can do it soon, we would really appreciate it.

Thank you in advance

**Comment by josemp10** [comment]
Ok, sorry I maybe forgot to mention about control datalement, my bad

We have 3 types of dataelements: Question, Comp. Scores, and Control
DataElements.

The way we have to identify control datalements is with the Question_Type
attribute. The value will be CONTROL_DATAELEMENT  (although it is not yet
implemented in the server). If it is an urgent matter, I will create the
value for the attribute tonight.

I dont know about other testing questions... can you give me the code of
them?

Are this answering (partially) your question? I can chat (hangout) tomorrow
afternoon

**Comment by josemp10** [comment]
ok, they were only 6 or 7 dataelements, so the server has already been
updated. So, you need to check the Question Type attribute of the
DataElement, if the value is "CONTROL_DATAELEMENT" means that is a control
data element :)

About other "testing", "wrong" questions... they shouldn't be on the
system. Have you found some?

**Comment by ifoche** [comment]
Yes, I give you one example. DE with uid "b3ppvtq6Kzc" which form_name is "POST-TEST" and is downloaded as several of them without being able to link to any header/tab/program... I've looked for it in all the Questions.csv and I didn't find it, and as long as I can see in our translated DB it doesn't have a header, like other around 600 questions that are in the same case. 

So from your answer I understand that you're going to create that "CONTROL_DATAELEMENT" attribute. That's good, thank you very much, we need it as soon as possible, as it's blocking us. And would you be able to create another one for the questions? Is that possible? That would simplify a lot the differentiation and would make the system much more robust (anyone who want to add a question to the app would need to tell the server, "yes, this is a question that must appear in the app". That way we would be able to not translate those 600 dataElements not linked to any header

@idelcano, can you add that "CONTROL_DATAELEMENT" filtering to the code? I'll create a task for that

**Comment by idelcano** [comment]
@ifoche of course! i will do now.

**Comment by josemp10** [comment]
I am answering between lines...

On Tue, Nov 17, 2015 at 2:27 PM, Ignacio Foche <notifications@github.com>
wrote:

> Yes, I give you one example. DE with uid "b3ppvtq6Kzc" which form_name is
> "POST-TEST" and is downloaded as several of them without being able to link
> to any header/tab/program... I've looked for it in all the Questions.csv
> and I didn't find it, and as long as I can see in our translated DB it
> doesn't have a header, like other around 600 questions that are in the same
> case.
>

It may be a question from a very old program (old release). Can you let me
know the program (uid) that the question belongs to? Anyway, why this
question is crashing the app? It contains Header (HIV Testing and
Counseling), Question Type (NO_ANSWER (Label)), Question order (220),
Composite Score (1.1). Maybe is it because of tab?

Other 600 questions?? mmmm... Do they belong to an old program?

> So from your answer I understand that you're going to create that
> "CONTROL_DATAELEMENT" attribute. That's good, thank you very much, we need
> it as soon as possible, as it's blocking us.
>
Well, I have created the option "CONTROL_DATAELEMENT" for the attribute
Question_Type. Yes, it should be enough. Let me know if there are problems
with that.


> And would you be able to create another one for the questions? Is that
> possible? That would simplify a lot the differentiation and would make the
> system much more robust (anyone who want to add a question to the app would
> need to tell the server, "yes, this is a question that must appear in the
> app". That way we would be able to not translate those 600 dataElements not
> linked to any header
>
Adding an attribute like this is a bit tricky now, but if a question has
the attribute question_type, it must have a header too (unless the
dataelement is a Comp. Score or a Control Data Element). Can you give me 2
or 3 examples with questions without header attribute? (and their program).
It is pretty strange because these questions are being generated
automatically using an script...

**Comment by ifoche** [comment]
@josemp10, sorry change in my last mail "create a new attribute" by "create a new  option for control dataElement". Can you, with that change, re-read my message and tell me if that is possible?

**Comment by josemp10** [comment]
Yes, it is already done since this morning.

I have added the "CONTROL_DATAELEMENT" option to the Question_Type
attribute. Let me know if it is not clear.

**Comment by ifoche** [comment]
And what about having an option QUESTION for control dataElement? would that be possible?

**Comment by josemp10** [comment]
Sorry, I dont understand what you mean by "having an option QUESTION for
control dataElement"...:)

I mean control data elements are just the same case that comp. scores in
terms of how you can distinguish between comp. scores and questions... (you
need to check the value of the question_type attribute, and if the value is
'COMPOSITE_SCORE', you know that is a comp. score. Here is the same case..)

I dont know if I am understanding you sorry.

**Comment by ifoche** [comment]
hi @josemp10, I see, you're looking at the messages in your phone. If you look at the issue, you'll see that I edited the comment, changing control dataElement by question dataElement

**Comment by ifoche** [comment]
While you answer that, 
the example question that I told you (that with form_name "POST-TEST". You asked me for its program. It is the one with UID rKjg29O3RFu.

**Comment by ifoche** [comment]
The question is crashing the app because it has no header/tab/etc associated and when the system is looking for it, it crash. Maybe there are old questions, or bad questions, or I don't know, but if you don't want us be responsible of having the server filled with only valid dataElements for our app hierarchy and be responsible of a global crash in case someone creates an invalid question, I suggest you to create a different questionType called "QUESTION" or whatever that may give us the possibility of distinguish the real questions of the app from the rubbish that may be in the server. 

It's obvious that I'm not explaining myself very well. Let me try this way:
We don't want the questions to be distinguish as an "else" condition. So we don't want the questions to be those dataElements that aren't CS nor control dataElements. Instead of that, we want to have a way to mark them as questions. 

Please let me know if it remains unclear

**Comment by josemp10** [comment]
Ok, I see what the problem is (I think). There is no stage section for
those programs (so you can not get the tab). As these programs only have
one tab, James or Graham may forget to add the sections here. Will try to
solve this in the following 30 minutes and let you know. It is not a matter
or rubbish, but configuration of the programs. In other words the Data
elements are ok, but the programs configuration, not.

**Comment by ifoche** [comment]
@josemp10. Will you please create that option or give us the access enough in the server to create it? Solving the problem to that question in particular doesn't solve the future problem if somebody add a question that we don't want to be uploaded to the app or things like that.

**Comment by josemp10** [comment]
@ifoche... it is not a question (DataElement) related problem. It is just a
program configuration problem (that affects to ALL questions inside that
program). I think I have solved it now. Can you check? Thanks

Creating a new question_type to separate "valid" from "invalid"
questions... I can not do that sorry. Please check if it works now.

**Comment by ifoche** [comment]
@josemp10 you are talking about this particular case. I am talking about the app architecture. It is much better if we have 3 different tags to separate the questions from the composite scores and control dataElements rather than relying the classification of questions in an "else" condition. Ok, I'll check it now, and sorry, I thought you had the permissions to do it. Don't worry, I'll ask directly Rodolfo who may have those permissions, explaining him the problem. I'll tell you in a few minutes the result of checking your last modification in the server

**Comment by idelcano** [comment]
@josemp10 

At this moment, the Questions without idheader are 30. the DB looks so different.
I think it was control Dataelementcontrol and maybe some compositeScores not filtered.

But application crash in a buildscore() method from compositescore, i take a look.


Null header questions at this moment:
de_name:
"_Forward Order"
"_Last Survey?"
"_Overall Class"
"_Overall Class A"
"_Overall Class B"
"_Overall Class C"
"_Overall Score"
"_Reverse Order"
"HNQIS-ICM-RDT-RDT-100-Is this a real or simulated observation?"
"HNQIS-ICM-I&PE-RDT-300-Assembles new test packet, swab, buffer, pipette, lancet and gloves"
"HNQIS-ICM-I&PE-RDT-310-Puts a new pair of gloves"
"HNQIS-ICM-I&PE-RDT-320-(i) Checks expiry date on package (ii) checks dessicant satchet is dry (iii) Write's patient's name or ID on cassette (iv) Places cassett"
"HNQIS-ICM-I&PE-RDT-330-Cleans finger with antiseptic/ alcohol"
"HNQIS-ICM-I&PE-RDT-340-Allows finger to dry before pricking it"
"HNQIS-ICM-I&PE-RDT-350-Use a sterile lancet for finger pricking"
"HNQIS-ICM-I&PE-RDT-360-Puncture the side of the ball of the finger"
"HNQIS-ICM-I&PE-RDT-370-Provider disposes of lancent in sharps bin immediately after pricking finger"
"HNQIS-ICM-I&PE-RDT-380-Collect blood with the enclosed pipette making sure to fill close to the first cross line"
"HNQIS-ICM-I&PE-RDT-390-Using a pipette, blots blood onto the pad in the correct well"
"HNQIS-ICM-I&PE-RDT-400-Disposes of the used pipette in the sharps container immediately after use"
"HNQIS-ICM-I&PE-RDT-410-Dispense correct number of drops of the buffer into the correct well"
"HNQIS-ICM-I&PE-RDT-420-Wait correct time before reading results"
"HNQIS-ICM-I&PE-RDT-430-Read the test results correctly"
"HNQIS-ICM-I&PE-RDT-440-Record results in the register"
"HNQIS-ICM-I&PE-RDT-450-Dispose gloves, wrappers, alcohol swab and dessicant safely"
"HNQIS-ICM-I&PE-RDT-460-Should RDT have been undertaken based on symptoms?"
"HNQIS-ICM-D,T&C-Diag3-360-END OF TAB"
"HNQIS-ICM-I&PE-RDT-490-END OF TAB"
"HNQIS-ICM-Work Env-Doc & Rept-290-END OF TAB"
"HNQIS-SF-1-C.Scores-CC-500-Cervical Cancer-Cryotherapy"

uid
"FEkGksxhOpH"
"iW2zVNwfDK6"
"ggrkfoq6nxA"
"TgCWRlUXbca"
"zckZqXOQRHT"
"DBUwlPCO0Hd"
"Y8Nmpp7RhXw"
"deeu8rjsqvH"
"PD9HoCTL6Ys"
"IJebXactxMg"
"eCPVti0KQtG"
"PZBDgiokcy5"
"iAKFd68uxJ2"
"ckbv6XI6MkH"
"TdnnCfPjvtG"
"i2zxoS0DryK"
"Yh8vdkFpFp6"
"Nw0FlpudQSx"
"ZrV0L9IyAdO"
"EbC9h6WYDOI"
"b3qdNHErmhv"
"jV7UOCiFVOq"
"TOL9I9EPzYH"
"EGEB9ZwANRu"
"fIDsIhGrlvf"
"cUOQpnHePfa"
"uyO7HXUowzy"
"illWFSrbZN2"
"LZBLBEPQ7eW"
"wu4yiGgpld4"

**Comment by josemp10** [comment]
Almost there @ideano !. Can you try again?

**Comment by ifoche** [comment]
@josemp10 now I think only these are failing

"1","_FWR-sort","_Forward Order","_Forward Order",,"FEkGksxhOpH",,,,,,,,
"2",,"_Overall Class C","_Overall Class C",,"DBUwlPCO0Hd",,,,,,,,
"3","_RWD-sort","_Reverse Order","_Reverse Order",,"deeu8rjsqvH",,,,,,,,
"4","_Overall Score","_Overall Score","_Overall Score",,"Y8Nmpp7RhXw",,,,,,,,
"5",,"_Overall Class B","_Overall Class B",,"zckZqXOQRHT",,,,,,,,
"6",,"_Overall Class A","_Overall Class A",,"TgCWRlUXbca",,,,,,,,
"7","_Overall Class","_Overall Class","_Overall Class",,"ggrkfoq6nxA",,,,,,"12",,
"8","_Last?","_Last Survey?","_Last Survey?",,"iW2zVNwfDK6",,,,,,,,

Those are the control dataElements, so I think there are no more problems @idelcano, can you confirm?

**Comment by idelcano** [comment]
Upss, i anwser in another cart sorry.

@josemp10 Yes! I have only Y8Nmpp7RhXw ggrkfoq6nxA deeu8rjsqvH as questions without header

**Comment by josemp10** [comment]
Qué infierno!!

So how many do we have?

"1","_FWR-sort","_Forward Order","_Forward Order",,"FEkGksxhOpH",,,,,,,,
"2",,"_Overall Class C","_Overall Class C",,"DBUwlPCO0Hd",,,,,,,,
"3","_RWD-sort","_Reverse Order","_Reverse Order",,"deeu8rjsqvH",,,,,,,,
"4","_Overall Score","_Overall Score","_Overall
Score",,"Y8Nmpp7RhXw",,,,,,,,
"5",,"_Overall Class B","_Overall Class B",,"zckZqXOQRHT",,,,,,,,
"6",,"_Overall Class A","_Overall Class A",,"TgCWRlUXbca",,,,,,,,
"7","_Overall Class","_Overall Class","_Overall Class",,"ggrkfoq6nxA",,,,,,"
12",,
"8","_Last?","_Last Survey?","_Last Survey?",,"iW2zVNwfDK6",,,,,,,,

PLUS

Y8Nmpp7RhXw ggrkfoq6nxA deeu8rjsqvH

??????

Can you give me their program?

**Comment by idelcano** [comment]
"3422"	"_Overall Class"	"_Overall Class"	"_Overall Class"	"NULL"	"ggrkfoq6nxA"
"3423"	"_Overall Score"	"_Overall Score"	"_Overall Score"	"NULL"	"Y8Nmpp7RhXw"
"3424"	"_RWD-sort"	"_Reverse Order"	"_Reverse Order"	"NULL"	"deeu8rjsqvH"
I´m not sure where look their program

**Comment by ifoche** [comment]
When I checked the DB there were all those I told you, but @idelcano has in his branch the change that also separates questions from control dataElement, so maybe the problem is that, those @idelcano has told you are not properly tagged as control DataElements ??? I'm going to check it

**Comment by idelcano** [comment]
No no no, only   Y8Nmpp7RhXw ggrkfoq6nxA deeu8rjsqvH

**Comment by josemp10** [comment]
Ok, I am going program by program  (10 minutes...)

**Comment by josemp10** [comment]
Can you try again? (cross fingers)

**Comment by idelcano** [comment]
No :(  Y8Nmpp7RhXw ggrkfoq6nxA deeu8rjsqvH continue in questions.

**Comment by josemp10** [comment]
@idelcano , I think that this time is going to work! :). Can you try again?
Let me know!

**Comment by idelcano** [comment]
@josemp10  yes!, it work now

**Comment by ifoche** [comment]
@josemp10, now the apps failing because we cannot take the hierarchical code of CS with UID XgjACuQSvun (that dataElement is being recongnized as a CS) . Can you give a look to this?

**Comment by ifoche** [comment]
To give you more info about this DE. 
It has 3 attributes:
DEQuestType: 93
Order: 100
DETabName: Composite Scores

It looks like it were a Tab (maybe the tab Composite Scores?) Does it looks like a CS recognition problem or is it a data problem?

**Comment by josemp10** [comment]
The DE is a comp. score. I need to check the reason of an empty value
there, but I have next 4 hours of meetings, sorry... so in the meantime I
have edited that attribute with the value '0', hope it is not failing now.
Will check when I come back

**Comment by ifoche** [comment]
Thanks @josemp10, that solved the issue. Now we can continue

**Comment by ifoche** [comment]
@josemp10 we're experimenting some errors we hadn't yesterday and @idelcano has realized that the server side changed (some extra questions apparently). Is that possible? Is the server in a steady stage? can you tell us whenever it's done? because maybe we're looking for a bug in the data that is not going to be a bug

**Comment by ifoche** [comment]
@josemp10 apart from that, is it possible that [root CS](https://hnqis.psi-mis.org/api/dataElements/XgjACuQSvun) doesn't contain the attribute to determine the CS code? Could it be repaired in server side? Thank you!

**Comment by josemp10** [comment]
Sorry for the slow response guys,

I have added the code to that C. Score (anyway, I think root comp. scores
are not longer needed, as we already have the control dataelement for that
porpuse right?) Need to think about it.

About some changes in the server.... yes, it is possible, but I didn't have
any news about it... Do you know the program which these dataelements were
created in?
