### ISSUE TITLE
OrgUnits pull

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#497]

**Comment by ifoche** [comment]
Org Units:. El SDK retornará automáticamente todas las unidades que tiene asociado cada usuario con los programas. Las org. units serán siempre health facilities, por tanto no habrá en nuestra base de datos información de país, districts, chiefdoms,... Esto quiere decir que no habrá una lista de DropDown Lists para elegir la org. unit (al contrario que EDS, que se descargará todo el árbol), si no un único campo donde el usuario vaya a introducir directamente la org. unit. Este único campo puede ser como el de picture app (R3), donde el usuario introduce texto libre y la app devuelve las coincidencias...

**Comment by idelcano** [comment]
@josemp10  

1.  Do you know where is the uid field of the org_unit in DHIS?
And other question:
In EyeSeeTeaDB the org_unit_level is a foreign key, points to org_unit_level  table with two fields, id, and name.
2. Do you know where is the name field for the org_units_level in DHIS?

Thanks

**Comment by idelcano** [comment]
@josemp10
Sorry, i think the uid is the id.

Anyway i dont know where is the name field in OrgUnitLevel table

**Comment by josemp10** [comment]
@idelcano , the SDK does not retrieve the hierarchy of the org. units that the user has access to, but a simple list of org. units (it does not matter which level they are). In other words, the OrgUnitLevel table only will have 1 row (1 level), so you can keep a generic "Org. Unit" or "Facility" org. unit level name.

Let me know if it is not clear

**Comment by idelcano** [comment]
@josemp10 
Sorry, I was trying to map the entire tables.
I understood now , but i have a related question to be totally safe:


Does the parent id is not needed? it is a recursive FK. I think is not needed.

When i pull all the org units, some org units have uid parents not pulled, and show as null. But if we only need a simple list of org units i think this field is not needed.

**Comment by ifoche** [comment]
@idelcano, yes, as you can see, the SDK is not able for the moment to download the orgUnit hierarchy, so in the future we would have to find a solution to that. For the moment, you don't need to remove that field from the database. Keep the field there so we will be able to do it whenever the SDK is able to retrieve a complex orgUnit hierarchy. Just leave for the moment that field to null.
