### ISSUE TITLE
Answer + options pull

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#498]

**Comment by ifoche** [comment]
Answers and Options: Copio aquí la llamada a la API para HNQIS server. Conviene que entendamos el formato de salida. Aunque sea json, el SDK nos devolverá en clases de Java, la misma estructura.

https://hnqis.psi-mis.org/api/optionSets.json?fields=id,name,options[name,code]&paging=no

Si buscamos 'Yes1No', vemos la siguiente estructura:

{

    id: "cN5N9aj3S30",
    name: "Yes1No0",
    options: 
    [
        {
            name: "Yes",
            code: "Yes [1]"
        },
        {
            name: "No",
            code: "No [0]"
        }
    ]

}


Donde name es el nombre de la Answer 'Yes1No0', y options un array con las opciones de la answer. Las options tienen 2 campos, name y code. Ambos tienen que ir a nuestra tabla Option (campos 'name' y 'code' respectivos). El valor del name es lo que el usuario ve de respuesta, y el valor de code, lo que realmente se pushea. Importante entender que en el code va también el factor de la option que tendremos que extraer para ponerlo en nuestro campo 'factor' (desgraciadamente no tenemos otra opción aquí). También importante, habrá options codes que no tengan factor, en este caso tendremos que suponer 0.

**Comment by ivanarrizabalaga** [comment]
@ifoche cool!

@josemp10 There is only 1 field left to be able to convert from sdk to answers and options and it is the **answer.output**.

Any idea?

**Comment by josemp10** [comment]
@ivanarrizabalaga, the answer.output  is a Data Element attribute in DHIS2,
so we need to implement the attributes first in SDK before pulling the
output in our database.

**Comment by ivanarrizabalaga** [comment]
thanks @josemp10, I'm going to add a //TODO tag to the right spot and recover this once we are ready for attributes.
