### ISSUE TITLE
Question, Header, Match, QuestionRelation, QuestionOption pull

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#500]

**Comment by ifoche** [comment]
Toda esta información se saca de los DataElements y de los attribute DataElements (por implementar en el SDK).

Llamada a la API (un buen tocho, nos devuelve todos los DE del programa ICM)

https://hnqis.psi-mis.org/api/programStages/of0S2MVj5kZ.json?fields=name,programStageDataElements[dataElement[name,code,shortName,id,optionSet,formName,attributeValues[value,attribute]]

Por ejemplo, si buscamos el DataElement del cHaoGgBRQ80 sacamos la siguiente información que tenemos que llevar a nuestro modelo de datos:

- Tabla Question

      - de_name: name
      - code: code
      - short_name: shortName
      - form_name: formName
      - uid: id
      - order_pos: Del atributo cuyo Code es Order -> en este caso 170
      - numerator_w: Del atributo cuyo Code es DENumerator -> en este caso 1
      - denominator_w: Del atributo cuyo Code es DEDenominator -> en este caso 1


      - id_header: El nombre de las headers va a ser un atributo de un DataElement (por desgracia, pero no hay otra forma). Este valor pertenece al atributo cuyo code es DEHeader -> en este caso Inquiry. Por tanto el algoritmo aquí tendría que ser algo como (pensando deprisa), devolver todas las questions ordenadas por su atributo order_pos. Acceder al atributo DEHeader. Es caso de que ese Header name (no habrá header name iguales) esté en la tabla Header no hacer nada, si no está introducir ese header name, incrementando en 1 su order_pos (que empieza desde '0' o '1'). No demasiado fácil.

       - id_answer: El campo OptionSet nos devuelve el nombre (no habrá 2 optionsets con el mismo nombre) de la answer (en caso de que su answer tenga opciones, en caso contrario no existe este campo) -> en este caso el valor es OuiNon (to be removed) (ojo!! Esto lo tenemos mal en el servidor, y el nombre correcto debería ser 'Yes1No0'. a lo mejor para cuando leais esto ya es 'Yes1No0'). Importante: El atributo cuyo código es DEQuesType nos devuelve la representación de esa respuesta (el tipo de layout a crear en android para la respuesta) -> en este caso es el valor 8, es decir un radiobutton horizontal. Los códigos que nosotros tenemos en la QA App para esto (label, positive integer, date, DDL, Radiobutton horizontal, Radiobutton vertical, etc.), salen de aquí. La numeración se mantiene.

        - id_compositescore: Del atributo cuyo Code es DECompositeScore -> en este caso el 1.1


- Tablas QuestionOption, QuestionRelation, y Match (complicadete)

Lo primero entender lo siguiente: En DHIS2 no tenemos en estos momentos capacidad para representar operaciones de show/hide y match vinculadas a opciones (para show/hide probablemente esto vaya a cambiar en los próximos meses, no está tan claro para el match). Por tanto, esto conlleva dos cosas: 1) Tenemos que suponer que el show/hide siempre ocurre cuando el usuario responde 'Yes' en una pregunta padre, y 2) El match siempre ocurre cuando los factores de las answers coinciden. Es decir 1), y 2) tienen que seguir la misma lógica que seguían hasta R10.

Dicho esto, la pregunta es : ¿Cómo unimos las preguntas que forman parte de una relación Parent/Child y/o Master/Relative (o como se llame esto)?. La respuesta es mediante dos atributos. 

Si buscamos el DataElement cuyo id es d2o7cifME4z entonces vemos que tiene los siguientes atributos:

     - Atributo con el Code DEHideType, cuyo valor es PARENT
     - Atributo con el Code DEHideGroup cuyo valor es 20.

Esto significa que esta Question será padre de todas las Questions cuyo DEHideType sea CHILD y cuyo DEHideGroup sea 20, `por ejemplo el DAtaElement con id: fLfac9AuABJ

Las relaciones de Match siguen la misma lógica: Pero en este caso los códigos de los atributos son DEMatchType, cuyos valores son PARENT (el resultado del match, por ejemplo M0dwjE6TviV ), y CHILD (pregunta que tiene que matchear, por ejemplo r1BTbbj12cu). En este caso el atributo con código DEMatchGroup indica las preguntas que conforman está relación.

**Comment by idelcano** [comment]
@ifoche 
We need the code field in the Question(app).
The DataElement(dhis) not have code field now.
it is easy to add , but is in sdk files. I added it in my local workspace(in sdk) and work ok.
Is it ok?


And, i think, i need access to the attributes to continue with header, QuestionRelation.

@ivanarrizabalaga

I need to add Anwser to the id_anwsers field in Question .

But i dont know how do it without pulling duplicate data. 
I only know this way:
(In PullController)
I add variable
static Map < String, Response> AnwsersList = new HashMap ();
And i have acces to the AnwserList you pulled before.

And in your method
visit ( optionset sdkOptionSet )
adding
AnwsersList.put ( sdkOptionSet.getName ( ) , appAnswer ) ;

When i need the anwser, i get from AnwserList:

appQuestion.setAnswer((Answer) AnwsersList.get(anwser.getName()));

It´s similar to popullate
But i think is not the correct way.
Any suggestion? how can get the pulled Answer?
Why not save the static HashMaps like in PopulateDB?

Thanks

**Comment by ivanarrizabalaga** [comment]
@idelcano sure.

Move the map from the visitor into the controller so you can share the
converted objects and recover them later in order to create the
relationships.

Key: uid
Value: Object (the app corresponding item)

The visitor receives the controller in its constructor and so..

**Comment by idelcano** [comment]
@ivanarrizabalaga

Thanks, it´s work.
I was thinking the uid is not unique always, or maybe in some table we dont have uid. 
I don´t know, but at the moment works fine.

**Comment by ifoche** [comment]
@idelcano sorry, I was travelling, and disconnected. I'm now back. Let me check what you're saying but, as a first approach, I would say no, don't edit SDK files. Think on this as the populate of the CSV files. @josemp10 was all this time creating the CSV using the information coming from the DHIS server, so if you don't find a field, before adding it by yourself, ask him where can you find it. In principle, only those fields that are stored in Attributes should be out of your scope. @josemp10, is this the case of code?

**Comment by idelcano** [comment]
@ifoche 
Ok!
Only remember:
The code in the server is in DataElement as field, as @josemp10 said:
https://hnqis.psi-mis.org/api/programStages/of0S2MVj5kZ.json?fields=name,programStageDataElements[dataElement[name,code,shortName,id,optionSet,formName,attributeValues[value,attribute]]
[...]
"dataElement": {
    "id": "w2L7ztygH2x",
    "name": "HNQIS-ICM-1-C.Scores-ICM-100-Inquiry",
    "code": "HNQIS-ICM-1-C.Scores-100",
[...]

But is not in the DataElement model in sdk.

**Comment by josemp10** [comment]
@idelcano, yes the uid is always unique.

code: It is not an attribute. Anyway, no, we shouln't add our java code in
the core definitions of the SDK data model at this stage. If the Data
Element code is not there (are you sure is the case?), it is ok, we dont
reallly need it (it was important to manage the CSV files because of the
uids, but with the pull we are getting their uids directly). Anyway, will
try to think if there is an scenario in which we may need the code, but for
now, you can keep it blank.

**Comment by ifoche** [comment]
@idelcano ok, I see. I was looking at the SDK tables directly. My fault. You're right, in that case, we could make a PR at some stage in the future against their code. For the moment just push that code (the sdk field addition) to a local branch and we will think on doing the PR later

**Comment by idelcano** [comment]
@josemp10 Some DEHeader attributes had the value "value": "ICM ", and others "value": "ICM". I think the correct value is without blank space in all of them.

**Comment by josemp10** [comment]
Yes, "ICM" (no blank spaces) sorry, We will be reviweing the values of all
attributes during the next week... (don't worry too much about possible
mistakes or weird values)

**Comment by idelcano** [comment]
@josemp10 How can I know what questions are "yes"? (id_option in a QuestionOption table)

**Comment by josemp10** [comment]
ahmm.... SDK or QA app data model?

You need to know which optionset belongs to a dataelement, list all options
of the optionset. and check if the option name is 'Yes'..  (dataelement,
optionset, and option tables, I gues)

Sorry.. I dont know if this was the answer you were asking for?

**Comment by idelcano** [comment]
Yes, it was the question.
i look some yes code field like Yes, Yes[0], Yes[1], and Qui qui[0] qui[1].

The field name is yes for the "Yes [0]" "Yes" "Yes [1]" option code.
But, The field name is qui for the "Yes [1]" "Oui [1]" "Oui [0]"  option code.
I need check if the option name is "qui" too? or only for "yes"?.

Thanks @josemp10

**Comment by ifoche** [comment]
@idelcano, I think what you need to check is that the field corresponds to the "Yes" string in strings.xml (so by calling context.getString("Yes"). That will give you the string in the selected language. The point is that "Oui" will be the one when the database is in French (as in Mozambique), but "Yes" would be the case when the database is in english. As we don't have any other way to detect if the DB is translated or not, we will have to rely for the moment, in the android language settings. We can think about introducing any way for selecting manually the language of the remote DB, but for the moment, I think that will be the best

**Comment by josemp10** [comment]
Yes, I agree. We have 3 different languages in DHIS2: English, French, and
Portuguese. This means that the 'Yes' option may be 'Oui' and 'Sim' as
well. So, if it is possible to check the current value using the
strings.xml, I think is the best way, yes.

This is something that is going to change in the server side in a couple of
months, so it may be easier to detect in the client side.

**Comment by idelcano** [comment]
Thank josemp10 and ifoche, i understood.

I thought I had finished, but i look a problem getting  the id_compositescore in the Questions.


I dont understand how get it now.


@josemp10 you said id_compositescore: "Del atributo cuyo Code es DECompositiveScore-> en este caso el 1.1"
The attribute with Code "DECompositiveScore" have a UID. I was trying to get a CompositeScore from that UID. But ivan gets the dataElement uid(dhis) for the CompositeScore uid(app), not the attribute UID, and the code(1.1 in your example) is not unique.

**Comment by ivanarrizabalaga** [comment]
dont worry @idelcano, we can clarify this in our meeting today, :D.


[image: http://]
Ivan Arrizabalaga
[image: http://]about.me/ivan-arrizabalaga
<http://about.me/ivan-arrizabalaga>

**Comment by ifoche** [comment]
@idelcano, I'm not sure if this answer your question but just in case...

@ivanarrizabalaga is getting from all the dataElements those who are CompositeScore  separating them by program. That way, the ID is unique (each CS only can belong to a program at a time). So probably you will need to insert your code in Ivan's one, in order to do it whenever those IDs are unique (after separating them by program)
