### ISSUE TITLE
Re-allocate Login in app start

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#508]

**Comment by ifoche** [comment]
Is needed to reintroduce sdk login integration branch and be able to pull the data, in order to translate data using the visitors pattern

**Comment by ifoche** [comment]
There is a problem when bringing back SDK integration branch to life. Apparently there is a problem when multiple DB and MultiDexEnabled. [Here](https://github.com/Raizlabs/DBFlow/blob/master/usage/DBStructure.md) there is more info about this

**Comment by ifoche** [comment]
The problem is addressed [in this bug report](https://github.com/Raizlabs/DBFlow/issues/266).
We probably would need to [include the library in the project as a repo](http://stackoverflow.com/questions/20377591/how-to-use-a-library-project-in-android-studio) and implement ourselves the solution in 3.0.0 version of DBFlow

**Comment by adrianq** [comment]
I have finally solved the bug. The instructions to configure the environment (malariapp-sdk-dbflowcustomised) can be found [here](https://docs.google.com/document/d/12Ctygrl16AAde429uc7diUM7M_Mxeo57Qw92ykdU5Bw/edit). The login has been reallocated at the beginning although no data is automatically pulled to the sdk db. A specific card will be create to do it.
