### ISSUE TITLE
Review release 12

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/malariapp#514]
Minor changes to release 12
- [x] Chart 1: center the legend, include it directly underneath the title and layer it horizontally instead of vertically
- [x] Chart 1: increase slightly the font size of the title
- [x] Chart 2: missing a small description in the lower right of the graphic. It is included in the feedback notes. The text should read Quality of Care (based on last assessment). Font color should be black. 
- [x]  Chart 2: font size of title to be in line with font size of title for chart 1
- [x] Chart 3: ​title should be simply 'ICM Assessment checklist', which is the name of the program I presume. It currently reads 'Quality of care (based on last assessment)
- [x] Chart 3: font size should also be increased to be in line with adjustments for charts 1 and 2
- [x]  General:  insert just a little more space between the last sent assessment and the title of the first chart. 
- [x] General: change the prompt that appears with a long press on an active assessment from the landing page to read 'View Feedback' instead of 'Preview Feedback' in the answer options

**Comment by adrianq** [comment]
The small description in the lower right of the graphics should be something along these lines:
![screenshot from 2015-10-23 10 28 57](https://cloud.githubusercontent.com/assets/6850223/10689204/4ef464b8-7971-11e5-992f-eded1963e28d.png)

**Comment by adrianq** [comment]
@ivanarrizabalaga I have reopened this issue as there are a few more fixes/improvements in this release:
- [ ] Changes in [this stylesheet](https://docs.google.com/presentation/d/11q6bPIO3IhqW-aT-52fe5ZojTtioDnAsOwSBfjYXc6o/edit#slide=id.p3)

**Comment by ivanarrizabalaga** [comment]
@adrianq, @ifoche it looks like I need to check the crashes from https://fabric.io/login but which credentials should I use?

**Comment by ivanarrizabalaga** [comment]
Expaded details on review, minor fixes:

- [x] Do not display TabGroups in Dashboard, only Program
- [x] Create button disappears (**cannot be reproduced**)
- [x] Lighter blue for 1.5 IUCD Removal (**cannot be reproduced**, data error)
- [x] Horizontal centered legend underneath title (**previously done**)
- [x] Increase font size title (**previously done**)
- [ ] Org unit name sometimes disappears 
- [ ] Going from Feedback back to Dashboard

New functionality:

- [ ] Turn  the 'averages' table into N tables (1 x program)

**Comment by ivanarrizabalaga** [comment]
Regarding going from Feedback to Dashboard:

```
Fatal Exception: java.lang.NullPointerException
       at org.eyeseetea.malariacare.layout.score.ScoreRegister.addRecord(ScoreRegister.java)
       at org.eyeseetea.malariacare.database.model.Question.initScore(Question.java)
       at org.eyeseetea.malariacare.layout.score.ScoreRegister.initScoresForQuestions(ScoreRegister.java)
       at org.eyeseetea.malariacare.layout.score.ScoreRegister.loadCompositeScores(ScoreRegister.java)
       at org.eyeseetea.malariacare.database.feedback.FeedbackBuilder.build(FeedbackBuilder.java)
       at org.eyeseetea.malariacare.database.feedback.FeedbackBuilder.build(FeedbackBuilder.java)
       at org.eyeseetea.malariacare.services.SurveyService.getFeedbackItems(SurveyService.java)
```

it seems it was something related to data since the crash comes from a NPE in:

```java
compositeScoreMap.get(question.getCompositeScore())
```

this means that for the tested variant (hnqisKenya) there was something wrong with a score and a question.

**Comment by ivanarrizabalaga** [comment]
The original request was:

 - #459 N Pie charts (1 x program)
 - #480 **1 table** at the very end of the screen with averages of scores grouped by orgunit (called providers in issue) (@adrianq I was wrong, data is currently grouped by orgunit instead of program).

So now the current code generates something like this:

![dashboard_several_units](https://cloud.githubusercontent.com/assets/4146319/10738436/c1dff6ec-7c17-11e5-9a2f-92d214580288.png)

After reading the feedback in doc (https://docs.google.com/presentation/d/11q6bPIO3IhqW-aT-52fe5ZojTtioDnAsOwSBfjYXc6o/edit#slide=id.p9) it is not 100% clear to me.

**Questions:**
*Should we show 1 chart +1 table x tabgroup?*
*In that case each table must have 1 row per orgunit?*
