### ISSUE TITLE
Extract functionality to trigger sdk pull and encapsulate it in a function that will be executed when populating malariappDB

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/malariapp#516]

**Comment by ivanarrizabalaga** [comment]
Some random notes:

The sdk uses a service (*DhisService*) and a bunch of controllers (*DhisController, LoadingController, MetaDataController...*).

There are 2 different types of loads (*LoadingController*):
 
 - loadMetaData
 - loadDataValues 

Metadata does not seem to load if you dont explicitly enable each type of metadata (which is load in a given special order):

 - Assigned programs
 - Program data
 - Option sets
 - Tracked Entity Attributes
 - Constants
 - Program rules
 - Program variables
 - Program rule actions
 - Relationship types

This seems a little bit weird so I will probably check it again.

After enabling **assignedprograms**  the sdk asks Dhis server for programs (HTTP 500 https://hnqis.psi-mis.org/api/me/programs/?fields=%5B%3Aall%5D ) but I'm getting a **500 error from the server** (not only with my credentials but with @aquintana too).

Maybe @josemp10 has an intuition about this issue (permissions? I dont know anything about dhis scheme).

**Comment by josemp10** [comment]
can you try again @ivanarrizabalaga? I gave you total permissions for Kenya
(so please, be super careful now :) ). Let me know (will probably check the
email tomorrow morning)
