### ISSUE TITLE
Update DB without needing to reinstall

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#519]

**Comment by ifoche** [comment]
This is documented here
EyeSeeTea/pictureapp#116

**Comment by ifoche** [comment]
We need change the populate to replace the old database with a new one in case of database version number. After finishing it, copy this change into picture app

**Comment by idelcano** [comment]
@ifoche  I'm not sure why I was not assigned to this card.(I look it now..)
I've found a way to reset the DB and repopulate the data in the migrate class with version control.
I created a new branch with the example in pictureapp. 
https://github.com/EyeSeeTea/pictureapp/commits/repopulate_example

**Comment by ifoche** [comment]
@idelcano thank you. Sounds good. Remember that yesterday we said you will create an equivalent card in pictureapp to do this task there, as we're not going to do it in malariapp for the moment. That's the reason why this card will remain here, unassigned, in the backlog (just in case in the future we decide to bring that change here too)

**Comment by ifoche** [comment]
This will only be needed after the app is in GPlay, but anyway,  we'll do it as the last task of the release, to be able to manage the bugs that PSI will probably ask us to repair after the release is over, thanks @idelcano for signaling the importance of this

**Comment by idelcano** [comment]
@ifoche i create and upload the branch for the migration from old app, to the google play app. I´m not sure if it is needed... Only change the table Attribute and the code column in DataElement table.
I ´m not sure if it is needed at this moment.
