### ISSUE TITLE
Repair app flow in visitors_try

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#530]

**Comment by ifoche** [comment]
Login is reintroduced at the beginning but now, when trying to push, it takes you to LoginActivity and waits for authorization. The old app flow must be rescued, so when login is done, the user is set, and a logout allows the user to exit to LoginActivity again. Push doesn't need the login to be introduced, as it is set at the beginning. Logout deletes every user data in the app (as it used to do)

**Comment by ivanarrizabalaga** [comment]
Mini tasks:

 - [x] Intercept and save right credentials while login.
 - [x] Check preferences ok with intercepted credentials
 - [x] Logout: delete data, logout dhis and go to login
 - [ ] Push on long click
