### ISSUE TITLE
Filter orgUnits by variant (and other possible tables)

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#547]

**Comment by ifoche** [comment]
When we call the pull, we're retrieving every orgUnit, even those not assigned to our variant. We need to establish a filter in our side (not touching the SDK files for that) to select the metadata that correspond to the selected variant

**Comment by josemp10** [comment]
I dont know if I am following properly this. So, with the SDK the org.
units retrieved wouldn't depend on the variants (also, do we need Variants
with the pull? why?), but on the org. units that the user has access to...

**Comment by ifoche** [comment]
Yes, I think you've understood what's happening. Variants are still needed because we have EDS and HNQIS separation, bug however, if we want to limit the access of a user to a given country this is the only way that we have. I thought PSI was worried about this kind of things (by political issues). I mean, giving Kenya their apk and Tanzania their apk. Do you think that they're not? Did they told you that we can just create a unique apk for everyone and control this with the permissions from the server. For us, of course, is easier in that way

**Comment by josemp10** [comment]
Ok, I understand the Variants for EDS and HNQIS,

but yes, the idea is to have one single APK for HNQIS. The users
(supervisors), are going to belong to a single PSI regional office
(country). But in any case, the access can be controlled from the server
(even with a user working in 2 countries). It is just a configuration in
the server of programs, users, and org.units.

**Comment by ifoche** [comment]
Ok, thank you for the news @josemp10. @ivanarrizabalaga, as you can see, you can forget about this task, we're not going add filters to downloaded data. They will dispose the data/permissions in the server side

**Comment by ivanarrizabalaga** [comment]
Cool, thanks @ifoche and @josemp10
