### ISSUE TITLE
Try to organize a little bit layout xmls

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#55]
This is not direct, because we have to take care of some android specific things (see in link)
http://stackoverflow.com/questions/4930398/can-the-android-layout-folder-contain-subfolders

**Comment by ivanarrizabalaga** [comment]
Some random thoughts as I run through the code:

  - [ ] Assesment header & Feedback header are the same?
  - [ ] Looks like they need column 'Date'
