### ISSUE TITLE
Pull CompositeScore & separate them from Questions

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#554]

**Comment by ifoche** [comment]
This is going to shock you. Here the explanation sent by @josemp10 (thanks!) about how does CompositeScore works in server side (sorry, it's in spanish):

--
En DHIS2 los DataElements son tb comp. scores

Comp.Scores: Se sabe que un DataElement es un comp. score cuando tiene el atributo "20 Question Type" con el valor de COMPOSITE_SCORE. Además el código del score viene determinado por el atributo "35 Composite Score" cuyo valor será un string con el código "1.2", "1.2.1", "1.2.2". La parte complicada viene ahora, la jerarquía. La única manera que tenemos de especificar jerarquías en DHIS2 es con campos de texto, por tanto no queda otra que implementarlo "a pelo" en la capa de translation del SDK a EST. Es decir, en el ejemplo anterior, tendrías que ir introduciendo la jerarquía por el código: si te llega un 1.2.1, tendrías que analizar que ese string corresponde a un hijo del que tiene código 1.2, y que además ocupará la primera posición de los hijos. Guapo, eh??? En el DHIS2 tendrían que venir ordenados (es decir, no debería estar el 1.2.2 antes del 1.2.1), aunque no hay nada que lo garantice 100%. 
--

This means here there are 2 main tasks:
- [ ] Translate CompositeScores
- [ ] Edit previous Question translation to avoid interpreting the CompositeScores as Questions

**Comment by ifoche** [comment]
This task has a strong relation with #555

**Comment by ivanarrizabalaga** [comment]
@ifoche, @idelcano I coudnt manage to finish this task yet but it will be surely done during the weekend (I'm almost there, :D)

**Comment by ifoche** [comment]
@ivanarrizabalaga ok. Thanks

**Comment by ivanarrizabalaga** [comment]
@josemp10, @ifoche, @idelcano  there is a problem with compositescores.

I have already separated questions from compositescores and save them properly but in order to fulfill its order and parent score fields we need to separate compositescores according to their **different program hierarchies** (FP scores from ICM scores and so on) and I'm not sure how to do this.

![composite_score_program_problem](https://cloud.githubusercontent.com/assets/4146319/11162919/0481a63a-8ab9-11e5-99f5-5aefc34c4e6c.png)

Any ideas? (I'm still looking for options)

**Comment by ivanarrizabalaga** [comment]
@idelcano I've just push the branch **separate_composite_scores** so you can take a look to how I split scores from questions.

**Comment by ivanarrizabalaga** [comment]
@josemp10 in case it is not already solved, would it be possible to add an attribute 'DECompositeScoreFamily' to group scores from the same hierarchy of scores?

From the programming perspective it might be the easiest solution.

**Comment by josemp10** [comment]
@ivanarrizabalaga adding a new attribute for comp. scores is going to be
quite complicated now. But I dont completely understand what the problem
is. The comp. scores (data elements) are already grouped by the programs
they belong to. And one comp. score can not belong to different programs.

Anyway, maybe I am not understanding you well. You can reach me on skype
(or hangout) if you want.

**Comment by ifoche** [comment]
@ivanarrizabalaga, does not solve your issue what @josemp10 have just said? Looking at the program each dataElement (CS) belongs to would let you group all CS for one program, and then, you would be ready to establish the hierarchy...could that work?

**Comment by ivanarrizabalaga** [comment]
@ifoche, @josemp10, yeah I think you both are ok. I was looking at the current API and there is no way no navigate from a dataelement to its programstage but it can be done via SQL.
