### ISSUE TITLE
Pull data (on demand)

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#555]

**Comment by ifoche** [comment]
What we need to pull is only very selected data. We need to pull the exact data that gives us the needed information to fill in the monitoring section. That is 
- CompositeScore values (dataValues for CS dataElements)
- Minimum information needed from the rest (I cannot identify anything else at this moment) to represent monitoring section with last 6 months data

This process, for the moment we're going to leave it on demand (as an option in the menu, like with the pull) and only after checking that pull is being completely done and there's no doubt about how it is working, then we would include it into the automatic pull after the login, and at the end of the manual-called pull option

**Comment by ifoche** [comment]
This task has a strong relation with #554

**Comment by ifoche** [comment]
Finally, there won't be necessary to filter data before pulling it. We will download everything, at least for this release. The client hasn't answered yet, but he'll probably answer that, as I've read in an specifications document and edition from his side (late october) that said that. So let's assume downloading everything (the easiest approach), and I'll communicate if there is any further change

**Comment by ifoche** [comment]
Client confirmed, we will download everything, but after the release is over, we will have to assess the amount of used memory for 6 month of survey storing and see if it worth the pain of avoiding that storage

**Comment by ivanarrizabalaga** [comment]
Then I'm putting this issue back to backlog, ok @ifoche?

**Comment by ifoche** [comment]
But...are we already getting dataValues? If not, that is what this issue is about

**Comment by ivanarrizabalaga** [comment]
Ok @ifoche I thought this was only about filtering 'what data to pull' not about pulling data values.

Understood, back to 'ready'

**Comment by ifoche** [comment]
ok, thanks. The goal is to make it at the end of the metadata pull, but if you find it better to start by adding it as a separate option in dashboard, and after checked, integrate, it's ok
