### ISSUE TITLE
Push data using SDK

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#556]

**Comment by ifoche** [comment]
Client has just asked us to upload, with the push of each survey, the control dataElement _Forward Order DE. Concretely, to write '9999' in the _Forward Order DE on survey push. This (uploading control dataElements) is something that Adrian implemented some time ago and can be searched in the history by "control dataElement". Their uid (for control dataElement) was stored in strings.xml if I'm not bad. It would be basically, upload this DE in the same way, but through the SDK

**Comment by ifoche** [comment]
Client answered, we need to mix both actions. Pull of data and pull of metadata will be result of the same action. That is, @ivanarrizabalaga:
- Leaving the menu option as "metadata refresh" as it was the last name they gave us, even knowing that probably they'll ask us to change it in the future
- Put the data refresh automatically launched after the metadata refresh

**Comment by ivanarrizabalaga** [comment]
@josemp10 is it possible to reduce in the server the number of  programs assigned (ICM + any other would be fine) to my user? 

I guess I have too many permissions and 1 pull gets 2 orgUnits x 14 programs => 305 surveys which takes 7min each time I'm debugging anything.

**Comment by ifoche** [comment]
@josemp10 could you do it for all of our users? that is a problem we're all suffering from. Otherwise, if you can tell us how can we do it by our own, we can avoid wasting your time

**Comment by josemp10** [comment]
@ifoche, can you try it now again? You (and the others), should be able to
see only ICM and Family Planing program...

Your user is ok, but it is the number of programs activated in the org.
units. I removed almost all of them for the testing facilities in Kenya,
just leaving ICM, and Family Planning. This shoulh work for all users. Let
me know, otherwise...

**Comment by ifoche** [comment]
thanks @josemp10, that reduced the downloading time

**Comment by ivanarrizabalaga** [comment]
I've just pushed **push_with_sdk** branch, it compiles and should be mostly done but I cant manage to test it now since there is something broken while trying to create a new survey.

Creating a survey is not working yet, right?
