### ISSUE TITLE
GUI changes

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#558]

**Comment by ifoche** [comment]
![dashboard_r13_changes](https://cloud.githubusercontent.com/assets/10931645/11134070/5cf54bfc-899a-11e5-80d1-0f04824a40c5.png)

**Comment by ifoche** [comment]
summary of changes:
- [ ] User logged at the top of the screen
- [ ] Sent assessment changes by Previous Assessment

**Comment by idelcano** [comment]
@ifoche I have a two little questions about the second task.

1 Do I have to make changes in french, spanish, and Portuguese strings?
I think yes, but i need use google transator.

from Evaluation(s) Envoyée(s) to Evaluation(s) antérieur(s)
from Avaliação enviado to Avaliação anterior(es)

2 Actually is "Sent Assessment(s)" and "Active Assessment(s)",  Do I need to change this to "Previos Assessment" and "Active Assessment"?
I think no. I only change Sent to Previous.
