### ISSUE TITLE
organize a little bit strings

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#56]

**Comment by ivanarrizabalaga** [comment]
Hi @EyeSeeTea/developers, 
the naming convention for string resources will be the following (changes are not available in 'development' yet) :

 - LABEL: General purpose strings.
 - CLASSIFIER_TYPE_LABEL: For the rest of strings (used somewhere along the app) the key is made of 3 parts:
     - CLASSIFIER:  The view where it is used (layout/fragment/etc)
         - settings
         - login
         - dashboard
         - survey
         - create
         - auto
         - custom
         - analytics
         - assesment
         - feedback
         - future
         - performance
     - TYPE: Type of element (menu/title/etc)
         - menu
         - info
         - error
     - LABEL: Free form label that shortly describes  the purpose of the string.

Examples:

 - settings_menu_about
 - dialog_title_license

**Comment by ifoche** [comment]
Perfect. Can you please put that in a document in shared folder of the Drive with a name like "EyeSeeTea Android Programming style guide". This way, we'll have a document to add the different de-facto standards we make, and so, a guide to look before doing anything (and a guide to reference whenever we change something from another guy of the team)

**Comment by ivanarrizabalaga** [comment]
Sure!

**Comment by adrianq** [comment]
@ivanarrizabalaga Can you let me know where I can find the doc? I was looking for the doc but I couldn't find it... maybe in some folder I can't read?

**Comment by ivanarrizabalaga** [comment]
@adrianq I thought I shared the document with everyone but obviously not.

**Comment by adrianq** [comment]
@ivanarrizabalaga Ok, no worries :) Can you please instead of sharing each with me (and every developer) just copied it to the share folder we have for the project? Sorry for being so picky but I think it is a good idea to have all the docs for the project in the same folder. Cheers!

**Comment by ivanarrizabalaga** [comment]
@adrianq Sure! :D

**Comment by ivanarrizabalaga** [comment]
@adrianq
It looks like is already there! 
By the way, I have **2 different ** 'Shared with developers' folders in my drive, I dont know why.

**Comment by adrianq** [comment]
Thanks @ivanarrizabalaga! @ifoche Can you have a look at this?

**Comment by ifoche** [comment]
Hi, yes @ivanarrizabalaga, you have one "Shared with developers" for the Android App project, and another one for the DHIS app one. I thought it would appear to you in a different way, but I can change the name to make you easier to recognize if it helps.

**Comment by ivanarrizabalaga** [comment]
@ifoche 
Yes please! Now they both look exactly the same to me.
Thanks!
