### ISSUE TITLE
Logout changes

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#560]

**Comment by ifoche** [comment]
As OrgUnit is now selected at login time, there must be a preference for the selected orgUnit (take it from pictureapp) and this must be deleted at logout time

**Comment by ifoche** [comment]
Related to #559

**Comment by idelcano** [comment]
The orgUnit will be a sharedPreference like the user name the server name and the user password. It is correct?
The orgUnit is not saved in sharedPreferentes  at this momment (visitors_try branch).
I need do  before the #559?

I create a string.xml for the orgUnit like user/pass/server. 
I created a method to remove the orgUnit sharedPreferent.
but it not exist now. It is waiting for it to work.

**Comment by ifoche** [comment]
@idelcano sorry, I think it was my fault. If you look at the last comment in #559, you'll see that client finally decided to drop that change from this release. I should have to remove, consequently, this related issue, as it makes no sense anymore without that other change, but I didn't. Can you keep that changes in a local branch, so we can come back to it in the next release?. I'm so sorry, it was completely my fault

**Comment by idelcano** [comment]
No problem ! 
Yes, i keep the changes in local branch to the future.
