### ISSUE TITLE
Push before delete unsent surveys

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#561]

**Comment by ifoche** [comment]
There is already another issue that will talk about this task (see )

**Comment by ifoche** [comment]
When the user press on pull option (that must be renamed to "Metadata refresh"), if there are unsent surveys, the user must be asked whether or not (s)he wants to push them before deleting all the data.

**Comment by ifoche** [comment]
@ivanarrizabalaga, as @idelcano has been very quick with his assigned issues, I'm reassigning this task to him. Please forget about it

**Comment by idelcano** [comment]
I finished this task, but i need try in actual version when we had a surveys to be sent
