### ISSUE TITLE
Dashboard must only show last survey completed for each OrgUnit

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#562]

**Comment by ifoche** [comment]
In sent surveys, at this moment we can have several sent surveys for the same OU. This need to be changed, and only show the last filled in survey

**Comment by ifoche** [comment]
@ivanarrizabalaga, as @idelcano has been very quick with his assigned issues, I'm reassigning this task to him. Please forget about it

**Comment by ivanarrizabalaga** [comment]
Grea thanks!
