### ISSUE TITLE
Review the downloaded dataElements to filter those who aren't questions

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#568]

**Comment by idelcano** [comment]
I´m waiting fot test.
 And i waiting for diferenciate the complete questions and not completed questions.
 642 questions has a id_header null and order_pos null from 1198 
And 556 has order_pos and id_header.

**Comment by ifoche** [comment]
@josemp10 is creating the attribute for both (real questions and control dataElements) at this moment, he will tell us when it's done

**Comment by josemp10** [comment]
I have already answered this in other ticket (sorry) . So...

- I didn't create a new attribute for control dataElements, but added the
new option 'CONTROL_DATAELEMENT' to the Question_Type attribute. It should
be enough in order to distinguish between Questions, Control Data Elements,
and Comp. Score.

- Having 642 questions without header... it shouldn't happen (I am really
surprised about that). There is an script that automatically creates these
dataelements in DHIS2. So, can you let me know 2 or 3 questions without
header? and their program? (same with order_pos==null)

**Comment by ifoche** [comment]
@idelcano,  apparently, there won't be any further Attribute. Things will remain untouched, so what I would propose to you is to change the "isQuestion()" method. Now, you're determining isQuestion() as ([see here](https://github.com/EyeSeeTea/malariapp/blob/visitors_try/app/src/main/java/org/eyeseetea/malariacare/database/iomodules/dhis/importer/QuestionBuilder.java#L411-419))
if you're control dataElement --> false
if you're compositeScore --> false
else --> true

I propose you to check, instead of that else, the following:
if you're in (list of possible question Types that are real questions)) --> true
else throw Exception / error message ("dataElement with UID XXXX not a valid CS, control DE nor question. Ignoring it...")

Can you do it? I hope it's clear. Thanks!

**Comment by ifoche** [comment]
@idelcano, I hope it's not too late. If you've not started with this, don't do it. The client finally accepted the suggestion of introducing a new Attribute, so if you haven't started yet, leave it as is, until we know that in the server the attribute is uploaded. Otherwise, ok finish it, after this change the only thing that we would need to re-write in the future will be "who are we asking for" to know if it's a question or not.

**Comment by ifoche** [comment]
Hi @josemp10, are there any news about the change of the Attributes to divide in DEType and DEQuestType?

**Comment by josemp10** [comment]
Hope to finish with the script at the end of this week. the server
administrator could execute it during the weekend or next Monday

**Comment by ifoche** [comment]
ok, thank you for the efforts

**Comment by ifoche** [comment]
@josemp10 do we know anything else about this?

**Comment by josemp10** [comment]
No, sorry. People involved on this (Graham, James/Jose) are extreamily busy
these days. We are meeting in Nairobi in 3 days, I can tell you more by
that time. Hope we can have it during the following week. Really sorry for
the slow work on this task.
