### ISSUE TITLE
Re-design the architecture of the app

### ISSUE THREAD

**Issue by josemp10** [EyeSeeTea/malariapp#57]
We need to think in the long term. The app is going to host different types of surveys, and also there are many new components that we need to manage. Some of them are:

- Feedback to the users
- Charts (data analysis)
- Planning to the next visits
- Pending surveys and complete surveys
- ....

This issue is not related to a refactor of the code, but to discuss several options about architecture as:

- Activities we need to create and its relation with the databsae
- New GUI
- Fragments
- etc...

**Comment by ifoche** [comment]
Already being implemented
