### ISSUE TITLE
QuestionRelation match problem

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#578]

**Comment by ifoche** [comment]
- Remember to look at the lucid chart to refresh the explanation about how the Math/Parent-Child questions are mapped into our DB (through QuestionOption, Match and QuestionRelation tables)
- Remember to re-do the parent-child mapping with using those 3 tables instead of the deprecated field id_parent

**Comment by idelcano** [comment]
@josemp

In match relations (questionrelation with operation 0)

I have  two questions child(match questions), and one question parent(match
result).

How can i know what  options values of the childs makes a match?

**Comment by josemp10** [comment]
@idelcano , because the factor of their answers is the same. So, for
example we have:

Q1: Diagnosis
Q2: Treatment

Q3: Does the diagnosis and Treatment match?

If the option factor for the Diagnosis answer (ex: Malaria -> 1), is equal
to the factor for the Treatment answer (ex: ACCT -> 1), both questions
match, and the answer for Q3 should be 'Yes'.

Let me know if it is not clear.

Thanks
Jose

**Comment by idelcano** [comment]
@ifoche @josemp10 maybe you can help me .
I was getting 3 groups of 6 childs/parents in MATCH relation(it could be 2child/parent).
It is becouse the 6 childs and 3 parents have the same DEMatchGroup attribute value.

For example
DEMatchGroup value=40
Parent: M0dwjE6TviV
Childs: h8jxRGcOqLf, r1BTbbj12cu, YtNPDDGkCqK, Op14xNMJi14, dl18H9KCLVF, hCFXSF0S3jh

Others 2 parents with same MatchGroup:
https://hnqis.psi-mis.org/api/dataElements/M0dwjE6TviV
https://hnqis.psi-mis.org/api/dataElements/Kb10vGu8WmT

In the Questions.cvs:
h8jxRGcOqLf and r1BTbbj12cu is in kenya,nigeria,tanzania questions.csv
dl18H9KCLVF and hCFXSF0S3jh is in congo question.csv
YtNPDDGkCqK, Op14xNMJi14 is not in the questions.csv

I looked dl18H9KCLVF and hCFXSF0S3jh are in tabname:  "Diagnostic, traitement et conseil"
the others 4 are in "Diagnosis, Treatment and Counseling" tab

How can i filter it?

**Comment by ifoche** [comment]
One question @idelcano. Do they belong to the same program? (The questions)

**Comment by idelcano** [comment]
I'm sorry , I did not see your response yesterday.

They are not in the same program.

Parents: 
M0dwjE6TviV program: vLTSa8wPqQ8 ICM checklist
Kb10vGu8WmT program BJV77y7qknZ ICM Checklist (French)
rTZ1EI1HBSt program: d6PHrjjljS1 KE HNQIS IMCI

Childs:
YtNPDDGkCqK program: d6PHrjjljS1 KE HNQIS IMCI
Op14xNMJi14  program: d6PHrjjljS1
dl18H9KCLVF  program: BJV77y7qknZ ICM Checklist (French)
hCFXSF0S3jh  program: BJV77y7qknZ 
h8jxRGcOqLf  program: vLTSa8wPqQ8 ICM checklist
r1BTbbj12cu  program: vLTSa8wPqQ8 

But, the relations(DEMatchGroup) not are unique?
I always need check the program? for the relation child/parent too?

**Comment by josemp10** [comment]
@idelcano, I am afraid the Groups (both, Match and Child/Parent) are not
unique. They are unique of course inside a program, but not in the
system... so, yes you might need to check the program...

**Comment by idelcano** [comment]
Ok thanks @josemp10
