### ISSUE TITLE
Massive Refactor

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/malariapp#58]
- [x] Create login, create form, dashboard
- [x] Finalise login activity
- [ ] Unit test:
   - [ ] Compositive scores
   - [ ] General Scores
   - [ ] Layout automatic tab
   - [ ] Layout custom tab
   - [ ] Db
- [x] Upgrade Db Schema
- [x] Read/write db

**Comment by adrianq** [comment]
See #49

**Comment by josemp10** [comment]
Estuve repasando el documento de la planificación, y creo que la plantilla para los diferentes componentes de la dashboard se puede sacar de ahí. En la segunda página donde pone 'Landing Page':

https://docs.google.com/document/d/1rm5j9G_JKV0hlD4mv2enCeyx31hMXlckV9UoqFsrZdU/edit#heading=h.x6bs6msqemc2

1 - Pending Questionaries:
 
    Código de la facility y el nombre. Fecha de inicio del llenado del survey. 
    Status: 'Ready' en caso de que se hallan respondido todas las preguntas, XX/YY indicando el número de preguntas respondidas del formulario (en el ejemplo 28 de 834). Dos botones 'Edit'  y 'Delete' para el caso de surveys no completas. Y 'send' para el caso de que estén completas.

2- Planning:

Código y nombre de la facility.
Próxima visita
Dos botones, 'start' para empezar ese formulario, 'reschedule' para cambiar la fecha

3 - Feedback:

Código y nombre de la facility
Fecha en la que el formulario fue complete
Lista de tabs ('FCM', 'RDT', 'Microscopy', ...) con el número de items a revisar por tab

4 - Algún gráfico que se pueda poner para el data analysis (en plan 'Media de puntiuación por mes').

**Comment by ifoche** [comment]
Sip, pué ser. Lo que en el documento pone en el punto 4 "Dashboard", que no
entiendo mu bien a qué se refiere, "My work", pero tu punto 4 mola más.

No pa ahora, pero pa más palante, quizás molaría que se pudiera modelar la
movida de forma que las cosas tipo una facility, fueran clickables y se
llevara al usuario a una página con la info que se tiene de esa facility
(se me ocurre). En general, se me ocurre que un activity/fragment tipo, que
utilizáramos de template para mostrar información sobre un elemento
genérico, podría ser buena cosa. Por ejemplo, lo necesitaríamos igual para
mostrar info de una facility, como para mostrar información sobre un
cuestionario, etc.

(el párrafo anterior puede obviarse, era sólo como idea pa quién sabe
cuándo :) ).





El 14 de abril de 2015, 17:49, josemp10 <notifications@github.com> escribió:

> Estuve repasando el documento de la planificación, y creo que la plantilla
> para los diferentes componentes de la dashboard se puede sacar de ahí. En
> la segunda página donde pone 'Landing Page':
>
>
> https://docs.google.com/document/d/1rm5j9G_JKV0hlD4mv2enCeyx31hMXlckV9UoqFsrZdU/edit#heading=h.x6bs6msqemc2
>
> 1 - Pending Questionaries:
>
> Código de la facility y el nombre. Fecha de inicio del llenado del survey.
> Status: 'Ready' en caso de que se hallan respondido todas las preguntas, XX/YY indicando el número de preguntas respondidas del formulario (en el ejemplo 28 de 834). Dos botones 'Edit'  y 'Delete' para el caso de surveys no completas. Y 'send' para el caso de que estén completas.
>
> 2- Planning:
>
> Código y nombre de la facility.
> Próxima visita
> Dos botones, 'start' para empezar ese formulario, 'reschedule' para
> cambiar la fecha
>
> 3 - Feedback:
>
> Código y nombre de la facility
> Fecha en la que el formulario fue complete
> Lista de tabs ('FCM', 'RDT', 'Microscopy', ...) con el número de items a
> revisar por tab
>
> 4 - Algún gráfico que se pueda poner para el data analysis (en plan 'Media
> de puntiuación por mes').
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EyeSeeTea/malariapp/issues/58#issuecomment-92921904>.
>



-- 
----
Clave pública PGP:
http://pgp.mit.edu:11371/pks/lookup?op=get&search=0x8185416E

**Comment by ifoche** [comment]
This concerns everyone, so @EyeSeeTea/owners

**Comment by josemp10** [comment]
Código fuente de coursera para fragments (por si vale para las dashboards), y muchos más ejemplos: https://github.com/aporter/coursera-android/tree/master/Examples

El mejor tutorial sobre listviews y adapters que ví en la red:
http://www.vogella.com/tutorials/AndroidListView/article.html

Uno de gridview
http://elbauldelprogramador.com/crear-un-gridview-con-adaptador-personalizado-en-android/

Ojo, yo no digo utilizar listviews o gridviews para la dashboard (y tampoco digo que no). Pero sí utilizarlos cuando haya que crear listas dinámicas.

**Comment by ifoche** [comment]
We close it because only unit tests are missing and there's already an specific card for it
