### ISSUE TITLE
Crash on entering feedbackActivity

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#588]

**Comment by idelcano** [comment]
The first problem is there are some Questions without denominator/nominator attributes in the server and without optionset to get the id_answer 
For example:
https://hnqis.psi-mis.org/api/dataElements/Z1a7gvow1iu
If the attributes not exist, denominator/nominator and anwser was null, and the application crash.
(example of complete question: https://hnqis.psi-mis.org/api/dataElements/aqtPzN8cVeN )

**Comment by idelcano** [comment]
@josemp10 is it a problem in the question data in the server ?

We have only 638 completed questions. And  95 Questions without denominator,nominator,optionset attributes.
The list:"MuI7YNE0d5D"
"b1a3MJzOuOd""Mv2NLjncuC2""PYw266QnRnC""dageOTINpMK""xkzT1ZTu7EG""Q61CAFO6iSF""VrZSylKLvk5""QgeZ4YMK3Y4""zdY4u6mzHVt""KQbyCWWP7V4""wb60pbBIrOt""m9HHP1NRCDA""IcncJeZo0LG""DdiLxLwFJx8""GFtHt0LBS1g""AEUP0n1mtXw""guEmPyGLrcr""U1zV7WlFUdR""EXjVAshmhzW""pteWi2eF1Td""kUpb7XFBanC""paEoRED8y8j""sSJb5aCwnau""YE3oBPjuKEi""Bji8I3OZguY""zcqbirITO1""vr1uBFYX54o""McHGQuIV9us""Jkzj5HSXdSz""IBK6cBKeWVq""MwExdj0svp""MGQuBzU24u8""rbc2Y6VNKV9""cIWw0Vx3Mro""fcE82FZozAj""pZZtmxSlFir""qLe9fN6l42h""LdlzZXGucu7""sUaDDpsYVm5""fz5MTTsOTA1""lgpaUPiyzCD""dMmQivtqMHQ""nLtnatD5p07""VBba0bWJEP1""hZ5lgYcLuO3""vDEjLvG96rz""ch6yFpMrAkg""xYTdkMyp3ym""IzCvJ6PLNKj""PljC4yMlWCz""xNjiKzAHTZw""fdyLpnXCT6b""esDpMTDIb1l""nr0ahGkg8tY""tZ50MRD0kiI""vfLDLCnNwIj""gDK0GRWVvHF""cNpTZYL1yQy""ZEQNgrf8pxq""fCBbs4ekGcC""nwoam81M6AU""i7oKXy0pLLV""uyO7HXUowzy""illWFSrbZN2""LZBLBEPQ7eW""kR94QfYAUUv""cvcXVeXDzdT""d1KO5D7K6VL""zSH6Ge65xXa""zlnipDu8O7G""cFxSz6nJD2M""N84CLoEKGAr"
"RlEKzstIPD1""znuK4fxFNyG""DaifDzoDEJE""Uh8dqauixmx""HjQEmI6t5Au""CBZSF1rD0AV""US25TpFR2n7""bWaMtjgG869""rEu50lGGAX7""X5UCPlGUy5h""pbiRti16NPp""ibDdwdGcUg5""gCHeofydbQN""IoGx5Xzr5Fv""F4CPlLK0P6A""cbyxbot2JyE""fQoZq5979Qo""eCjAFxq2HU6""kQpbtp1Yrqa""vzhq8hLWHpQ""eyVfGY07S5m""wu4yiGgpld4"

**Comment by josemp10** [comment]
@idelcano, I have checked this question
https://hnqis.psi-mis.org/api/dataElements/Z1a7gvow1iu , but it contains
the RealSimulated OptionSet right? .... Some questions may not have
optionsets because they are Labels, Date, Positive Integer, ... otherwise
(they are Dropdown list, Radiobuttons...) they need to have an optionset
yes. Have you found some example which is not like that? (If so, let me
know the uid please).

About numerator/denominator...ok, yes, I understand, this is something like
the factors in the options (no factor, means '0' value). So here is the
same, if there is no numerator and denominator (they are null) the value is
'0'. Anyway, I think we agreed with PSI to upload also the '0' values for
num/denum as well. I'm going to check with them, but in the meantime can
you assume that 'null' means '0'?

Regards
Jose

**Comment by idelcano** [comment]
Ok!
For example https://hnqis.psi-mis.org/api/dataElements/b1a3MJzOuOd not have optionset

**Comment by josemp10** [comment]
Yes, but because it is a label (check the QuestionType attribute)... so the
labels do not have option sets (just only Dropdown lists, radiobuttons
vertical and horizontal...)

**Comment by idelcano** [comment]
But, is a label a question? Or need it be filtered?  The aplication is
crashing becouse our  db have 95 question with null  anwser options. Any
clue?  Thanks for  all @josemp10

**Comment by josemp10** [comment]
Yes, right now, a label is a question without an answer... (although it
sounds contradictory)

**Comment by idelcano** [comment]
Ok, the application is crashing in the HEADER ICM becouse his tab is null.
I checking the https://hnqis.psi-mis.org/api/programStages/of0S2MVj5kZ.json?fields=name,programStageDataElements[dataElement[name,code,shortName,id,optionSet,formName,attributeValues[value,attribute]] list and i look some "ICM" and others "ICM " 
i think it is the problem, @josemp10 can you take a look?

**Comment by ifoche** [comment]
@josemp10 we're stuck on this (and this may be hidding some bugs that we are not able to see yet). Can you please check it? Apparently, if I'm not bad, there are 2 headers "ICM" and "ICM " where there should be only one ("ICM"). Is it something that can be more or less quickly repaired? Thank you very much

**Comment by josemp10** [comment]
@idelcano, @ifoche, sorry for the slow answer, I have just arreived from
Etiopia.

@idelcano, sorry, I dont know if I am understanding you properly (answers
between lines ...)

"Ok, the application is crashing in the HEADER ICM becouse his tab is null"

What do you mean? There is no programstagesection for those questions? (the
ones under ICM header)

"I checking the
https://hnqis.psi-mis.org/api/programStages/of0S2MVj5kZ.json?fields=name,programStageDataElements[dataElement[name,code,shortName,id,optionSet,formName,attributeValues[value,attribute]]
list and i look some "ICM" and others "ICM ""

I have renamed all "ICM " for "ICM" (I think, please check). Anyway, the
header name is free text, so there may be some mistakes in the future
(probably it is going to happen some times) coming from the users in charge
of the app content. If that happens, is not the app just showing 2 headers?
"ICM", "ICM "? If this is the case is not our problem, but the PSI staff
(If the app is crashing is our problem, yes)

**Comment by idelcano** [comment]
Thanks @josemp10 

"What do you mean? There is no programstagesection for those questions? (the ones under ICM header)"
Yes. In our database(app) the pull process save two ICM, one with tab, and other without tab.
I will revise all now.

"If this is the case is not our problem, but the PSI staff (If the app is crashing is our problem, yes)"
To prevent this crash...
shouldn't save the questions without header tab?

**Comment by josemp10** [comment]
So, the questions should belong to a programstagesection (is the tab), and
have the attribute header with a value !=null. If for some reason is not
like that (it is not our problem), those questions (with no tab or header)
shouldn't be stored in the app database. I dont know if I am answering your
question.

Anyway, let me know the questions without tabs and header (if you can or
have time enough)

**Comment by idelcano** [comment]
Ok.
Now the problem is:
the dataelements with  DEHeader=ICM
have the DETabName=ICM
But DETabName is not in the ProgramStageSection in the sdk db

For example: kR94QfYAUUv

**Comment by josemp10** [comment]
You can avoid the attribute DETabName. It is not used

**Comment by idelcano** [comment]
sorry @josemp10 , can you refresh me the relation header<->tab (DEHeader<->ProgramStageSection) ?
I´m not sure how can get the tab from the DEHeader attribute.

**Comment by josemp10** [comment]
@idelcano, unfortunately there is no a direct relation between tabs and
headers.

So, for example, if we have:

Tab: HIV
Header: HIV Care and Treatment
Question: Proper history taking and staging of the patient

The tab 'HIV' is stored as a ProgramStageSection (table) in the SDK. There
is one relation between ProgramStageSection (has many) and DataElements. So
you know that the Question belongs to the Tab HIV. The Question
(dataelement) also has the attribute Header with the name "HIV Care and
Treatment", so this is the way to know that the Question belongs to this
header, and the header belongs to the Tab HIV.

I know it is not very easy, but unfortunately we dont have other way to
represent this in the server.

**Comment by idelcano** [comment]
Ok, thanks you @josemp10

I have other question. You said the headers name was unique. But is it unique only in the program, correct?
I detect some headers with diferents tabs in differents programs.( i was filtering by program now).


Anyway:
I refresh your words:"Por tanto el algoritmo aquí tendría que ser algo como (pensando deprisa), devolver todas las questions ordenadas por su atributo order_pos. Acceder al atributo DEHeader. Es caso de que ese Header name (no habrá header name iguales) esté en la tabla Header no hacer nada, si no está introducir ese header name, incrementando en 1 su order_pos (que empieza desde '0' o '1'). No demasiado fácil."

Steps:
1 Loop the questions filtered by program and ordered by order value.

2 Assign the header if exist in the dataelement program
2 or if header is not created, create it and:
     3 Increment header order_pos 
     4 Get the tab from the ProgramStageSection dataElement  to the header.
     5 Save header.


I have doubts with the first step. 
The header.order needs be incremented in order of appearance of question.order ? But i think the questions in diferents programs have a diferent order of appearance...


Thanks for your patience

**Comment by josemp10** [comment]
@idelcano,

I'm really sorry. it is my mistake...

The steps are ok, BUT:

It can not be 2 different headers with the same name in the same tab
(programstagesection), but we may have different headers with same names in
different tabs. So we need to filter by Tab, not program.

The header.order are also "Tab" relatives (they start from 1 per tab), and
yes, needs to be incremented sequentialy (1, 2, 3, ...) following the
question.order

sorry about the confusion...

**Comment by josemp10** [comment]
question.order is also Tab relative,

**Comment by idelcano** [comment]
sorry @josemp10 I think i dont understood 100%.
The header.order depends of tab.order?
For example
Header "A" with Tab "A" is header.order=1
Header "A" with Tab "A" is header.order=2
Header "B" with Tab "A" is header.order=3
Header "A" with Tab "B" is header.order=1
Header "A" with Tab "A" is header.order=4
Header "A" with Tab "B" is header.order=2

is it the way?

And you said "question.order is also Tab relative,". I dont understood  it. 

I order the questions from question.order value. Some questions have the same order.value( for example 21 questions have 100 order value, all with different header but two have same tab). 
How can i know what is first?
Headers:
Question order 100 Header="Diagnosis 1"	"Diagnosis 1"	"4"	"8"
Question order 100 Header="Workplace"	"Workplace"	"5"	"8"
Tab:"8" Inquiry and Physical Examination order.pos=0

Thanks

**Comment by idelcano** [comment]
Well..
@ifoche @ivanarrizabalaga
I don´t understand why the label Question type  not have answer in the sdk and in our app, but it exist in csv.
 
For example in the Tanzania Question.csv, we have the uid: fz5MTTsOTA1
This uid have header and answer, the answer is "label".

The label answer(the optionset) is not in the sdk, and is not in our db.

And this Question fz5MTTsOTA1 is crashing in our app becouse it dont have a Answer.



the problem at this moment in:
AutoTabAdapter.class
//The questions returns not parent(and it don´t have parent).
 boolean hidden = AutoTabLayoutUtils.isHidden((Question) item); 
elementInvisibility.put(item, hidden);
//call this method
 if (!(hidden)) AutoTabLayoutUtils.initScoreQuestion((Question) item, totalNum, totalDenum);
//but inside, get the answer in a Question without answer and crash. 
(F. example: cFxSz6nJD2M)


And if we open a survey:
FeedbackAdapter.reloadHiddenPositions call the method QuestionFeedback.isPassed()

And that method return this.value.getOption().getFactor()==1; but the value.getOption is null. (F. example: kR94QfYAUUv)

Other thing,
@josemp10 now i am ordering the questions by (programstagedataelement.set_order+question.order) for save the headers  in order.

I don´t sure if is correct.

**Comment by idelcano** [comment]
Status:
The new surveys works.
The feedback view works.
If we push a survey, the survey was sent(The push response show, for example, Imported:19 | Updated: 0 | Ignored: 0). But the survey is not moved to Previus Assessments(sent surveys).

The dummy sent surveys:
test facility 2 Works.
test facility 1 have a CRASH exception with the UID kR94QfYAUUv (it have answer, but not have options(becouse is a label answer), and the app search the option factor).
https://hnqis.psi-mis.org/api/dataElements/kR94QfYAUUv
This dataelemente looks like a CompositeSocre
And is in the CSV in CompositeScore table. But in our app is in Question table  #593

I created my survey in test facility 1 and ICM checklist and it didn´t crash (i answered all the options but the score is 96.0%, maybe ignore the CS).



The temporal solution:

if i check the DEQuesType in some of the label was 7, but in others not.
I will investigate now what was the other type of DEQuesType in the Questions without answer field.

I needed force: if getOptionSet==null... set the answer as label.

**Comment by ifoche** [comment]
These are very very good news!! Thanks @idelcano

**Comment by josemp10** [comment]
Between lines...

On Tue, Nov 24, 2015 at 2:26 PM, idelcano <notifications@github.com> wrote:

> sorry @josemp10 <https://github.com/josemp10> I think i dont understood
> 100%.
> The header.order depends of tab.order?
>
No, the header order depends on questions.order.


> For example
> Header "A" with Tab "A" is header.order=1
> Header "A" with Tab "A" is header.order=2
>
You can not have two (or more) equal header names in the same tab

> Header "B" with Tab "A" is header.order=3
> Header "A" with Tab "B" is header.order=1
> Header "A" with Tab "A" is header.order=4
> Header "A" with Tab "B" is header.order=2
>
> is it the way?
>
> And you said "question.order is also Tab relative,". I dont understood it.
>
Question.order (100, 110, 120,...) is unique per Tab, not for programs


> I order the questions from question.order value. Some questions have the
> same order.value( for example 21 questions have 100 order value, all with
> different header but two have same tab).
>
Headers are not relevant here. Question.order should be unique per tab not
for header. Have you found 2 question with the same order in the same tab?


> How can i know what is first?
> Headers:
> Question order 100 Header="Diagnosis 1" "Diagnosis 1" "4" "8"
> Question order 100 Header="Workplace" "Workplace" "5" "8"
> Tab:"8" Inquiry and Physical Examination order.pos=0
>
Ahm... Do this questions belong to the same tab?

**Comment by idelcano** [comment]
Ok, next step:
@josemp10 Is It possible to add in the server a answer to the "labels"?

The 79 Questions with  DEQuesType value=7(No answer) it is assumed as "Label".

But we have this Questions withut answer, and without DEQuesType value= 7:
DEQuesType value=2 UID kR94QfYAUUv HNQIS-ICM-1-C.Scores-ICM-112-Diagnosis and Treatment
DEQuesType value=91 UID vDEjLvG96rz HNQIS-ICM-Feedback-Counseling-240-Effective counseling obs 1
DEQuesType value=91 UID ch6yFpMrAkg
DEQuesType value=91 UID xYTdkMyp3ym
DEQuesType value=91 UID IzCvJ6PLNKj
DEQuesType value=91 UID PljC4yMlWCz
DEQuesType value=91 UID xNjiKzAHTZw
DEQuesType value=91 UID esDpMTDIb1l
DEQuesType value=91 UID fdyLpnXCT6b
DEQuesType value=91 UID nr0ahGkg8tY
DEQuesType value=91 UID tZ50MRD0kiI
DEQuesType value=91 UID vfLDLCnNwIj
DEQuesType value=91 UID gDK0GRWVvHF
DEQuesType value=91 UID cNpTZYL1yQy
DEQuesType value=91 UID ZEQNgrf8pxq
DEQuesType value=91 UID fCBbs4ekGcC
DEQuesType value=91 UID nwoam81M6AU
DEQuesType value=91 UID i7oKXy0pLLV
DEQuesType value=92 UID wu4yiGgpld4 HNQIS-SF-1-C.Scores-CC-500-Cervical Cancer-Cryotherapy

**Comment by josemp10** [comment]
@idelcano, not all answers in our app are optionsets in DHIS2. For instance
only DROPDOWN_LIST, RADIOBUTTON_VERTICAL, and RADIOBUTTON_HORIZONTAL
'Question_Type' are an optionset. 'Label', 'Positive Integer', 'Date',
'Text', and 'Long Text' do not have option sets.

You may remember that optionsets represent just a set of options
("Male"/"Female"), ("Yes"/"no"), etc.

About the question.order... different questions in different tabs may have
the same value for question.order. So you don't need to add the
programstagedataelement.set_order, but keep the question.order with the
vaue presented in the attribute.

**Comment by idelcano** [comment]
I detect a bug(app crash) entering in CompositeScores only in api16
#599

**Comment by idelcano** [comment]
The crash on feedbackActivity was solved.

Unsolved:
The match question of two questions with same factor  not change the questionrelation idquestion with operation(0) to yes.
