### ISSUE TITLE
Investigate Compositescore is saved as question kR94QfYAUUv

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/malariapp#593]
CompositeScore is saved as Question.

https://hnqis.psi-mis.org/api/dataElements/kR94QfYAUUv
is saved as question in our db

**Comment by ifoche** [comment]
my guess is that DEQuestType is badly set in the server side. If you look at the value for that dataElement, it is 2. Check it out in other valid CS, and you'll see that it's 93. Examples:
[this](https://hnqis.psi-mis.org/api/dataElements/Jn8YspI9Pq8), [this](https://hnqis.psi-mis.org/api/dataElements/v0OP0gV4Kdp) or [this](https://hnqis.psi-mis.org/api/dataElements/S3QQdRoto6O).
 @josemp10 does it makes sense for you?

**Comment by josemp10** [comment]
Yes, you are right.

Checking with the content team for HNQIS and let you know (I think it
should be marked with a '93' value yes)

**Comment by josemp10** [comment]
Yes, it is confirmed. It is a compositescore. It has been  changed in the
server..

**Comment by ifoche** [comment]
Thank you very much @josemp10, @idelcano, can you check that now it works?

**Comment by idelcano** [comment]
It works but is saved without order field in our database. I will investigate why. And it still having header(i think the others composite scores dont have).
