### ISSUE TITLE
Create cancel button in the pull_metadata

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/malariapp#596]

**Comment by ifoche** [comment]
@idelcano just to let you know, I'm about to merge visitors_try into development branch, so whenever you finish with this branch, before starting the next task, please move to that branch. Thank you!

**Comment by idelcano** [comment]
This issue is taking me a lot of time.. i was testing all the options and combinations and trying to understand the dhis bus.

I am having two crash if we have this conditions...
1. First pull. Works ok.
2. Second pull (in pull metadata with/without sending surveys or pull again after cancell) Works ok.

3. Before second pull finish.
     3.a Presh in start Assatment( create new survey).
      3.b Third pull without restart the application, or

3.a When i press in Start Assatment, i have a crash caused by Foreing Key failed in the survey, but only first time!:
Survey{id=0, tabGroup=TabGroup{id_tab_group=5, name='KE HNQIS FP', uid='zOD4Z1WK0jg'}, orgUnit=OrgUnit{id=3, uid='QS7sK8XzdQc', name='KE - HNQIS SF pilot test facility 1', orgUnit='null', orgUnitLevel='OrgUnit{id=3, name='Zone'}'}, user=User{id=2, uid='Abm2D2BXUdE', name='Ignacio Foche Perez'}, eventDate=Wed Dec 02 00:14:19 GMT+00:00 2015, completionDate=Wed Dec 02 00:14:19 GMT+00:00 2015, status=0}

3.b I get this second crash, when i pull metadata with o without push surveys.

I force to use the postfinish method  after push, and after pull, and i get this exception:

retrofit.client.Response org.hisp.dhis.android.sdk.network.DhisApi.postEvent(org.hisp.dhis.android.sdk.persistence.models.Event)' on a null object reference
org.hisp.dhis.android.sdk.controllers.tracker.TrackerDataSender.postEvent(TrackerDataSender.java:123)

**Comment by idelcano** [comment]
Refresh the user in Session fixed this problems. 
(I think the user in Session not exist in the second pull, becouse the user had diferent id).
3.a solved.
3.b i can´t reproduce it again after 3.a was solved.

@ifoche 
i think it´s all right now. Anyway is little hard to try all the combinations.

**Comment by idelcano** [comment]
@ifoche 
I can´t stop the DHIS2 thread. I don´t know if it is possible but i can´t it. If i cancell  in the metadatarefresh  and i force go to loginActivity, the DHIS2 thread  needs about 1 minute to finish...
After the metadatarefresh i moved the checks and it is in LoginActivity in a moment.

**Comment by ifoche** [comment]
Ok @idelcano. Is it already uploaded to the repo? Would you consider the
task as finished? I mean, have you cleaned the code?

**Comment by idelcano** [comment]
I will push it in a flew mins(some changes lite change te button to our
custombutton, and more checks)

**Comment by idelcano** [comment]
It is ready!

2015-12-04 14:40 GMT+01:00 Ignacio del Cano Costa <ignaciodelcano@gmail.com>
:

> I will push it in a flew mins(some changes lite change te button to our
> custombutton, and more checks)
>
> El vie., 4 de diciembre de 2015 14:31, Ignacio Foche <

**Comment by ifoche** [comment]
Can you give a look also to the appearance of the button? last time a saw
it it seemed to need some design efforts

**Comment by idelcano** [comment]
What kind of design efforts? color?text?size and shape of the button? all of them?
The difference between this button and other buttons is the color of the  layout background.

About the position: 
I was reading google guidelines design. And i added the button at right corner at buttom. 
About the colors:
i used the login colors and text font. 
I´m not sure what is better, if Background white and text blue(looks good), background bluelight and text blue, background blue and text bluelight/white...

**Comment by ifoche** [comment]
I was thinking more in giving some padding to the button (text is very close to the button border) and margin (button is very close to the screen border) and maybe uploading different images (one for the button not pressed, another for the button when it's pressed...) and doing as we did with checkboxes. However, the most important thing is the padding in my opinion (so please don't get stuck too much time adding the pressed/not pressed image logic).
