### ISSUE TITLE
mocked org unit level breaks create survey GUI

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#611]

**Comment by ifoche** [comment]
When you create a new survey there are 2 dropdowns:
Zone:
----DROPDOWN----
Survey:
----DROPDOWN----

The first one, is not showing the "Zone" title. This is (my guess) because it is taking that title from the org unit level and, as we've mocked that when translating to an empty string, that is what we see. We should change that mocked empty string by "Zone" in order to see that in that title.

**Comment by idelcano** [comment]
I create the R.string.create_info_zone  for get the zone name in all org_unit_levels.

**Comment by idelcano** [comment]
And i removed the compositeScoreHierarchicalCode==null temporal fix(jose upload the compositeScore with null hierarchical code)
