### ISSUE TITLE
Migrate all pictureapp-specific components to malariapp

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#618]

**Comment by ifoche** [comment]
- Image layout for 2, 3, 4, 5 and 6 images (with DB modification as well)
- Numeric picker
- Telephone with format validation

**Comment by ifoche** [comment]
Keep this modification in you own branch, do not merge this branch to development

**Comment by idelcano** [comment]
@ifoche should do i  this issue in a new branch from development branch, or from visitors_try?

**Comment by ifoche** [comment]
@idelcano please create it from development (if you've already done it from visitors_try don't worry, the important thing it not to merge to development again when you finish)

**Comment by idelcano** [comment]
Ok! thx

**Comment by idelcano** [comment]
I am having  some crash... if i merge the last development (i think the plan changes was not finish and crash for example the monitor, all of the crash was related with data). 
I think is not heavy problem and i don´t know if i need merge it at this moment.


All its working at this point. 
In Utils.ispicturequestion(), the application inits and/or get the sharedPreference ispictureapp, and use that for select the difference way in some places.(it has 86 usages at this point, a lot of little differences in layout, i was trying to remove the differences without alter the logic and result)

I will comment the Push background in his chart now.

**Comment by ifoche** [comment]
@idelcano has made the migration of the pictureapp components. I'm going to try to replicate pictureapp using his branch, so whenever we merge this branch, we will have a new variant for pictureapp
