### ISSUE TITLE
Migrate background push from pictureapp

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#619]

**Comment by ifoche** [comment]
keep this branch without merging it to development. This will be for R14

**Comment by idelcano** [comment]
All working, in pictureapp questions.
The malariapp question is not sent with the alarmservice of pictureapp at this point(i am having doubts at this time if i need do it in this chart).

Only two things.
In dev server the response is a error:

Example:
<html><head><title>Apache Tomcat/7.0.54 - Error report</title><style></style> </head><body><h1>HTTP Status 500 - Request processing failed; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet</h1><HR size="1" noshade="noshade"><p><b>type</b> Exception report</p><p><b>message</b> <u>Request processing failed; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet</u></p><p><b>description</b> <u>The server encountered an internal error that prevented it from fulfilling this request.</u></p><p><b>exception</b> <pre>org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet

"HTTP Status 500 - Request processing failed; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet"

"Request processing failed; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet"

"org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet"



In the other server is not imported/updated becouse the program/org unit is not valid, but works...


Example:

prepareDataElements result: {"program":"vLTSa8wPqQ8","orgUnit":"QS7sK8XzdQc","eventDate":"2015-12-16","status":"COMPLETED","coordinate":{"latitude":null,"longitude":null},"dataValues":[{"dataElement":"OEdLEjF6Z8p","value":"អវិជ្ជមាន"},{"dataElement":"RuNZUhiAmlv","value":"###15555215554###000000000000000###89014103211118510720"}]}

parseResponse: {"httpStatus":"OK","httpStatusCode":200,"status":"OK","message":"Import was successful.","response":{"responseType":"ImportSummaries","imported":0,"updated":0,"ignored":0,"importSummaries":[{"responseType":"ImportSummary","status":"ERROR","description":"Program is not assigned to this organisation unit","importCount":{"imported":0,"updated":0,"ignored":0,"deleted":0}}]}}


Other thing.
I did refactor the PushClient class and i did create the PrepareData class... becouse the PushClient had 1000+ lines, and i think is necesary.

**Comment by ifoche** [comment]
@idelcano, have you already checked that the server error response doesn't have anything to do with your PushClient refactor? I mean, do you get that exact message using development branch?

**Comment by idelcano** [comment]
I checked changing the server. The development branch not have the pictureapp background push.
And i am sending the same json.
The dev server was not changed?

**Comment by ifoche** [comment]
@idelcano, I think the server changed in the last version of picture app, maybe you're pushing to an old server that is no longer being used? If I'm not bad, they're now using https://www.psi-mis.org, but I think that is production server. Maybe @adrianq can confirm which is the development server @idelcano can use to check that the background push is working

**Comment by idelcano** [comment]
No. I am using our server(without .dev). It fails in the valid  org unit
(its logic). But in the dev server, the response in the server is a crash
of the server reading  the resultset (I dont know more..). Im not in the
computer at this moment, i Will update the comment with the url  of the
severs  (@ifoche you tell us in the chat).

**Comment by ifoche** [comment]
Ok, I think I'm not properly understanding you, so yes, maybe it is better talk directly so you can explain me this better.
