### ISSUE TITLE
Sent surveys list is only showing last survey

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#632]

**Comment by ifoche** [comment]
If we have for example 3 programs (IMCI, family planning and HIV) and we send a survey for each one, we're seeing only the last one, but we should see the last one for each program.

**Comment by idelcano** [comment]
@ifoche Ok, for be sure before merge: 

We needs filter the last survey from program, or from org unit, or for program and org unit?
Before merge is only filtered by org Unit.
I understood I need filter by program+org unit. In this case we can have 
test facility1 IMCI
test facility2 IMCI

test facility1 family planing
test facility2 famili planing

test facility1 HIV
test facility2 HIV

its correct?

other options:
Filtering only for program

test facilityX IMCI
test facilityX family planing
test facilityX HIV

Filtering by org_unti(actual)
test facility1 X
test facility2 X

**Comment by ifoche** [comment]
Hi @idelcano, you undertood it perfectly. It is the 1st option, so distinct OrgUnit + distinct program. You would have
OrgUnit1:
 - Last survey for program IMCI
 - Last survey for program family planning
 - Last survey for program HIV
OrgUnit2:
 - Last survey for program IMCI
 - Last survey for program family planning
 - Last survey for program HIV

and so on...
