### ISSUE TITLE
General Layout Modifications

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#635]

**Comment by ifoche** [comment]
- [ ] Tabs Layout with the footer area
- [ ] Include designed icons in the layouts - PSI to provide file in format and size specified by EST
- [ ] Implement tab loading in background 
- [ ] Move each fragment to its tab
- [ ] Separate sent surveys fragment from monitor UI logic
- [ ] New graphic design specs, using PSI design specs

**Comment by ifoche** [comment]
![assess_tab](https://cloud.githubusercontent.com/assets/10931645/11702167/c9895412-9ed4-11e5-8ad1-1563c3120847.png)

**Comment by idelcano** [comment]
The first step is done.
 
 -Tabs Layout with the footer area
-Include designed icons in the layouts (cut them from PDF)
-Move each fragment to its tab

@ifoche
What do you mean with : " Implement tab loading in background "
Other question: 
You show different order(plan assess improve and monitor) than the order in the pdf (assess improve plan and monitor) , what is the correct order?


@ivanarrizabalaga
You can pull the branch: 
https://github.com/EyeSeeTea/malariapp/tree/general_layout_modifications

and you can add the plan in...
Layout:
https://github.com/EyeSeeTea/malariapp/blob/general_layout_modifications/app/src/main/res/layout/tab_dashboard.xml#L61
or 
Java:
https://github.com/EyeSeeTea/malariapp/blob/general_layout_modifications/app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java#L99
(If you need you can add a new activity for the "plan" tab).

**Comment by ifoche** [comment]
@idelcano, sorry for the delay, I had forgotten about this issue. I answer your questions:

- With loading in background I mean that the UI shouldn't remain frozen until every tab is filled. Usually, when you build a tabHost arch, all tabs are loaded before the user gets the control of the interface. Well, if that's our case, and you find that we're being frozen too much time loading before the user can interact with the UI, then we would need to launch the jobs that can be launched in background using services, to let the UI be usable. 

- The tab order is the one in principle, the one in the image I pasted, this is
   1 Planning 
   1 Assess
   1 Improve
   1 Monitor

However, they're still deciding it, and pdf is just a draft, so it can change in the future. For us, that doesn't implies too much, because that would be just changing the order in an xml.

**Comment by idelcano** [comment]
I understood! thanks @ifoche.
I updated the branch
@ivanarrizabalaga if you need do something when the Plan tab is select: https://github.com/EyeSeeTea/malariapp/blob/general_layout_modifications/app/src/main/java/org/eyeseetea/malariacare/DashboardActivity.java#L123

**Comment by idelcano** [comment]
I think the backgraund loading it s not needed at this moment. 

I checked in a real device and in a emulator and the movil. 
Only when you click in the monitor tab, and the monitor is rendering the stats looks little strange(but is not tab problem, is the normal load), but you can use the UI the application is not frezed.. 

About the UI, at this momment the UI: 
![screen](https://cloud.githubusercontent.com/assets/5302538/11726938/45375562-9f81-11e5-81ba-761f70382737.png)

if you want i can cut best the icons, or is best wait for the real icons?

I think is finish, can i PR in development?
thanks @ifoche .

**Comment by ifoche** [comment]
Hi @idelcano. Yes, it looks like everything's done. Thanks for your work, I'll wait for your PR

**Comment by ifoche** [comment]
Just one thing, can you remove "line3, line5, etc from the actionbar?"
