### ISSUE TITLE
Assess Tab

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#636]

**Comment by ifoche** [comment]
![assess_tab](https://cloud.githubusercontent.com/assets/10931645/11702177/df2e290a-9ed4-11e5-9228-a18a575de148.png)

**Comment by ifoche** [comment]
- [ ] Move feedback "view feedback" option from send dialog to a new dialog after send. At this moment, when you long press, it allows you to cancel / send / view feedback. It must disappear from there, and after send is done (or survey set as completed), launch a new dialog to ask the user if (s)he wants to see the feedback
- [ ] Remove from the list surveys whose status is COMPLETE

**Comment by idelcano** [comment]
At this point, a survey with status==completed is not in the Assess but is not sent 
(I think it is other issue). 
We talked about it in the Meeting. but i dont take note and i´m not sure, i worked in the the issue comment.

**Comment by ifoche** [comment]
@idelcano I'm not sure to properly understand what you say. Assess must contain only those surveys whose status is COMPLETED or SENT. But be careful, don't make this filter by selecting those who are not IN_PROGRESS, because in his work, @ivanarrizabalaga is going to introduce a new status for surveys for plannification of future surveys, and you may get them. I'm going to look at the PR and I'll tell you there if I find anything like that there.

**Comment by idelcano** [comment]
Yes it is correct i understood. I filtered  if is sent  or completed.  But
in this momment the completed was  always  unsent. And they shows with
score 0%(becouse the score is calculated in push). I calculate the score if
the status is upload (easy  to revert ).
