### ISSUE TITLE
Compulsory Questions

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#641]

**Comment by ifoche** [comment]
- [ ] Introduce a way to mark a question as compulsory
- [ ] Modify score calculation to take into account compulsory questions and answered non-compulsory questions
- [ ] When exiting, if every compulsory question have been answered ask the user "Would you like to complete this survey?" with the answers "Complete | Continue Later". If complete is answered then "Are you sure? This action cannot be undone and you will no longer be able to edit or delete this survey" with "OK | Cancel" possibilities. On complete, then next assessment date would be calculated.

**Comment by ifoche** [comment]
@ivanarrizabalaga, apparently we're having problems with the development server, but anyway, @josemp10 has already set the compulsory field for the DataElements:
- https://hnqis-dev.psi-mis.org/api/dataElements/Op14xNMJi14
- https://hnqis-dev.psi-mis.org/api/dataElements/YtNPDDGkCqK

So I imagine that you should get the compulsory field set to true for the compulsory field in their ProgramStageDataElement object. Can you verify it and tell us if you find any problem?

Thank you

**Comment by ivanarrizabalaga** [comment]
@ifoche, 
it works! 

'Diagnosis 1 based on supervisor&#39;s observation' and  'Treatment 1 administered'
are the only required questions so far, :D.

**Comment by ifoche** [comment]
Brilliant! Thank you really.

**Comment by idelcano** [comment]
@ifoche i had some question.

In the unsentfragment, if a survey had one or more compulsory question, the % of completed is calculated with the compulsory questions. (done and easy)

But i am confused about the scores, in the sentfragment, and in feedback.
In sentfragment we can look the total score. 

I need use the same logic than the % completed of unsentfragment? 
If in a survey, exists one or more compulsory question, i need ignore the score of the others and calculate the score only of the compulsory questions?

And, in the sentfragment we look the total survey score. But in the feedback we can look other scores like by tab, i need do the same in the feedback scores(tabscore, and header score)?

**Comment by ifoche** [comment]
@idelcano. I wouldn't touch the score, as it depends on the composite scores. In principle I would say that the survey creator is in charge of not adding optional questions to composite scores, so I think that it's not our business... At this stage, I would say that it can remain untouched. If we find later any bad implications of that, we will come back to this.

**Comment by idelcano** [comment]
@ifoche 
I am not sure to understand this point:
"Modify score calculation to take into account compulsory questions and answered non-compulsory questions"
Is It talking about the % of progress in unsentfragment?
I add a column in question for compulsory, the logic of score is not affected.
If i am correct the issue is finish(i only will review a bit)

**Comment by ifoche** [comment]
Yes, I think you've finished it. The only score that I think that must be affected (if I'm not bad) is the completion percentage. Please, make the PR after refactoring the code as much as you can. Thanks!

**Comment by ifoche** [comment]
ah! of course, don't forget to add the column you added in the Table Migration

**Comment by idelcano** [comment]
ok! thanks @ifoche i will do the PR in the next hours (i'm going to eat)
