### ISSUE TITLE
Completed survey workflow

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#643]

**Comment by ifoche** [comment]
Instead of sending a survey, now the user will be asked to "mark as completed", and that will be sent in background

**Comment by idelcano** [comment]
take a look in the pull of metadata flow. And  removing some elements related to  #658

**Comment by idelcano** [comment]
The reloadDashboard action(in surveyservice) is getting not working ok with the unsentsurveys. Becouse it is getting the unsentsurveys and the complete surveys too.

**Comment by idelcano** [comment]
1. Survey state places:
Plan Planfragment SURVEY_IN_PROGRESS / SURVEY_PLANNED(If not exist is generated from last sent survey for OrgUnit/Program)
Assses UnsentFragment SURVEY_IN_PROGRESS
Improve SURVEY_COMPLETED/SURVEY_SENT
Monitor SURVEY_COMPLETED/SURVEY_SENT

2. Survey posible states:

SURVEY_PLANNED
this state is seted creating new survey getting the last sent survey when a survey is sent or removed.
(Plans a new survey according to the last surveys that has been sent for each combo orgunit + program)
 

SURVEY_IN_PROGRESS
this state is seted in Plan tab, or createSurveyFragment. And it come from SURVEY_PLANNED

SURVEY_COMPLETED
This state is seted in: inunsentfragment. And it come from a SURVEY_IN_PROGRESS

SURVEY_SENT
This state is seted in : background push: And it come from a SURVEY_COMPLETED

SURVEY_HIDE
Not used at this moment(pictureapp feature).

3. Survey status Workflow:
From - fragment - To - initialState - endState

Plan - planfragment -> SurveyFragment - SURVEY_PLANNED -> SURVEY_IN_PROGRESS  V
Plan - planfragment -> SurveyFragment - SURVEY_IN_PROGRESS -> SURVEY_IN_PROGRESS  V



Assess - SurveyFragment -> unsentfragment - SURVEY_IN_PROGRESS -> SURVEY_IN_PROGRESS(save) V
Assess - unsentfragment -> Action(edit)->SurveyFragment- SURVEY_IN_PROGRESS -> (not change) V
Assess - unsentfragment -> Action(mark as completed) - SURVEY_IN_PROGRESS -> SURVEY_COMPLETED(save) V
Assess - unsentfragment -> Action(Deleted) - SURVEY_IN_PROGRESS -> new survey with SURVEY_PLANNED state and is set in never assessed(save) V

Assess - createSurveyFragment -> SurveyFragment - SURVEY_PLANNED -> SURVEY_IN_PROGRESS(save) V
Assess - SurveyFragment -> Exit in complete compulsory survey and choose set as completed - SURVEY_IN_PROGRESS -> SURVEY_COMPLETED(save) V
Assess - SurveyFragment -> Normal exit(change tab/button back) - SURVEY_IN_PROGRESS -> SURVEY_IN_PROGRESS(save) V
Assess - SurveyFragment -> exit aplication - SURVEY_IN_PROGRESS -> SURVEY_IN_PROGRESS(save) V 

Background-  (mark as completed in unsentfragment)->All- SURVEY_COMPLETED -> SURVEY_SENT  V

All -> reloadDashboard/Converttosdk(sending surveys) - planFragment - !SURVEY_IN_PROGRESS || !SURVEY_PLANNED -> new survey SURVEY_PLANNED(in ServiceIntent reloadDashboard) V

**Comment by idelcano** [comment]
I did this document https://docs.google.com/document/d/1SA9TLO3nxgRSokvwP_0tj6epDFXtZE9HccGD5XdwIyw/edit?usp=sharing

**Comment by ifoche** [comment]
Review double creation of a survey by the planning

**Comment by idelcano** [comment]
@ifoche Here is the problem:
-When we sent a survey, it is set as completed.
-The survey list is reloaded.
-When a survey is not in planning/progress, the SurveyPlanned creates a new In_planning survey..

-When the survey is sent in background, the SurveyPlanned create a new planned survey from the sent survey.(It is the duplicated survey, but it have different data, like a mainScore and ScheduledDate).

I think the solution is move the creation of the new planned survey from "ConvertToSdkVisitor" method(it is called when a survey is sent) to method setCompleteSurveyState from Survey. (It works and i think it not change the behavior).

**Comment by ifoche** [comment]
@idelcano did you already implemented it? If you didn't, please go ahead, because it makes sense. BTW thank you for deeply analysing the problem

**Comment by ifoche** [comment]
Ok, I've just seen your PR, thanks
