### ISSUE TITLE
Upgrade SDK to 2.22 DHIS server (2.21 SDK branch)

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#644]

**Comment by ifoche** [comment]
Apparently, SDK (and DHIS2) developers are convinced that 2.21 SDK branch will be compatible with 2.22 DHIS2 servers. However, as code is at this moment adapted to 2.20 branch, we will have to 
- [ ] Migrate it to 2.21 branch
- [ ] Check its compatibility with 2.22 DHIS2 server

**Comment by ivanarrizabalaga** [comment]
Server url:

https://hnqis-staging.psi-mis.org

**Comment by ivanarrizabalaga** [comment]
Looks like I manage to make it work in staging but it is not working completely in other envs:

| Env            | Pull                                                                                            | Push                                                                                                                                      |
|----------------|-------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------|
| 2.21 - staging | ok                                                                                              | ok                                                                                                                                        |
| 2.20 - dev     | ok                                                                                              | HTTP Status 500 - Request processing failed; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet |
| 2.20 - pro     | HTTP Status 500 - Request processing failed; nested exception is java.lang.NullPointerException |                                                                                                                                           |

**Comment by ivanarrizabalaga** [comment]
Pulling with my credentials (iarrizabalaga) from PRO returns an error 500 (I remember that something like this happened in the past):

https://hnqis.psi-mis.org/api/me/programs/?fields=%5B%3Aall%5D -> 500 NullPointerException

**Comment by ifoche** [comment]
I suppose that it is not that easy but...you're pulling/pushing dev and pro using 2.20 SDK branch and staging using the 2.21 SDK branch, right? If that's the case, @josemp10, can you help @ivanarrizabalaga with this?

**Comment by ivanarrizabalaga** [comment]
@josemp10, forget about it :P

**Comment by ivanarrizabalaga** [comment]
Our module requires **guava 18** since it uses *Booleans.countTrue(upper);* which is not present in **guava-collections**.

Options:

a) Change this method by our own code (a simple loop) + using guava-collections r03 everywhere.

b) Keep on using guava 18 (the 'right' one) + add a tip to our shared document (changing collections x 18 in sdk/app/build.gradle)

**Comment by ifoche** [comment]
Ok, I think that b) would be the best then, adding the tip to the TIPS document. Later, whenever the DBFlow 3.0 is released as a compiled library and the Oslo team change it in their code, and we don't need to edit the SDK build.gradle by hand anymore, we will talk again about it. Bug for the moment...yet another tip to configure the environment :).
