### ISSUE TITLE
Remove viewfeedback variable

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/malariapp#658]
Call feedback from ProgressActivity with a intent
from
https://github.com/EyeSeeTea/malariapp/pull/656/files#diff-a24fd608ae37e59f15d857b5438ce339R300 
to

https://github.com/EyeSeeTea/malariapp/pull/656/files#diff-d711350d2ab5677ab23b095a030e15a0R67

thanks!

**Comment by idelcano** [comment]
At this momment, it is not used.
@ifoche the variable viewfeedback is only used when you push  a single push, 
But the application is pushing the surveys in background, and this code is never used now.

**Comment by ifoche** [comment]
ok, I see. Can you refactor that code and remove the unused part?
