### ISSUE TITLE
Find excell script to manage dev server

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#665]

**Comment by josemp10** [comment]
This is the script we were using (with data of Nigeria):
https://drive.google.com/open?id=1TBwWOI9LFaIpxEZ-7-EDzsW_TULSrq-KC3eOxW55HDU

Please note:

1) The script should generate a xml file (menu: XML -> To File), and you
need to import that file in the dhis2 instance (in case you want to
introduce new/update dataelements). Please, remember to use just the dev
server for testing. hnqis-dev . The others (hnqis, hnqis-staging) need to
stay as they are.

2) The script works, but it may contain some bugs. James may be still
working on the script.

**Comment by ifoche** [comment]
Script moved to a new folder called "DHIS2" in this project folder
