### ISSUE TITLE
show survey activity from assess tab

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#672]

**Comment by ifoche** [comment]
At this moment, when the user is in Assess tab and click to edit a survey, the DashboardActivity is closed and SurveyActivity is opened. What is needed is to embed the SurveyActivity logic into the DashboardActivity as a fragment. In my opinion that would imply:
- Migrate SurveyActivity to a new SurveyFragment with the same logic when possible.
- Change what in SurveyActivity is the "exit" order to show the UnsentFragment
- Take into account that any tab change could imply exiting from a survey, alert dialogs may be necessary in that case

**Comment by ifoche** [comment]
To give you a better idea of the desired behaviour, take look at this image:

![assess_tab_2](https://cloud.githubusercontent.com/assets/10931645/12091732/11a0f8d0-b2f9-11e5-8f10-bb6b6b21040e.png)

**Comment by ifoche** [comment]
For the moment, forget about the upper tabs, just embed the fragment replacement of SurveyActivity into the DashboardActivity

**Comment by idelcano** [comment]
@ifoche about this point:
-Take into account that any tab change could imply exiting from a survey, alert dialogs may be necessary in that case


At this moment, if you are editing a survey, and you go to other tab, when you come back you come back the survey is in the same state.

Is necesary close the survey if you change of tab anyway?

should i copy the funcionality of backpress(ask, and save and close the survey)?

**Comment by ifoche** [comment]
@idelcano mmm, well, leave it like that for the moment and let's see client's feedback. We'll ask him his opinion. Thank you

**Comment by idelcano** [comment]
@ifoche sorry, i think it is necesary finally... 
becouse when i enter in a feedbackactivity, the survey is closed and saved without ask the user. The data is not lost, but  the user not confirm the action of finish survey.

**Comment by ifoche** [comment]
but, isn't that because feedback is a new activity and you're moving into it? remember that your next task is to move also the feedback activity into a fragment...so that is not going to happen whenever that task is done...isn't it?

**Comment by idelcano** [comment]
@ifoche sorry  for the delay. Yes its true, but i was thinking about it and i´m not sure( the SurveyActivity and the FeedbackActivity get the Survey from Session), I think it could cause problems.

I was thinking it, and did the feedbackactivity, i will check., i am working in feedbackfragment.
Can i upload this issue merge with the feedbackfragment issue?
Anyway is not problem, i can do a cherry pick and upload the feedbackfragment in other independent branch. But i want check the code with all the fragments.

**Comment by ifoche** [comment]
Hi @idelcano. Ok, for the moment, please don't introduce the survey exit check, we'll wait for the feedback to be finished and integrated with planning and everything. If you want to test both fragments together, please merge the feeback branch into the assess branch (or viceversa). The git history will be easier to understand in that way.
