### ISSUE TITLE
change graphs for monitor tab

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#691]

**Comment by ifoche** [comment]
Just to give you an idea about where to touch if you try to avoid the score bubbles to be circles and not ovals, the files that the other day I was touching were:

app/src/main/assets/dashboard/dashboard.html

...concretely the part of the CSS for the classes td.[green|amber|red]circle, and the file...

app/src/main/assets/dashboard/table.facilities.js

...concretely the for loop that builds each row of the table with the code...

```
row=row+"<td "+buildColorXScore(iValue)+">"+buildCellXScore(iValue)+"</td>";
```

Another think that I tried was to use an .xml layout instead of a drawable for printing the circle shape. Concretely, a combination like this (example for the green circle):

app/src/main/res/layout/circle_shape_green.xml
```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="fill_parent"
    android:layout_height="fill_parent"
    android:orientation="vertical">
    <ImageView
        android:src="@drawable/circle_shape_green"
        android:layout_width="wrap_content"
        android:layout_height="fill_parent"
        android:scaleType="fitCenter"/>
</LinearLayout>
```

app/src/main/res/drawable/circle_shape_green.xml
```
 <shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="oval" >
     <solid android:color="@color/lightGreen" />
     <size android:height="20dp" android:width="20dp"/>
 </shape>
```

The point here is that the scaleType property was suppose to do the trick, but I didn't get it working. I hope you'll be more lucky with this. I suppose you were already aware about all of this, but just in case the time I spent the other day can worth for something, it would be great.

Thanks

**Comment by idelcano** [comment]
@ifoche thanks for your coment, i finally used only css
