### ISSUE TITLE
Create pull tests

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#750]

**Comment by ifoche** [comment]
There must be, server side, a very simple test user permanently there, with static properties just to use it as a GoldStandard.
Test at least:
- [ ] Pull is successful. It downloads the OrgUnits, Attributes, Programs that it must download
- [ ] The translation to our DB is ok. You can see those OrgUnits, Programs and Attributes
- [ ] A communication problem results in an alert message and go back to login
- [ ] If we cancel de pull, it just stops and takes the user to Login 
- [ ] Any server side problem bad configuration (here we can use a different test user if it's needed) is detected in translation time to our DB and shown as an error (alert to the user) and go back to Login

Please, take a deep look to @ivanarrizabalaga push tests in order to keep the same structure and standards

**Comment by idelcano** [comment]
@ifoche some comments:

>  A communication problem results in an alert message and go back to login

Nothing happends when the comunication have problems (I suppose its only is possible when the network lost). The app continue and save only the pulled data.

I think it is a new issue "show a dialog message and control when the application needs stop the conversion and return to logging".
I think if the necesary data is not downloaded the app needs stop conversionfromsdk, show error dialog, and return to loginactivity.


> Any server side problem bad configuration (here we can use a different test user if it's needed) is detected in translation time to our DB and shown as an error (alert to the user) and go back to Login

In this point, if your user or server not exist... you can not login. And if you are logged you can not change this data. Do you think in other case?.
What kind of errors should i check? 
I think the only case  is if the pull is cancelled and the user is null, but is a problem of the first point.

> Pull is successful. It downloads the OrgUnits, Attributes, Programs that it must download

> The translation to our DB is ok. You can see those OrgUnits, Programs and Attributes

I did the OrgUnit Attributes, the other attributes is dependent from other Pojos as header/question..
 I can do the program attribute too(but the branch is not merged).
I ´m not sure if i undertood

Thanks !

**Comment by ifoche** [comment]
> Nothing happends when the comunication have problems (I suppose its only is possible when the network lost). The app continue and save only the pulled data.

> I think it is a new issue "show a dialog message and control when the application needs stop the conversion and return to logging".

> I think if the necesary data is not downloaded the app needs stop conversionfromsdk, show error dialog, and return to loginactivity.

Perfect, this is the goal of the tests, make the problems appear and solve it. If you please can create the issue and take care of it, it would be fine.

> In this point, if your user or server not exist... you can not login. And if you are logged you can not change this data. Do you think in other case?.

> What kind of errors should i check?

> I think the only case is if the pull is cancelled and the user is null, but is a problem of the first point.

Maybe here you can play with the testOK and testFAIL users. testFAIL is authorized to login, but it has no permission to download/push data. That for example is an error we can control. I think it is related to the #24 issue @ivanarrizabalaga created, so here you wouldn't need to create the issue. The problem treated in that issue is that when that exception (the user has no permission to get the data) happens, it is masked by a try/catch and you're not able to realize in the code, that this has happened. So the first thing you would have to do is modify the SDK to return that error and be able to catch it from our code, so we would control that possibility too.

> I did the OrgUnit Attributes, the other attributes is dependent from other Pojos as header/question..

> I can do the program attribute too(but the branch is not merged).

I think you have work enough with the other 2 questions you asked, so whenever you reach this point again, I will probably have merged program attribute branch
