### ISSUE TITLE
Header changes

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#755]

**Comment by ifoche** [comment]
Change the actionbar to use only 2 lines, making the logo bigger and changing the content as shown in the image

![feedback_changes](https://cloud.githubusercontent.com/assets/10931645/12944919/95d1367a-cfea-11e5-9df8-ee6bfef424c0.png)

**Comment by idelcano** [comment]
I was searching how make the logo bigger but i didnt find nothing. And the align is a bit different in diferent screens.

**Comment by ifoche** [comment]
I think that what they need is as simple as generating a logo with a little
bit more pixels in each dimension. Not scaling at all. Did you tried that?

**Comment by idelcano** [comment]
@ifoche it is true! thanks ifoche, i feel stupid.

**Comment by ifoche** [comment]
@idelcano a couple of comments to the new aspect of the header. Could you...
- make the space between logo and the actionbar text a little bit bigger?
- make HNQIS black and bold while the rest remains as-is (if you find it very difficult, please leave it like that)?

![header_feedback](https://cloud.githubusercontent.com/assets/10931645/13064380/7e48b9d0-d452-11e5-8967-3205c8c6ca95.png)
