### ISSUE TITLE
Make eds branch show the different tabs in the same page one on top of the other

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#769]

**Comment by ifoche** [comment]
We could create a setting (not visible to the user, same as the CSV one) to determine if the rendering of the different modules (tabs) must be in the same page or each module in a different tab. To do this it would be fantastic to create a "Module" class and a "Dashboard" class we could use to define the presentation attributes, independently of the content of the fragments. 

In this task, the first objective is to be able, in the "eds" branch, to show every fragment in the same page (as we used to do in R10/R11/R12)

**Comment by idelcano** [comment]
@ifoche some questions.

At this moment i load horizontal or vertical in base at settings value. But with the same style as in R14 (is not 100% finish, i need fix two things).  

But i want ask you...

Do i need replicate the color and style of the layouts to look exactly as R10? 

Do i need "remove" the new features (like compulsory question dialogs or the tab navigation in the survey fragment) ?

And i thinking in how do it with Module and Dashboard class.

I think the Module item with the attributes and the fragment, and the dashboard should have a fragment with the module list and represent it as tabhost or with the linearlayout.

**Comment by ifoche** [comment]
@idelcano I answer your questions:

1) Yes, color and style of R10 must be replicated

2) I would leave them, but with adapting the style to the old colors. 

3) In my imagination

- Dashboard would contain a list of Modules and a property render with the posibilities "horizontal" | "vertical". So vertical would be all the fragments one on top of the other, and horizontal would be each fragment in a different tab.

- Module would contain things like the xml resource of the associated fragment (an integer, if my memory works), the xml of the transition to enter the fragment, the xml of the transition to exit the fragment (maybe fragment-related things should be lists, to be able to represent those modules that have more that one fragment), String for the name of the module...

Probably, when creating the Dashboard Activity, would be a good point to look into the Dashboard/Module classes, and a it would be just close to perfection, if the renderisation of the modules is made using an Adapter...but as I told you before. This is a very high-level (easy to say, but probably difficult to implement) view. So if you want to start with the first prototype without the Dashboard/Module classes, PR the code, and after that, start to refactor the code to implement that idea, that would be perfect.
