### ISSUE TITLE
vertical/horizontal dashboard abstraction

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/malariapp#788]
using Dashboard/Module  as was commented  in #769

**Comment by ivanarrizabalaga** [comment]
https://docs.google.com/document/d/1JeZdHCAC9Kmxy_jKrEGzvndIKHeLOsxuowLyD2Bpl08

**Comment by ivanarrizabalaga** [comment]
Start working from  branch https://github.com/EyeSeeTea/malariapp/tree/dashboard_modules_vertical_horizontal

Using dev-ci server.

**Comment by ivanarrizabalaga** [comment]
@ifoche https://github.com/EyeSeeTea/malariapp/tree/modules_config
The app compiles and runs for both variants(eds, hnqis) BUT the unsent fragment needs to be review since it crashes.

**Comment by ivanarrizabalaga** [comment]
@ifoche, I've just pushed the latest.
