### ISSUE TITLE
UI feedback

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#793]

**Comment by ifoche** [comment]
- [ ] Put a red asterisk in compulsory questions
- [ ] Remove/darken left/right arrows when first/last tab
- [ ] Make the planning pencil icon yellow, so it it's easier to identify in progress surveys
- [ ] Give a little bit more up/down padding to the entries without OU name to make them more clickable
- [ ] Make the margin bigger between the OU and the survey selection dropdowns
- [ ] Make the planning dropdown arrow the same size as in improve tab
- [ ] First sub-row in planning always white background

**Comment by idelcano** [comment]
@ifoche do you like this red asterisk?
![asteriscos](https://cloud.githubusercontent.com/assets/5302538/13401780/d4ab0056-df0d-11e5-80f8-91d7f55d4541.png)
If we can put the red asterisk in the right i need edit all the question .xml to add a new customtextview.

**Comment by ifoche** [comment]
I think is ok, but can you put a little space between the asterisk and the start of the question? (just a little bit)

**Comment by idelcano** [comment]
I use a darkness colors to   easier to identify in progress surveys
It is easy to change for any other color
![buttoncolors](https://cloud.githubusercontent.com/assets/5302538/13406567/86672566-df24-11e5-9aa8-4d9b48e8c384.png)

What do you think? any suggestions?

**Comment by ifoche** [comment]
@idelcano I find it better too but what the client explicitly said was to put a yellow pencil, so it is better if you use the yellow pencil for all the lists and after that let them decide

**Comment by idelcano** [comment]
@ifoche  i uploaded the PR, I used a new color, yellow a litle more dark than normal. I think this color is nice for all planing blocks.

**Comment by ifoche** [comment]
thanks!
