### ISSUE TITLE
Include custom tabs in normal pull

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#794]

**Comment by ifoche** [comment]
@ivanarrizabalaga I sent you an email with the R10 apk for Tanzania, just to let you see that Program "Tanzania checklist" Tab Group "General OTSS" has a custom tab called "Adherence" you can use as a template of how it was working before.

Regarding the server, @josemp10 is creating a new server (apparently it will be in eds-dev.psi-mis.org) with all the metadata for those custom tabs uploaded. Please @josemp10, keep @ivanarrizabalaga informed about that progress, so he can work on it after you finish. 

Thanks both!

**Comment by ifoche** [comment]
@ivanarrizabalaga just a few things about how will be the metadata implemented in the new eds-dev.psi-mis.org server:

- The attributes that define the Row/Column for the custom cells are called "Row" and "Column" with code "DERow" and "DEColumn"
- The row/column numeration start in 1, but row 0 is reserved for the title of the table
- TabGroups are coded in the name of the ProgramStageSection. So you will get ProgramStageSections like TabGroup.Tab where the "." (dot) is the token that split TabGroup and Tab (so we sill need to modify the corresponding visitors section)
- In a custom tab (table), any dataElement not being a label must not show it's form_name, as its going to be simply the answer
- The switch of the Adherence tab, that show/hide the rest of the questions is modeled as a parent-child relationship
- There are questions inside the table whose answers are not the punctuation, but the match between them. At the same time, the result of the match must not be shown in the tab. This is modeled with a new type of question "DEQuestType" called DROPDOWN_LIST_INVISIBLE. As you could imagine, these questions, that are the result of the matching, must not be shown and their answer must be taken into account for their composite scores (if they have). 
- The cells (DEs) for all the columns of a row must have the same size

Please, if something is not clear or you find any problem during the implementation, just give me a call.

Thanks!

**Comment by ifoche** [comment]
@ivanarrizabalaga @idelcano there's a new development server up and running with the EDS data (http://eds-dev.psi-mis.org). I've created users for both (iarrizabalaga and idelcano) and I'll send you pwds in separate mail. You've permissions for the only Programs that Jose has checked for the moment (Malawi ones). Please let me know if you have any problem doing pull/push to/from that server.

Thanks!

**Comment by ifoche** [comment]
@ivanarrizabalaga regarding the questions that we talked about in our last hangouts:
- We have to stop using ProgramStage for TabGroups. Apparently, in DHIS, there are 2 kind of reports:
   - Single Event Without Registration
   - Multiple Stage With Registration

...and we're using the first one. In that kind of report, only 1 ProgramStage can be used in a Program (DHIS doesn't allow multiple ProgramStages). To use Multiple Stage With Registration we would need to use tracker events and change a lot of things, so we're limited by DHIS2 capabilities, and we will have to continue using (just for the moment, we'll change it later) ProgramStageSections to map both TabGroups and Tabs (it's very ugly, I know, after the pilot in Kenya we will have to change it).

- It's ok if we have in hnqis some optioncodes different than their option factor attributes, it's not a mistake, they want it like that. However as you've already seen, in eds-dev server the optioncodes will be like in hnqis-dev-ci server.

**Comment by ivanarrizabalaga** [comment]
@josemp10 It looks like  in **eds-dev** the attribute for Question Type (**RkNBKHl7FcO**) have NO code (null instead of DEQuesType).

It is very important  since this value is used to determine the type of question.

I dont have the rights to change any of this in the server.

**Comment by ifoche** [comment]
@ivanarrizabalaga I've just configurated it. It was not that the only metadata missing. Supervisor, OUProductivityValues & PProductivityFactor Attributes were not present a multiple other attributes didn't have their code configured and even there was an attribute with the code wrong. They're supposed to be fixed now, but please let me know if you find out anything else. 

@josemp10 there's also a new piece of metadata in this server that I don't know why is it there for, it's an attribute called "type of facility".  Do we have to take it into account for anything?

**Comment by ivanarrizabalaga** [comment]
@ifoche There are questions with:

**optionSet** = TG8w4sXTlEB

But there is no optionSet with that ID in the server anymore.
I've checked other servers (https://hnqis-dev-ci.psi-mis.org/api/optionSets?paging=false&fields=*,options[*,attributeValues[*]]) and that UID belongs to the::

**OuiNon (to be removed) (HNQIS)**

There are **482** with this optionset in the server

**Comment by ifoche** [comment]
@josemp10 I'm trying to look at this, but as you can imagine, this is something that you'd fix much quicker than me. Please, can you take care of this as soon as you are available? In the meanwhile I'll try to guess how to do it.

**Comment by josemp10** [comment]
- @ifoche, can you let me know which other attributes didn't have their
codes properly configured? I would like to check that for the EDS server as
well.

- As far as I know, OUProductivityValues & PProductivityFactor Attributes
are only valid for HNQIS. If this is the case they don't have to appear in
the EDS server (what is the 'supervisor' metadata about to? I can not
remember now. Is it only for EDS and not HNQIS?)

- optionSet = TG8w4sXTlEB is a Yes1No0 optionset ->
https://eds-dev.psi-mis.org/api/optionSets/TG8w4sXTlEB

**Comment by ifoche** [comment]
Hi @josemp10 . I thought you knew that code between HNQIS and EDS is essentially following the same scheme. Not providing the minimum metadata needed by the pull will potentially make the app crash. If Productivity is not going to be used in EDS it's something that we cannot guess, we have to assume that pull is the same as in HNQIS, or we will go crazy by including a lot of exceptions. I think that a good point would be to make some kind of metadata document with the scheme that the user is going to have and so we can adapt ourselves to that scheme. However, that's not the main problem here. The OptionSet was the main problem to continue. @ivanarrizabalaga can you confirm that you can now continue, taking into account that there's now an OptionSet with that UID?

**Comment by ivanarrizabalaga** [comment]
That's enough for me to go on.

**Comment by josemp10** [comment]
Ok, I will take care of that metadata document. About the codes, yes, it
may be my fault or that DHIS2 didn't import those values properly. Likely
my fault, but I need to check that. Can you let me  know what other
attribute codes were missing?

I didnt change anything regarding that optionset. As far as I know that
optionset was 'always' there (have you tried to test it before with
https://eds-dev.psi-mis.org/api/optionSets/TG8w4sXTlEB and did you receive
an error?)

**Comment by ivanarrizabalaga** [comment]
Status:

 - [x] Add row/column to question
 - [x] Update ConvertFromSDK to add row/column
 - [x] Turn list of header, questions into a list of header, questionRow, question
 - [x] Update visibility map for questionRow stuff
 - [x] Make table structure visible (AutoTabAdapter.getView())
 - [ ] Make table headers layout beautiful
 - [ ] Init table content rows properly (according to question.output)
 - [ ] Customize switch

**Comment by ifoche** [comment]
@ivanarrizabalaga thank you very much, have a good holidays!

**Comment by ifoche** [comment]
@josemp10 I've told you by mail. OptionSets were probably there but only superusers could see them, they were not available for normal users (like @ivanarrizabalaga). And it's so strange as there were some OptionSets opened to everybody with login and some others with permissions just for superusers. Regarding the attribute codes that were missing, I can't remember exactly which of them. It was like half of them didn't have their code set.

**Comment by ivanarrizabalaga** [comment]
@ifoche Thanks!

The latest: https://github.com/EyeSeeTea/malariapp/tree/custom_tabs

**Comment by ivanarrizabalaga** [comment]
@ifoche, @josemp10  the question by uid m0f4mdp8aXq needs to update its order_pos to 175.

Right now in eds-dev this question (age) and the next one (gender) for the first row of the table1 have the same order which makes both columns switch its places.

**Comment by ivanarrizabalaga** [comment]
Updated Status:

 - [x] Add row/column to question
 - [x] Update ConvertFromSDK to add row/column
 - [x] Turn list of header, questions into a list of header, questionRow, question
 - [x] Update visibility map for questionRow stuff
 - [x] Make table structure visible (AutoTabAdapter.getView())
 - [ ] Background even/odd rows
 - [ ] Complete getColumnView (radios, ..)
 - [ ] Text fields not editable (soft keyboard issue)
 - [ ] Font sizes (@ifoche)
 - [ ] Change question order ( m0f4mdp8aXq -> 175) (@josemp10)

**Comment by ifoche** [comment]
@ivanarrizabalaga I've changed the question order. Can you recheck?

**Comment by ivanarrizabalaga** [comment]
perfect! thanks @ifoche
