### ISSUE TITLE
Set default max events for pull download in 30

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#797]
In both EDS and HNQIS variant

**Comment by idelcano** [comment]
@ifoche can you refresh me what should i do?
I changed the value of initMaxEvents from 200 to 30, but the sdk is downloading more.
I think you talk about this other meeting but i dont remember very good.

**Comment by ifoche** [comment]
Remember that number is the maximum for the pair OU/Program. Are you
getting more than that?

**Comment by idelcano** [comment]
@ifoche Yes It is correct,  it is working, i will do the PR (I only changed the max event limit).
