### ISSUE TITLE
tab switching time very long when planning tab is hidden

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#805]

**Comment by idelcano** [comment]
The problem with the Improve tab is the list. It is more heavy than other tabs.
I find a solution, hide/unhide the layout.
Hide before load the tab, and show after.

Other option... was init in only one program.(one program and one org unit).
i don´t find other way to do it.

I commented the logs too. And it was more fast for me(a bit), but i uncomment for the PR becouse it is not needed with the new show/hide load.

I removed the option "all org units"(we talk about it). 

I think it is not a problem of hide the planning tab, is a problem loading dashboardsentfragment(with planning tab hide or not) becouse is more heavy than others.

I fixed at this moment:
Change tab fast.
I fixed the problem when you hide the planning tab. 
And i hide the option "all org units" and the user need filter by one org unit in this PR.
