### ISSUE TITLE
Fix OrgUnit filter in a default orgUnit and disable "ALL ORGUNITS" option

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#826]

**Comment by ifoche** [comment]
The ALL ORGUNITS must still be there, but not clickable if possible. If it become too complicated, then please tell me why in this issue and take the approach of removing that option.

**Comment by ifoche** [comment]
@idelcano I think this is done but the "ALL ORGUNITS" option has disappeared. I imagine that you kept this task here for that reason, isn't it?

**Comment by idelcano** [comment]
Yes i need review this becouse in this task "The ALL ORGUNITS must still be there, but not clickable if possible.". And I did it before this issue, but I removed this option in the other branch. (I need make the option visible, but not selectable, now is not visible and not selectable)

**Comment by ifoche** [comment]
@idelcano perfect, I leave you then this as the first task. Thank you
