### ISSUE TITLE
Make the size of the header in createSurvey consistent

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#831]

**Comment by ifoche** [comment]
When creating the survey through the old way (not the planning tab) the header that says "Facility/survey" and "%complete" doesn't have the same size than the rest of the headers of the other tabs. They want it with the same size

**Comment by idelcano** [comment]
I have questions.
![headers](https://cloud.githubusercontent.com/assets/5302538/13571471/892ccffc-e475-11e5-8a08-d8181f4497e5.png)

![othersize](https://cloud.githubusercontent.com/assets/5302538/13571626/77f8512e-e476-11e5-9f1a-3e2096c3ef80.png)

What is the header of tab/improve? the real headers(Facility/survey; never assessment..) or the filters?

I think i need make improve and assess header like Never assessed, what do you think?
And, have a problem, in some devices for example, Completion date, take two lines and is more bigger.
I think i will make the headers more bigger, like if it contains two lines. And make all rows(headers) like in planning tab(textsize too). what do you think?

As you can look the assess tab have the same size as improve tab. (Only is not true if the improve tab is deformed by long text)

**Comment by ifoche** [comment]
@idelcano I think you're right, the headers look like consistent but with the exception of the headers of planning that are not similar to the facility/survey headers...but I'm not really sure that changing them would be a good idea. We can start putting problems in low resolution tablets, and we don't want that. Please keep this apart (I'll move it to Backlog) and let me talk it with the rest of the people here.

**Comment by ifoche** [comment]
Ok, we've finally cancelled this task, so don't worry about it anymore
