### ISSUE TITLE
Put a progress bar to make heavy jobs in background

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#84]

**Comment by ivanarrizabalaga** [comment]
hi @EyeSeeTea/developers

**Comment by ifoche** [comment]
See also #96

**Comment by ifoche** [comment]
Rodolfo moved this task to Release 9, so we're not highly stressed with this. If you've not spent too much time yet on it, maybe it is better to move to another task. If you've advanced already and it doesn't worth the pain of stopping and restarting later, just continue.

**Comment by ivanarrizabalaga** [comment]
The places where this needs to be done are:

 -[] Populate after login (already done via AsyncTask)
 -[] Load surveys into Dashboard (done in branch using SurveyService)
 -[] Load Survey details into SurveyActivity (not done yet)

**Comment by ivanarrizabalaga** [comment]
@EyeSeaTea/developers
The use of a background service to speed up surveys is already done BUT in order to make it better we should complete #226.
