### ISSUE TITLE
Dates used in monitoring charts are wrong

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#846]

**Comment by idelcano** [comment]
I think is not necesary, but @ifoche only for refresh your memory. Do you remember #846 ? the data was showing without the correct mainscores. Maybe it is a related task.

**Comment by ifoche** [comment]
@idelcano I'm looking at the DB. The completion dates are definitively wrong, while the other dates are right, and in the monitor chart apparently we're seeing the completion dates. So yes, it's necessary. The composites  scores-related task that you're talking about was just that the CS 0 was not the root of the CS tree server side, and as long as it was being used to determine the main score of the survey in the translation into our DB, it was failing saying 0% (so class C score).
