### ISSUE TITLE
Tests for new list adapters

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/malariapp#847]

**Comment by ivanarrizabalaga** [comment]
@ifoche, so far we were using testOK as the user with the right credentials (1 orgunit, 1 program).

If we want to test the behaviour of adapters with a bunch of surveys we need a user with access to more programs or orgunits. What do you think?

**Comment by ifoche** [comment]
@ivanarrizabalaga I've just added a second OU to the testOK user role, and 2 more programs (Cervical Cancer and IMCI), so you would be able to have 6 different combinations. Is that enough for making the test? do you want another program/OU? Can you please verify that the rest of the tests have not been affected by the role change and continue working? Thank you very much

**Comment by ivanarrizabalaga** [comment]
@ifoche there were 5 tests that failed after changing the user rights, now there are only 2 .. . I'm solving this.
