### ISSUE TITLE
Use the patch method in EDS code

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#880]

**Comment by ifoche** [comment]
- [ ] Modify the create survey to select between "Create a new survey" and "Patch an existing one"
- [ ] Introduce a function to search for the last event matching that OU/Program and get its UUID
- [ ] Use the patch function with that event UUID

**Comment by idelcano** [comment]
@ifoche i have two problems.


1 The eventDate is truncated  in the server.

I think the eventDate is truncated sometimes in server side. The other option is that date was truncated by the sdk or by our app and saved with American format in the server.



The put method is working and i did the dialogs to work.
I was problems when i uninstall the program and logging with other user, but removing the "maxEvent limit"  the problem disappeared .

For example:
https://hnqis-dev-ci.psi-mis.org/api/events/dhhG4D1DtLr

That event was created by ifoche, updated by ifoche, and it was updated again by idelcano.

At this moment the "sortedBy" value is only saving the first time than a user save this datavalue. But we can edit all the datavalues.

I will try to download the last Event by eventDate this night.
If you want we can talk when you want.

**Comment by idelcano** [comment]
Sorry @ifoche I modified my last comment, you need read it in the web, thanks.

**Comment by ifoche** [comment]
@idelcano we'll talk about it in our meeting today, but:
 1. Please create a card for the date ascendant order of the pull. That need to be clearly reviewed and it has max priority. 
 2. The date truncation we can leave it with low priority, as we have the workaround if we cannot find another solution of putting a text DE type (however, I'm sure you'll find out where it is being truncated)

The maxEvent limit problem with the user seems to be related to the ascendant order of the pull so lets wait for you to review that before talking about it

**Comment by idelcano** [comment]
I was working in the third step, after hard work to 
create the uploadevent function in sdk (like james said in his mail).

My solution was remove all the event.datavalues and after set the new values.
I am working in sent the datavalues for a not pulled event in the local data now.

But i sent one event with the POST method in a mistake. 
And i look:

"httpStatus":"OK","httpStatusCode":200,"status":"OK","message":"Import was successful.","response":{"responseType":"ImportSummaries","imported":9,"updated":1,"deleted":0,"ignored":0,"importSummaries":[{"responseType":"ImportSummary","status":"SUCCESS","importCount":{"imported":9,"updated":1,"ignored":0,"deleted":0},"reference":"FzyOAFg6X2I","href":"https://hnqis-dev-ci.psi-mis.org/api/events/FzyOAFg6X2I"}]}}

That event was updated without overwrite the old values( I don't send this values), and it only update or create the new values.

I am playing with that event, and i looked how the POST method works for update the event datevalues.

It only need a event without created date, and only with the new datavalues.

I think we can use the Post method to update the events, without changes in the sdk... 
But i did finished this part using the put method (but it was a bit complex).
The good news are if we use the post method it's more simple.

Maybe you want talk about that.

I need to finish this issue:
test and finish the update of events not downloaded(When a survey is in the server, but we don't have it pulled in local).
(It is working but i want test a bit using post) 

-checks before push if an event in local is older than the events in the server, and use the old event.

-Refactor code(move some methods..)

-Finish test

-Extra: i am getting the eventUid using the api and not the sdk. I can try to do that method in the sdk.

@ifoche i think it can be finish the Monday. But if you need it as soon as be possible, i can finish it tomorrow or the Sunday and not work the Monday.
