### ISSUE TITLE
When the phone language is Spanish, the parent/child relations don't work.

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/malariapp#886]
The children question are always visible.

**Comment by ifoche** [comment]
Sorry @idelcano but testing this bug in the last build from buddybuild (I've tested with French and Spanish on a real device) I'm not able to replicate that bug. Are you sure that it is not something that you've introduced with your changes? Can you please test it with development to be sure that you're able to replicate it there?

**Comment by idelcano** [comment]
You need change the phone language, and after that, you need reinstall or refresh the metadata.
I tested it  with development branch, in real device and in the emulator. And i have this bug always.
I tested it against hnqis and hnqis-dev-ci with my user.

**Comment by ifoche** [comment]
It seems to be a problem on the translation visitors part.
