### ISSUE TITLE
Control dataElements to manage all dates

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#890]

**Comment by ifoche** [comment]
From now on, the dates must be changed into the following scheme:
- [ ] When the user press the + button, that date must be stored as the "Creation Date" in our DB. That date will be stored also in a control dataElement called "_CreatedOn". At that moment, also the user is stored in the DB and filled in the control dataElement "_CreatedBy"
- [ ] When the user mark a survey as completed, the "Completion Date" is stored and the "Event Date" of the survey is set to that completion date.
- [ ] Each time the system tries to send a survey, the "Upload Date" is stored in the control dataElement"_UploadedOn"
- [ ] During the pull process, the control dataElement "_CreatedOn" is translated into the "Creation Date" in our DB. In case of absence of this dataElement, the Event Date is assumed by default. The "Event Date" is translated into the "Completion Date" in our DB. The control dataElement "_UploadedOn" is translated into the "Upload Date" in our DB. In case of absence of this dataElement, the Event Date is assumed by default.
- [ ] Ensure that the scheduled date is being calculated using the completion date and not using the upload date.
- [ ] Ensure that the upload date is recalculated on each iteration where the push is trying to send the survey

**Comment by idelcano** [comment]
I am waiting to test with the Controldataelements. But it should work.

**Comment by ifoche** [comment]
@josemp10 do we have an estimation about when will the control dataElement be ready server side?

**Comment by ifoche** [comment]
@idelcano if I'm not bad, as the control dataElements are not present, the default behavior now is to use Event Date for everything, is that right? (so it's working now, but you say that you're waiting just to check that dates are properly stored there and decoded in the pull)

**Comment by idelcano** [comment]
yes, that is right. But the new dataelements not exist in the push. And the
survey status is set as conflict.
Anyway if you want, i can do the PR.
