### ISSUE TITLE
Modify the about text

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#896]

**Comment by ifoche** [comment]
Include what it's written in [this document](https://docs.google.com/document/d/1Ar1WKW-GORY0srHxA-0oAI1eHHJpr4caf3Yr3ehUG7s/edit). Please note that HNQIS version appears at the top-right. It should be automatically taken from gradle variable instead of modifying it by hand each time we increase the version

**Comment by idelcano** [comment]
Líder de desarrollo conceptual e implementación</p>
