### ISSUE TITLE
Remove lastcommit.txt from repo

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#900]

**Comment by ifoche** [comment]
To make .gitignore work and avoid the continuous problems with moving from one branch to another, it's better if we remove lastcommit.txt from the repo and we create it on demand the first time it's called and it's not present. So the workflow would be:
- We search for lastcommit.txt
- If the file does not exist, we create it with the default context we had "Unavailable" if I'm not bad
- If the file exists, we continue as usually

Otherwise, each time we move from one branch to another we would have to tell git that file we need it to ignore, or disable and enable the post-commit hook to change without having git complains

**Comment by idelcano** [comment]
@ifoche I think that not work.

This problem appears if the script not exist, and the hooks try to run the script, not if the lastcommit.txt not exist.

The last commit is always re-created (with echo "msg" > file, you create the file if not exist).

In this scenary, if the repository not have the hooks, the project can´t compile without lastcommit.txt file.

If the repository have the hooks, and the script, the lastcommit.txt file never should be "Unavailable".

We only need check if the generate_last_commit script exists  in the hooks, before run it.

If the script not exists, exit. If the script exists,  continue as usually

**Comment by ifoche** [comment]
@idelcano I'm not saying that we need to remove the script but the lastcommit.txt file from the repository. The file will be regenerated by the script, of course, but the file won't be tracked by the repository, and as soon as it's in the .gitignore file, the repository won't complain about it. Please let me know if you don't understand what I'm saying and I'll call you to explain it better.

**Comment by idelcano** [comment]
Yes i understand but, if we remove the lastcommit.txt, the "unvailable" message never will show. Because the project can't be compiled without this file.

**Comment by ifoche** [comment]
I think I'm not explaining myself properly. There's a part in the code where you're looking for the content of lastcommit.txt to print it and if the content is "unavailable" then you print it, is that right?

Ok, so now imagine that you check it and if the file is not present, then you can create it with the text "unavailable" inside...wouldn't that make the trick?

**Comment by idelcano** [comment]
@ifoche Ok, i need do it in the android application. It has sense

**Comment by ifoche** [comment]
You may need to change it from raw folder to a file in the assets, I suppose, but just let me know if you find any further problem
