### ISSUE TITLE
The maxEvent limit gets the first events.

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/malariapp#911]
It is easy to reproduce:
Set the maxEvent limit as 1. 
All the events was from 2015.
Related: The event table is not deleted before logout/pull the metadata.
(To reproduce it, we need remove the db first)

**Comment by ifoche** [comment]
As we talked yesterday, this will be addressed by introducing an API call in the SDK to introduce the start and end date for the events and for our apps we will be downloading only the last 6 months in principle. We'll start by hardcoding it and later we will ask the client if they need to put a preference for letting the user to change
