### ISSUE TITLE
Pull the controldataelements uid

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/malariapp#913]

**Comment by idelcano** [comment]
@ifoche i need two things for finish it.

We need add the code value in the follow control dataelements:
"_Overall Class A"	"_Overall Class A"	"2015-10-12T11:35:49.490+0000"	"2015-11-17T07:27:18.235+0000"	"null"	"TgCWRlUXbca"
"_Overall Class B"	"_Overall Class B"	"2015-10-12T11:36:36.360+0000"	"2015-11-17T07:27:36.929+0000"	"null"	"zckZqXOQRHT"	"_Overall Class B"
"_Overall Class C"	"_Overall Class C"	"2015-10-12T11:37:11.948+0000"	"2015-11-17T07:27:54.429+0000"	"null"	"DBUwlPCO0Hd"	"_Overall Class C"

it is null now, i am using the name if the code is null.

And the controldataelements aren´t inside the programs. I think they need be inside the the programs like the others dataelements.

The problem with that is... The sdk are looping the dataelements from inside the programs.(And us too).

**Comment by ifoche** [comment]
@idelcano You have now the code for all the DEs, and, just for the record, as we talked yesterday, the DEs are inside the programs but they aren't inside the ProgramStageSections. With the for loop we added yesterday to the ProgramWrapper of the SDK that should be solved. Please let me know if you cannot find the control DE. I'm realizing that they are not set in the eds-dev server, so I'm going to introduce them there too.

**Comment by ifoche** [comment]
@idelcano it's done. You should be able to see those DEs now in eds-dev also.

**Comment by idelcano** [comment]
I checked it now, and it works ok(with eds-dev in eds flavour too).
