### ISSUE TITLE
Switch button for custom tabs

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/malariapp#918]
Implement the switch button for showing the tables in custom tabs

**Comment by ivanarrizabalaga** [comment]
@ifoche, @josemp10  
I've been checking the **Tanzania EDS R10** that you sent a couple of months ago and this is what I've have seen:

**Adherence tab**
 - It has  a slider on top of the questions(strings.xml:  **adherence_info_switchquestion**).
 - This is not a real question but a static element (see **adherencetab_header0.xml**)
 - The switch element has a listener that changes the visibility of the rest of items.

**Lab Observation.Slide Rechecking**
 - There is NO slider in this tab.
 - I need to find out why questions in this tab are not being shown.

In order to implement the switch widget we need:

 - [ ] A new data element that represents that slide question.
 - [ ] An attribute value with the new constant value (SWITCHBUTTON or something like that)
 - [ ] The parent child relationship modeled in the server for all the question from that tab

**Comment by ivanarrizabalaga** [comment]
@ifoche I need to check if an option is a **yes**.

It is save to consider that the option Yes always will have a 1 factor??

We used to have a method isAYes (still in the code but not used) which relies on checking the string but this is a bad approach that will fail sooner or later.

**Comment by ifoche** [comment]
@ivanarrizabalaga as we talked yesterday, of course you need to have a dataElement for that slide question. But I've checked the server and apparently it is there:
https://eds-dev.psi-mis.org/api/dataElements/ijuzoTy96LL
with Question type RADIO_GROUP_HORIZONTAL, which should be enough to work
and giving a quick check to the parent-child configuration of the dataElements, they seem to be properly set server side to the same hide_group, The parent has its hide type to parent and children to child. Can you re-check that you're not able to see that DE? Even if we don't use the switch and use the radiobutton instead (I'll create the switchbutton answer for you if you get it working with the radiobutton)

**Comment by ivanarrizabalaga** [comment]
All right, I will check whats wrong with this.

I will probably find a spot tomorrow morning. I tell you something.

**Comment by ivanarrizabalaga** [comment]
@ifoche both a header and a question (the one we were missing) are already in the database but somehow they are not being shown. 

Today I will check this first and keep you informed.

**Comment by ivanarrizabalaga** [comment]
There were a bug related to the visibility stuff, I've parcially solved and now the sliding tab is showing ok.

I'm still working in the toggle visibility feature with the questionrows (almost there).

You can change the Yes/No parent question into a switch to give it a try tomorrow completely.

**Comment by ifoche** [comment]
@ivanarrizabalaga I've just created a new Option
Option name: SWITCH_BUTTON
Option code: 12

and I changed that DE Quest Type to SWITCH_BUTTON, so you should be able to see this in a new pull.

@josemp10 I'll document it in the metadata document, but just to let you know, we created this in order to represent the switch button of the custom tabs. Maybe you want to add it to your metadata script. In this thread is detailed which exact DE is affected by this
