### ISSUE TITLE
PushController: saveCreationDateInSDK

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/malariapp#924]
In the pushController class there is a method saveCreationDateInSDK that should NOT be there.

```java
            Log.d(TAG, "Pushing survey data to server...");
            DhisService.sendEventChanges();
            saveCreationDateInSDK(surveys);
```

Since DhisService is **async** it makes no sense to put that there.

That method should be implemented inside the *ConvertTOSDKVisitor.saveSurveyStatus* which the one invoked after a successfull push and is in charge of updating both the survey and the event with the right dates and so.

**Comment by ifoche** [comment]
Sounds logic, @idelcano, can you review this?

**Comment by idelcano** [comment]
[PR ](https://github.com/EyeSeeTea/malariapp/pull/927)
