### ISSUE TITLE
Check in which R10 commit we lost empty CS verification and revert it

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#940]

**Comment by josemp10** [comment]
I think f27bdb8
<https://github.com/EyeSeeTea/malariapp/commit/f27bdb8f41876b320ccac80f60c259aa907740ae>

https://github.com/EyeSeeTea/malariapp/commit/f27bdb8f41876b320ccac80f60c259aa907740ae

**Comment by ifoche** [comment]
Yes, it looks like...and I think that code is correctly deleted. I'll check better if that variable is null before calling to the calculateNumDenTotal() function, or at least refine the Exception to a NullPointerException
