### ISSUE TITLE
ScoreRegister unit tests

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#960]

**Comment by ifoche** [comment]
We need to test a complex CS scenario to be sure that scores are properly working. This has to be a JUnit tests batch, to avoid running the whole interface to this decoupled piece. 

We would need to populate a fake DB with the minimum needed for a scoring test to work, creating the appropriate CSVs for a CS scenario like:

- 0 -- root CS
- 1 
   - 1.1 
      - 1.1.1
   - 1.2 
      - 1.2.1 
      - 1.2.2
      - 1.2.3
- 2
   - 2.1
      - 2.1.1
      - 2.1.2
   - 2.2
      - 2.2.1
   - 2.3
      - 2.3.1
      - 2.3.2
      - 2.3.3

This should be created starting from custom_tabs branch and merging against custom_tabs branch

**Comment by idelcano** [comment]
Updated
