### ISSUE TITLE
EDS bug fixing

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#962]

**Comment by ifoche** [comment]
- [ ] Change version to "EDS 2"
- [ ] When creating a survey, after retrieving the last survey for the program|tabGroup/OU, the dialog that shows the date for the last survey uses an illegible date format (a timestamp). Use a simple date instead (same that we're using on the surveys list)
- [ ] Text "Are you sure you want to completely delete the survey: %s" appears like that, without the substitution of %s by the name of the survey
- [ ] Deleting a survey [do not always work](https://drive.google.com/open?id=0B8KIRhh6kcl6X0s3UEhPS2VCMkU)
- [ ] [Strange OU level bug](https://camo.githubusercontent.com/36b7fd7398f1ba0fd55fe41607f8a8e7c8ccdace/68747470733a2f2f73332d75732d776573742d322e616d617a6f6e6177732e636f6d2f62756464796275696c642d73637265656e73686f74732f3536626262636536636435316134303130306430336136652f3537313666353330666539626234303130306666346130362f66356639323565662d613933612d343735622d623737352d6531346463353966346666642e6a7067)
- [ ] "Level" name [goes out of the screen](https://camo.githubusercontent.com/ecda8c109e45618e71fce61d9356501019ec8f42/68747470733a2f2f73332d75732d776573742d322e616d617a6f6e6177732e636f6d2f62756464796275696c642d73637265656e73686f74732f3536626262636536636435316134303130306430336136652f3537313666353330666539626234303130306666346130362f62323639366636642d313464352d343032372d616338392d3663323565663838633463352e6a7067)
- [ ] For [this prompt] (https://cloud.githubusercontent.com/assets/14224713/14645945/f4108172-0614-11e6-86cc-cdecbb74e674.png), the new redaction should read "Do you want to create a new assessment or modify the latest assessment, dated [xx]"

**Comment by ivanarrizabalaga** [comment]
@ifoche The confirm deletion message for sent surveys should include the name of the selected survey but that is going to be super long:

Example: 
*Are you sure you want to complete delete the survey MWI outlet 1 test 1,Malawi Checklist,Laboratory Observation*

is that ok??

**Comment by ifoche** [comment]
@ivanarrizabalaga yes, that's correct. Don't worry. If they want to make that message shorter they will need to make the name of the survey shorter.
