### ISSUE TITLE
Hide merge functionality

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#982]

**Comment by ifoche** [comment]
- [ ] Assume that all current tabGroups will be separated in the server (will be done by Monday) into different programs
- [ ] Avoid going to the server for getting the last survey
- [ ] Hide the create or modify dialog, and assume always the creation of a new one

**Comment by ivanarrizabalaga** [comment]
@ifoche moving tabgroups stuff into #983 since it is the right issue (everything related to tabgroups instead of the 'modifiying' thing)
