### ISSUE TITLE
Do not read tabgroup attribute anymore and create a fake tabgroup instead

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#983]

**Comment by ifoche** [comment]
This attribute is going to disappear so we need EDS to create its own tabGroup in case there's no tabGroup attribute.

**Comment by ivanarrizabalaga** [comment]
Subtasks:

 - [ ] ConvertFromSDK, remove tabgroup builder stuff
 - [ ] CreateSurveyFragment, remove tabgroup combo
 - [ ] Survey, remove tabgroup from title
 - [ ] Feedback, remove tabgroup from title
