### ISSUE TITLE
Prototype media

### ISSUE THREAD

**Issue by ivanarrizabalaga** [EyeSeeTea/malariapp#994]
Sync video/image in local

 - [x] Add attribute
 - [x] Convert media
 - [x] Add google drive
 - [ ] Pin to those media files
 - [ ] Deal with account login
 - [ ] Review loop over media to sync
 - [ ] Sync only if wifi | space in disk (optional)

**Comment by ifoche** [comment]
- File to test [this one](https://drive.google.com/open?id=0B8KIRhh6kcl6QTFHTW5oODE5ZVU)
- + info [here](https://developers.google.com/drive/android/intro#attribution_requirements)

**Comment by ifoche** [comment]
More videos:
- [This one](https://drive.google.com/open?id=0B8KIRhh6kcl6Sk5fQnZYeVo5cUk)
- [This one](https://drive.google.com/open?id=0B8KIRhh6kcl6Sk5fQnZYeVo5cUk)
- There's a very big one, to test only once we had checked everything's working, as it's very big. Please tell me whenever you think we're ready for that test

**Comment by ifoche** [comment]
- Videos to be embedded only in the feedback section, not in the questionnaires

**Comment by ivanarrizabalaga** [comment]
Just as a potential plan B it is possible to download files from the fileID using the following link directly:

https://docs.google.com/uc?id=0B8KIRhh6kcl6QTFHTW5oODE5ZVU&export=download

Any file under 250MB is downloaded directly, if its a bigger file this trick does not work.

**Comment by ivanarrizabalaga** [comment]
https://stackoverflow.com/questions/37307040/not-able-to-connect-in-a-project-with-variant

**Comment by ivanarrizabalaga** [comment]
Sample elements with attributes:

 - https://hnqis-dev-ci.psi-mis.org/api/dataElements/WnKvWRJaG90

 - https://hnqis-dev-ci.psi-mis.org/api/dataElements/gGQ4TBoARSm

**Comment by ivanarrizabalaga** [comment]
important note:

http://stackoverflow.com/questions/37358495/drive-android-api-is-it-impossible-to-download-public-files-that-were-not-create

**Comment by ivanarrizabalaga** [comment]
Links related to Rest api:

 - Sample code: https://developers.google.com/drive/v3/web/manage-downloads#downloading_a_file

 - Docs on scopes: https://developers.google.com/drive/v2/web/scopes

**Comment by ivanarrizabalaga** [comment]
Api online explorer: https://developers.google.com/apis-explorer/#p/

**Comment by ivanarrizabalaga** [comment]
Logging problems in order to avoid getting lost:

 - [x] Check a basic example that downloads a given file taking its filename
 - [x] Checking that public (not owned) files can be downloaded too.
 - [x] Test basic sample under api 21 (not working since easypermissions require api 23)
 - [x] Compile malariapp with api 23 (no new dependencies):
     - [x] HttpClient is removed in api 23 change code to use okhttp
 - [x] Make pull work again (some scores with "" raising errors, check parseFloat)
 - [x] Add google drive rest dependencies (drive, client, permissions)
     - [x] jsr305 dependency conflict (espresso vs google api client)
     - [x] guava-jdk5 dependency conflict (cannot be exclude directly, requires configurations exclude all)

- [ ] Moving rest code into malariapp
- [ ] Render media into feedback

**Comment by ivanarrizabalaga** [comment]
@ifoche no PR to custom tabs since I guess this is a different release:

Branch:
https://github.com/EyeSeeTea/malariapp/tree/drive_rest_custom_tabs

Finally:

 - Just downloads media with wifi
 - No google account selection (moved into settings.json)
 - Image showed inline, video fullscreen after click
