### ISSUE TITLE
Create github wiki documentation

### ISSUE THREAD

**Issue by ifoche** [EyeSeeTea/malariapp#995]

**Comment by ifoche** [comment]
- [ ] Creation of github wikis for the projects: malariapp (QApp = EDS + HNQIS) and pictureapp (Malaria Case Surveillance)
- Add:
   - Environment setup from zero
      - [ ] git clone, gitflow, android studio config and git branch selection
      - [ ] gradle modifications
   - [ ] DB explanation and diagram
   - For the case of malariapp:
      - [ ] Variants explanation (differences, app that generates, etc)
      - [ ] Activities and user workflow (diagrams)
      - [ ] Background services
      - [ ] json defining the variant structure (app/src/[variant]/res/raw/settings.json)
      - [ ] Tests (how to run them, struture, unittests and instrumented tests)
   - For the case of pictureapp:
      - [ ] Special components
      - [ ] Activities and user workflow (diagrams)
      - [ ] Background services

**Comment by idelcano** [comment]
The wiki not allow upload images to github server. 
I will use this issue to upload the image in github and i will use this link in the wiki.
![db_design 1](https://cloud.githubusercontent.com/assets/5302538/15196988/5d2e4d30-17cf-11e6-9ab4-e30ab92b9760.png)

**Comment by idelcano** [comment]
More wiki images:
![parentnotselected](https://cloud.githubusercontent.com/assets/5302538/15236234/0567b3bc-18c3-11e6-8848-c407c821739c.png)
![planningtab](https://cloud.githubusercontent.com/assets/5302538/15236235/058394d8-18c3-11e6-80cb-68fc222d3386.png)
![planningtab0](https://cloud.githubusercontent.com/assets/5302538/15236238/05965a50-18c3-11e6-907c-abba3a385935.png)
![programfilter](https://cloud.githubusercontent.com/assets/5302538/15236239/05974686-18c3-11e6-8475-0ee4e3373a5e.png)
![pullcomplete](https://cloud.githubusercontent.com/assets/5302538/15236236/0595a952-18c3-11e6-9a4d-ea5100c563b0.png)
![survey](https://cloud.githubusercontent.com/assets/5302538/15236240/059876b4-18c3-11e6-925c-bcd920038cc9.png)
![table](https://cloud.githubusercontent.com/assets/5302538/15236237/05961ed2-18c3-11e6-9ee5-2679f58d2ef4.png)
![changedate](https://cloud.githubusercontent.com/assets/5302538/15236241/059ad4ea-18c3-11e6-98ab-0a673276f2e8.png)
![changedate1](https://cloud.githubusercontent.com/assets/5302538/15236244/05b075de-18c3-11e6-88db-7a38768731ba.png)
![chart](https://cloud.githubusercontent.com/assets/5302538/15236243/05adc316-18c3-11e6-9f81-f969c8c192ef.png)
![createdinplanning](https://cloud.githubusercontent.com/assets/5302538/15236242/05ad3298-18c3-11e6-85d7-d3d8efdd547c.png)
![createdsurvey](https://cloud.githubusercontent.com/assets/5302538/15236247/05b377b6-18c3-11e6-8271-fcfefb9315a6.png)
![dhispulling](https://cloud.githubusercontent.com/assets/5302538/15236245/05b16c3c-18c3-11e6-86e6-8853d81e6070.png)
![editsurvey](https://cloud.githubusercontent.com/assets/5302538/15236246/05b1dcf8-18c3-11e6-9481-0ae91d580a3b.png)
![eulaf](https://cloud.githubusercontent.com/assets/5302538/15236248/05c56aac-18c3-11e6-86aa-bd051f7dd2d4.png)
![feedback](https://cloud.githubusercontent.com/assets/5302538/15236250/05c880fc-18c3-11e6-8b67-d74d3c2f3a6a.png)
![feedbackhide](https://cloud.githubusercontent.com/assets/5302538/15236251/05ca9540-18c3-11e6-9d14-b16e4383a17d.png)
![feedbackhidepass](https://cloud.githubusercontent.com/assets/5302538/15236249/05c81ffe-18c3-11e6-8eb0-d6435f6e2b05.png)
![filterprogram](https://cloud.githubusercontent.com/assets/5302538/15236253/05cd7328-18c3-11e6-869a-80436bd8ad23.png)
![improve](https://cloud.githubusercontent.com/assets/5302538/15236252/05ccafe2-18c3-11e6-9399-6404bb3363dc.png)
![login0](https://cloud.githubusercontent.com/assets/5302538/15236254/05dcc2ba-18c3-11e6-9c86-928e56f0d5a3.png)
![neverassessed](https://cloud.githubusercontent.com/assets/5302538/15236256/05dfec2e-18c3-11e6-962f-7978c0b0dfb6.png)
![parent_child](https://cloud.githubusercontent.com/assets/5302538/15236255/05df023c-18c3-11e6-9334-2c0c4a14f9f8.png)
![eds0](https://cloud.githubusercontent.com/assets/5302538/15236267/177f04b0-18c3-11e6-862d-4dd580c364d8.png)
![eds2](https://cloud.githubusercontent.com/assets/5302538/15236269/17a35bd0-18c3-11e6-9554-14851fcb554d.png)
![eds3](https://cloud.githubusercontent.com/assets/5302538/15236271/17a72d0a-18c3-11e6-960f-06c9e9a94869.png)
![eds5](https://cloud.githubusercontent.com/assets/5302538/15236272/17a7ff64-18c3-11e6-9392-4206177f26e8.png)
![eds6](https://cloud.githubusercontent.com/assets/5302538/15236270/17a58ac2-18c3-11e6-939d-ebc67fde34d6.png)
![eds7](https://cloud.githubusercontent.com/assets/5302538/15236273/17a878ae-18c3-11e6-9df9-e4ddca56d6e1.png)
![eds8](https://cloud.githubusercontent.com/assets/5302538/15236268/17969850-18c3-11e6-8e0f-65039b7c240e.png)
![eds9](https://cloud.githubusercontent.com/assets/5302538/15236274/17aeb066-18c3-11e6-986d-ea4bbbfd83f3.png)
![eds10](https://cloud.githubusercontent.com/assets/5302538/15236275/17ba678a-18c3-11e6-851b-1f7e186bc19b.png)
![eds11](https://cloud.githubusercontent.com/assets/5302538/15236276/17bc84e8-18c3-11e6-91e3-4c99aefa5a64.png)
![edseula](https://cloud.githubusercontent.com/assets/5302538/15236279/17c1e37a-18c3-11e6-9125-cbd7016c8c84.png)
![edsfeedback](https://cloud.githubusercontent.com/assets/5302538/15236277/17bf3030-18c3-11e6-97e7-027bf40b8e42.png)
![eds-level](https://cloud.githubusercontent.com/assets/5302538/15236278/17c12700-18c3-11e6-999f-1deb57d969e2.png)
![activitiesworkflow 1](https://cloud.githubusercontent.com/assets/5302538/15236285/211451d8-18c3-11e6-80a1-62fc06d7b379.png)

**Comment by idelcano** [comment]
![screenshot_20160513-141325](https://cloud.githubusercontent.com/assets/5302538/15249809/e79114c8-1921-11e6-8609-7543d921f6c1.png)
![screenshot_20160513-141331](https://cloud.githubusercontent.com/assets/5302538/15249812/e79361ce-1921-11e6-88c3-3001fe70f37b.png)
![screenshot_20160513-141719](https://cloud.githubusercontent.com/assets/5302538/15249813/e794697a-1921-11e6-9938-c0f8cbc4a627.png)
![screenshot_20160513-141727](https://cloud.githubusercontent.com/assets/5302538/15249814/e79dff8a-1921-11e6-8322-649465b17654.png)
![screenshot_20160513-132621](https://cloud.githubusercontent.com/assets/5302538/15249811/e792e5aa-1921-11e6-8b97-e74ca203127e.png)
![screenshot_20160513-132629](https://cloud.githubusercontent.com/assets/5302538/15249810/e7921d14-1921-11e6-8585-f1aca5cc86c3.png)
![screenshot_20160513-132925](https://cloud.githubusercontent.com/assets/5302538/15249815/e7ac41c6-1921-11e6-8e24-fc25d648bde9.png)
![screenshot_20160513-132929](https://cloud.githubusercontent.com/assets/5302538/15249816/e7ae0e34-1921-11e6-8c20-40a1b9b5cc16.png)
![screenshot_20160513-132935](https://cloud.githubusercontent.com/assets/5302538/15249817/e7ae84fe-1921-11e6-8b08-08802111c2e3.png)
![screenshot_20160513-132941](https://cloud.githubusercontent.com/assets/5302538/15249818/e7af314c-1921-11e6-9e2f-88b8d649d6a9.png)
![screenshot_20160513-132952](https://cloud.githubusercontent.com/assets/5302538/15249819/e7af51ea-1921-11e6-85b2-52d37e757730.png)
![screenshot_20160513-132959](https://cloud.githubusercontent.com/assets/5302538/15249820/e7b88b70-1921-11e6-85c3-fd4d61e52e83.png)
![screenshot_20160513-133010](https://cloud.githubusercontent.com/assets/5302538/15249821/e7c49d02-1921-11e6-8068-3d690fb13e49.png)
![screenshot_20160513-133025](https://cloud.githubusercontent.com/assets/5302538/15249825/e7cb9986-1921-11e6-820e-19250131aa8b.png)
![screenshot_20160513-133051](https://cloud.githubusercontent.com/assets/5302538/15249823/e7c92070-1921-11e6-9e84-a7941c488228.png)
![screenshot_20160513-140628](https://cloud.githubusercontent.com/assets/5302538/15249822/e7c64b7a-1921-11e6-8efe-9c64571d10bd.png)
![screenshot_20160513-141042](https://cloud.githubusercontent.com/assets/5302538/15249824/e7cb4bde-1921-11e6-9806-d0cf62d0cd3a.png)
![screenshot_20160513-141323](https://cloud.githubusercontent.com/assets/5302538/15249826/e7cfbee4-1921-11e6-8a63-0908ce9b8500.png)
![pictureapp activitiesworkflowv1](https://cloud.githubusercontent.com/assets/5302538/15249789/d0cbdb38-1921-11e6-9207-56251d10076d.png)

**Comment by ifoche** [comment]
What about [this](https://help.github.com/articles/adding-images-to-wikis/)? It doesn't work!!??!!

**Comment by idelcano** [comment]
Yes, but you need insert a image url.
